# Generated by Django 5.2.5 on 2026-08-24 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('precisao_metros', models.FloatField(blank=True, help_text='O que o navegador informou; ajuda a não tratar 2 km como se fosse 2 m.', null=True, verbose_name='Precisão (m)')),
                ('momento', models.DateTimeField(verbose_name='Quando')),
                ('origem', models.CharField(choices=[('PONTO', 'Marcação de ponto'), ('MANUAL', 'Envio manual'), ('APP', 'Aplicativo')], default='MANUAL', max_length=8, verbose_name='Origem')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Posição registrada',
                'verbose_name_plural': 'Posições registradas',
                'ordering': ['-momento'],
                'indexes': [models.Index(fields=['usuario', '-momento'], name='maps_posica_usuario_748a0e_idx')],
            },
        ),
    ]
