# Generated by Django 5.2.5 on 2026-08-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coleta_ativa', models.BooleanField(default=False, help_text='Desligado, o mapa mostra apenas a última marcação de ponto.', verbose_name='Coletar posição ao vivo')),
                ('intervalo_minutos', models.PositiveSmallIntegerField(default=5, help_text='De quanto em quanto tempo o navegador reenvia a posição.', verbose_name='Intervalo de envio (min)')),
                ('aviso', models.CharField(blank=True, default='Sua localização está sendo compartilhada com a gestão.', help_text='Texto do selo que aparece no portal enquanto a posição é enviada.', max_length=160, verbose_name='Aviso exibido à pessoa')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do mapa',
                'verbose_name_plural': 'Configuração do mapa',
            },
        ),
    ]
