# Generated by Django 5.2.5 on 2025-08-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('send_to_all', models.BooleanField(default=False, verbose_name='Enviar para Todos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Lido em')),
            ],
            options={
                'verbose_name': 'Leitura de Comunicado',
                'verbose_name_plural': 'Leituras de Comunicados',
                'ordering': ['-read_at'],
            },
        ),
    ]
