# Generated by Django 5.2.5 on 2025-08-26 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_communications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatários'),
        ),
        migrations.AddField(
            model_name='communication',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_communications', to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AddField(
            model_name='communicationread',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.communication', verbose_name='Comunicado'),
        ),
        migrations.AddField(
            model_name='communicationread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='communicationread',
            unique_together={('communication', 'user')},
        ),
    ]
