# Generated by Django 5.2.5 on 2025-08-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationread',
            name='status',
            field=models.CharField(choices=[('NAO_VISUALIZADO', 'Não Visualizado'), ('ESTOU_CIENTE', 'Estou Ciente'), ('ESTOU_COM_DUVIDA', 'Estou com Dúvida')], default='NAO_VISUALIZADO', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='communicationread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
