# Generated by Django 5.2.5 on 2025-08-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_communicationread_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='active_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ativo a partir de'),
        ),
        migrations.AddField(
            model_name='communication',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ativo até'),
        ),
        migrations.AddField(
            model_name='communication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
