# Generated by Django 5.2.5 on 2025-09-02 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_communication_active_from_communication_active_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='clapped_by',
            field=models.ManyToManyField(blank=True, related_name='clapped_communications', to=settings.AUTH_USER_MODEL, verbose_name='Aplaudido por'),
        ),
        migrations.AddField(
            model_name='communication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='communications/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='communication',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Fixar na Dashboard'),
        ),
        migrations.AddField(
            model_name='communication',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_communications', to=settings.AUTH_USER_MODEL, verbose_name='Curtido por'),
        ),
        migrations.AddField(
            model_name='communication',
            name='loved_by',
            field=models.ManyToManyField(blank=True, related_name='loved_communications', to=settings.AUTH_USER_MODEL, verbose_name='Amado por'),
        ),
        migrations.AddField(
            model_name='communication',
            name='sender_group',
            field=models.CharField(blank=True, choices=[('GERENTES', 'Gerentes'), ('COORDENACAO', 'Coordenação'), ('DIRETORIA', 'Diretoria'), ('TODOS', 'Todos'), ('ADM', 'Administração')], max_length=20, null=True, verbose_name='Grupo Remetente'),
        ),
    ]
