# Generated by Django 5.2.5 on 2025-09-02 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_communication_clapped_by_communication_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='is_popup',
            field=models.BooleanField(default=False, verbose_name='Exibir como Pop-up'),
        ),
        migrations.CreateModel(
            name='CommunicationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('can_send', models.BooleanField(default=True, verbose_name='Pode Enviar Comunicados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('members', models.ManyToManyField(blank=True, related_name='communication_groups', to=settings.AUTH_USER_MODEL, verbose_name='Membros')),
            ],
            options={
                'verbose_name': 'Grupo de Comunicação',
                'verbose_name_plural': 'Grupos de Comunicação',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='communication',
            name='custom_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communicationgroup', verbose_name='Grupo Personalizado'),
        ),
    ]
