# Generated by Django 5.2.5 on 2025-09-06 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_communicationcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_communications', to=settings.AUTH_USER_MODEL, verbose_name='Visualizado por'),
        ),
    ]
