# Generated by Django 5.2.5 on 2025-09-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_alter_communication_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='clapped_by',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='loved_by',
        ),
        migrations.AlterField(
            model_name='communication',
            name='sender_group',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True, verbose_name='Grupo Remetente'),
        ),
    ]
