# Generated by Django 5.2.5 on 2025-09-12 18:20

import core.storage
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_remove_communication_clapped_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=core.utils.upload_communication_attachment, verbose_name='Imagem'),
        ),
    ]
