# Generated by Django 5.2.5 on 2025-09-16 19:14

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0011_alter_communication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_communication_attachment, verbose_name='Imagem'),
        ),
    ]
