# Generated by Django 5.2.5 on 2025-10-03 15:24

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0012_alter_communication_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utils.upload_communication_attachment, verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='communications.communication', verbose_name='Comunicado')),
            ],
            options={
                'verbose_name': 'Imagem do Comunicado',
                'verbose_name_plural': 'Imagens do Comunicado',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
