# Generated by Django 5.2.5 on 2026-08-28 17:53

import core.storage
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0015_communication_title_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=core.utils.upload_communication_attachment, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='communicationimage',
            name='image',
            field=models.ImageField(storage=core.storage.MediaStorage, upload_to=core.utils.upload_communication_attachment, verbose_name='Imagem'),
        ),
    ]
