# Generated by Django 5.2.5 on 2026-07-10 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0022_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('message', models.TextField(help_text='Texto exibido no corpo do popup. Quebras de linha são preservadas.', verbose_name='Mensagem')),
                ('icon', models.CharField(blank=True, default='fas fa-bullhorn', max_length=60, verbose_name='Ícone (classe Font Awesome)')),
                ('color', models.CharField(choices=[('indigo', 'Índigo'), ('orange', 'Laranja'), ('amber', 'Âmbar'), ('red', 'Vermelho'), ('green', 'Verde'), ('purple', 'Roxo'), ('blue', 'Azul'), ('slate', 'Cinza')], default='indigo', max_length=20, verbose_name='Cor do cabeçalho')),
                ('completion_mode', models.CharField(choices=[('ACK', 'Ciente — botão de confirmação'), ('LINK', 'Visitar link — conclui ao abrir a ação'), ('EXTERNAL', 'Tarefa do sistema — conclui quando a tarefa é cumprida')], default='ACK', max_length=20, verbose_name='Modo de conclusão')),
                ('action_url', models.CharField(blank=True, help_text='Destino do botão de ação (obrigatório para "Visitar link" e "Tarefa do sistema"). Ex.: /feedback/pesquisa-clima/', max_length=300, verbose_name='URL de ação')),
                ('action_label', models.CharField(blank=True, default='Continuar', max_length=60, verbose_name='Texto do botão de ação')),
                ('external_check_key', models.CharField(blank=True, help_text='Para "Tarefa do sistema": qual condição marca o popup como concluído.', max_length=80, verbose_name='Verificação da tarefa')),
                ('target_all', models.BooleanField(default=False, help_text='Quando marcado, ignora os filtros de usuário/setor/hierarquia.', verbose_name='Todos os usuários')),
                ('target_hierarchies', models.JSONField(blank=True, default=list, help_text='Lista de códigos de hierarquia (ex.: ["PADRAO", "SUPERVISOR"]).', verbose_name='Hierarquias')),
                ('blocking_mode', models.CharField(choices=[('NEVER', 'Nunca bloqueia (sempre pode pular)'), ('AFTER', 'Bloqueia após uma data/hora'), ('ALWAYS', 'Sempre bloqueia até concluir')], default='NEVER', max_length=20, verbose_name='Bloqueio do portal')),
                ('block_after', models.DateTimeField(blank=True, help_text='Só para "Bloqueia após uma data/hora": até lá o popup pode ser pulado; depois passa a travar o portal de quem não concluiu.', null=True, verbose_name='Bloquear a partir de')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Exibir a partir de')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Exibir até')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='Sequência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_popups_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('target_sectors', models.ManyToManyField(blank=True, related_name='portal_popups', to='users.sector', verbose_name='Setores')),
                ('target_users', models.ManyToManyField(blank=True, related_name='portal_popups', to=settings.AUTH_USER_MODEL, verbose_name='Usuários específicos')),
            ],
            options={
                'verbose_name': 'Popup do Portal',
                'verbose_name_plural': 'Popups do Portal',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PopupCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_completions', to=settings.AUTH_USER_MODEL)),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='portal_popups.portalpopup')),
            ],
            options={
                'verbose_name': 'Conclusão de Popup',
                'verbose_name_plural': 'Conclusões de Popup',
                'unique_together': {('popup', 'user')},
            },
        ),
    ]
