# Generated by Django 5.2.5 on 2025-09-07 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.sector', verbose_name='Setores'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Setor principal para compatibilidade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='users.sector', verbose_name='Setor Principal'),
        ),
    ]
