# Generated by Django 5.2.5 on 2025-09-07 06:35

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_sectors_alter_user_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_user_profile_photo),
        ),
    ]
