# Generated by Django 5.2.5 on 2025-09-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hierarchy',
            field=models.CharField(choices=[('PADRAO', 'Padrão'), ('ADMINISTRATIVO', 'Administrativo'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Administração'), ('SUPERADMIN', 'Superadmin')], default='PADRAO', max_length=20, verbose_name='Hierarquia'),
        ),
    ]
