# Generated by Django 5.2.5 on 2025-09-12 18:20

import core.storage
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=core.utils.upload_user_profile_photo),
        ),
    ]
