# Generated by Django 5.2.5 on 2025-09-16 17:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disc_profile',
            field=models.CharField(blank=True, help_text='Perfil comportamental DISC (até 5 letras)', max_length=5, verbose_name='Perfil DISC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_user_profile_photo),
        ),
    ]
