# Generated by Django 5.2.5 on 2025-09-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_disc_profile_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uniform_size_pants',
            field=models.CharField(blank=True, help_text='Ex: P, M, G, GG, 38, 40', max_length=3, verbose_name='Tamanho uniforme (Calça)'),
        ),
        migrations.AddField(
            model_name='user',
            name='uniform_size_shirt',
            field=models.CharField(blank=True, help_text='Ex: P, M, G, GG', max_length=3, verbose_name='Tamanho uniforme (Blusa)'),
        ),
    ]
