# Generated by Django 4.2.16 on 2025-11-30 09:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_uniform_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='team_logo',
            field=models.ImageField(blank=True, help_text='Escudo ou logo do time do setor para o sistema de apostas', null=True, upload_to=users.models.upload_sector_team_logo, verbose_name='Escudo/Logo do Time'),
        ),
    ]
