# Generated by Django 5.2.5 on 2026-01-09 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_team_logo_to_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_comissao_url', models.URLField(default='https://1drv.ms/x/c/871ee1819c7e2faa/IQDp2ONpM_88ToSopGzjlPVdASX6rIFB3_ENXnJcGN3e7Go?e=Q3fDRz', help_text='URL de compartilhamento do OneDrive para a planilha de comissões', max_length=500, verbose_name='Planilha de Comissionamento')),
                ('excel_vendas_url', models.URLField(default='https://1drv.ms/x/c/871ee1819c7e2faa/IQAVeQ-dgEiBTYG0UlK7URSLAQ5r634qBo9-GicO2D8ZfmY', help_text='URL de compartilhamento do OneDrive para vendas e metas', max_length=500, verbose_name='Planilha de Vendas e Metas')),
                ('excel_base_pagamento_url', models.URLField(default='https://1drv.ms/x/c/871ee1819c7e2faa/IQBHZkNccF89Tb0x1dXfoLhiAT8Q5C_fzHlIyUnc2L2FJVs?e=vAO4OX', help_text='URL de compartilhamento do OneDrive para base de pagamento', max_length=500, verbose_name='Planilha BASE_PAGAMENTO')),
                ('excel_base_exclusao_url', models.URLField(default='https://1drv.ms/x/c/871ee1819c7e2faa/IQBryBteOg4sS4cBwU1tIgKoATfi6qmYB8eRrIaTpyP8Qhc?e=pye3Sj', help_text='URL de compartilhamento do OneDrive para base de exclusão', max_length=500, verbose_name='Planilha BASE_EXCLUSAO')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
