# Generated by Django 4.2.16 on 2026-01-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_system_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Login/Código'),
        ),
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='pdv',
            field=models.CharField(blank=True, max_length=100, verbose_name='PDV'),
        ),
        migrations.AddField(
            model_name='user',
            name='pis',
            field=models.CharField(blank=True, max_length=20, verbose_name='PIS'),
        ),
    ]
