# Generated by Django 5.2.5 on 2026-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_hr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Demissão'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_experience_window',
            field=models.BooleanField(default=False, verbose_name='Se Há Janela de Experiencia'),
        ),
    ]
