# Generated by Django 5.2.5 on 2026-05-04 14:08

import core.storage
import core.utils
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_systemconfig_display_reference_and_commission_user_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionspreadsheetversion',
            name='contestacao_phase',
            field=models.CharField(choices=[('antes', 'Antes da Contestação'), ('pos', 'Pós Contestação')], default='pos', help_text='Indica se a versão é antes ou pós contestação', max_length=10, verbose_name='Fase de Contestação'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='team_logo',
            field=models.ImageField(blank=True, help_text='Escudo ou logo do time do setor para o sistema de apostas', null=True, storage=core.storage.MediaStorage(), upload_to=users.models.upload_sector_team_logo, verbose_name='Escudo/Logo do Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to=core.utils.upload_user_profile_photo),
        ),
    ]
