# Generated by Django 5.2.5 on 2026-06-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_commission_version_unique_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pcn',
            field=models.CharField(blank=True, help_text='Percentual CN importado das metas (sheet METAS CN REAL)', max_length=20, verbose_name='PCN'),
        ),
    ]
