# Generated by Django 5.2.5 on 2026-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_pcn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta_eletronicos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta do pilar ELETRONICOS importada das metas (sheet METAS CN REAL)', max_digits=14, null=True, verbose_name='Meta ELETRONICOS'),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_essenciais',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta do pilar ESSENCIAIS importada das metas (sheet METAS CN REAL)', max_digits=14, null=True, verbose_name='Meta ESSENCIAIS'),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_fixa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta do pilar FIXA importada das metas (sheet METAS CN REAL)', max_digits=14, null=True, verbose_name='Meta FIXA'),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_movel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta do pilar MOVEL importada das metas (sheet METAS CN REAL)', max_digits=14, null=True, verbose_name='Meta MOVEL'),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_seguro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta do pilar SEGURO importada das metas (sheet METAS CN REAL)', max_digits=14, null=True, verbose_name='Meta SEGURO'),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_smartphone',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta do pilar SMARTPHONE importada das metas (sheet METAS CN REAL)', max_digits=14, null=True, verbose_name='Meta SMARTPHONE'),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_sva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta do pilar SVA importada das metas (sheet METAS CN REAL)', max_digits=14, null=True, verbose_name='Meta SVA'),
        ),
    ]
