# Generated by Django 5.2.5 on 2026-06-30 23:36

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_commission_monthly_total_aparte_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactivation_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motivo da Inativação'),
        ),
        migrations.AddField(
            model_name='user',
            name='leave_attachment',
            field=models.FileField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to='afastamentos/%Y/%m/', verbose_name='Anexo do Afastamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='leave_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motivo do Afastamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('AFASTADO', 'Afastado')], db_index=True, default='ATIVO', help_text='Situação do colaborador: ativo, inativo ou afastado', max_length=20, verbose_name='Situação'),
        ),
    ]
