# Generated by Django 5.2.5 on 2026-07-01 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_inactivation_reason_user_leave_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Chave da Sessão')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Início da Sessão')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Usuário',
                'verbose_name_plural': 'Sessões de Usuários',
                'ordering': ['-last_activity'],
            },
        ),
    ]
