# Generated by Django 5.2.5 on 2026-07-13 03:28

import core.storage
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Documento')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento Exigido',
                'verbose_name_plural': 'Documentos Exigidos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='pre_registration_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Pré-cadastro'),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_registration_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pré-cadastro'),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_registration_status',
            field=models.CharField(choices=[('NONE', 'Cadastro normal'), ('PENDING', 'Pré-cadastro pendente'), ('COMPLETED', 'Pré-cadastro concluído')], db_index=True, default='NONE', max_length=20, verbose_name='Situação do Pré-cadastro'),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_registration_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token de Pré-cadastro'),
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nome do Documento')),
                ('file', models.FileField(storage=core.storage.MediaStorage(), upload_to=users.models.upload_user_document, verbose_name='Arquivo')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='users.requireddocument', verbose_name='Tipo de Documento')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_user_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Documento do Colaborador',
                'verbose_name_plural': 'Documentos dos Colaboradores',
                'ordering': ['document_name', '-uploaded_at'],
            },
        ),
    ]
