# Generated by Django 5.2.5 on 2026-07-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_requireddocument_user_pre_registration_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leave_return_date',
            field=models.DateField(blank=True, help_text='Data prevista de retorno do colaborador afastado', null=True, verbose_name='Data de Retorno do Afastamento'),
        ),
    ]
