# Generated by Django 4.2.16 on 2026-07-17 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_leave_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pre_registration_extra_documents',
            field=models.ManyToManyField(blank=True, related_name='adjustment_requests', to='users.requireddocument', verbose_name='Documentos Adicionais Solicitados'),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_registration_rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motivo da Reprovação do Pré-cadastro'),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_registration_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Análise do Pré-cadastro'),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_registration_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pre_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Analisado por'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pre_registration_status',
            field=models.CharField(choices=[('NONE', 'Cadastro normal'), ('PENDING', 'Pré-cadastro pendente'), ('COMPLETED', 'Pré-cadastro concluído'), ('APPROVED', 'Pré-cadastro aprovado'), ('REJECTED', 'Pré-cadastro reprovado')], db_index=True, default='NONE', max_length=20, verbose_name='Situação do Pré-cadastro'),
        ),
    ]
