# Generated by Django 4.2.16 on 2026-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_pre_registration_extra_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão do RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg_issuer',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Órgão Emissor do RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDIGENA', 'Indígena')], default='', max_length=10, verbose_name='Cor/Raça'),
        ),
        migrations.AddField(
            model_name='user',
            name='voter_section',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Seção Eleitoral'),
        ),
        migrations.AddField(
            model_name='user',
            name='voter_title',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Título de Eleitor'),
        ),
        migrations.AddField(
            model_name='user',
            name='voter_zone',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Zona Eleitoral'),
        ),
    ]
