# Generated by Django 5.2.5 on 2026-07-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_cep_user_father_name_user_mother_name_user_rg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vacation_end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fim das Férias'),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Início das Férias'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('AFASTADO', 'Afastado'), ('FERIAS', 'Férias')], db_index=True, default='ATIVO', help_text='Situação do colaborador: ativo, inativo, afastado ou de férias', max_length=20, verbose_name='Situação'),
        ),
    ]
