# Generated by Django 5.2.5 on 2026-08-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_vacation_end_date_user_vacation_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='adabas',
            field=models.CharField(blank=True, default='', help_text='Código ADABAS da loja (ex.: ESD0267-013). Vazio para setores que não possuem.', max_length=30, verbose_name='ADABAS'),
        ),
    ]
