# Generated by Django 5.2.5 on 2026-08-06 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_seed_sector_adabas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_complement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthplace',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch_cnpj',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CNPJ Filial'),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'PJ')], default='', max_length=3, verbose_name='Modelo de Contratação'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('FUND_INCOMPLETO', 'Ensino Fundamental incompleto'), ('FUND_COMPLETO', 'Ensino Fundamental completo'), ('MEDIO_INCOMPLETO', 'Ensino Médio incompleto'), ('MEDIO_COMPLETO', 'Ensino Médio completo'), ('SUPERIOR_INCOMPLETO', 'Ensino Superior incompleto'), ('SUPERIOR_COMPLETO', 'Ensino Superior completo'), ('POS', 'Pós-graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], default='', max_length=22, verbose_name='Grau de Instrução'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('HOMEM', 'Homem'), ('MULHER', 'Mulher'), ('NAO_BINARIO', 'Não binário'), ('OUTRO', 'Outro'), ('NAO_INFORMAR', 'Prefiro não informar')], default='', max_length=14, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('UNIAO_ESTAVEL', 'União estável'), ('SEPARADO', 'Separado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)')], default='', max_length=15, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('INTERSEXO', 'Intersexo')], default='', max_length=12, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('relationship', models.CharField(help_text='Grau de parentesco/relação (ex.: mãe, cônjuge, irmão).', max_length=60, verbose_name='Grau')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Contato de Emergência',
                'verbose_name_plural': 'Contatos de Emergência',
                'ordering': ['id'],
            },
        ),
    ]
