# Generated by Django 5.2.5 on 2026-08-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_personal_fields_and_emergency_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salário do colaborador. Visível apenas para quem gerencia usuários.', max_digits=10, null=True, verbose_name='Salário'),
        ),
    ]
