# Generated by Django 5.2.5 on 2026-08-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tangerino_employee_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Preenchido automaticamente pela sincronização; pode ser ajustado à mão.', null=True, unique=True, verbose_name='ID do funcionário no Tangerino'),
        ),
        migrations.AddField(
            model_name='user',
            name='tangerino_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vínculo com o Tangerino feito em'),
        ),
    ]
