# Generated by Django 5.2.5 on 2026-08-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_tangerino_employee_id_user_tangerino_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='excel_contestacao_base_pagamento_url',
            field=models.URLField(blank=True, default='', help_text='URL do OneDrive para a base de pagamento usada na contestação de valores. Precisa ter a coluna RECEBIDO além de RECEITA — é a diferença entre as duas que abre a contestação.', max_length=500, verbose_name='Planilha BASE_PAGAMENTO (Contestação)'),
        ),
    ]
