# Generated by Django 5.2.5 on 2026-08-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_systemconfig_excel_contestacao_base_pagamento_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireddocument',
            name='use_as_profile_photo',
            field=models.BooleanField(default=False, help_text='Quando o colaborador enviar este documento, a imagem vira a foto de perfil dele. Vale só para imagem (JPG, PNG, WEBP) — um PDF é guardado como documento e a foto não muda.', verbose_name='Usar como foto de perfil'),
        ),
    ]
