# Generated by Django 5.2.5 on 2026-08-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_requireddocument_use_as_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', help_text='Preferência de aparência. Fica no cadastro para acompanhar a pessoa em qualquer aparelho.', max_length=5, verbose_name='Tema do portal'),
        ),
    ]
