# Generated by Django 5.2.5 on 2026-08-27 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60, verbose_name='Campo')),
                ('field_label', models.CharField(max_length=80, verbose_name='Nome do campo')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='Antes')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='Depois')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador alterado')),
            ],
            options={
                'verbose_name': 'Alteração de cadastro',
                'verbose_name_plural': 'Alterações de cadastro',
                'ordering': ['-created_at', 'field_label'],
                'indexes': [models.Index(fields=['target', '-created_at'], name='users_userc_target__e59c49_idx')],
            },
        ),
    ]
