# Generated by Django 5.2.5 on 2026-09-03 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_userchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(db_index=True, max_length=50, verbose_name='Módulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Liberado em')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_grants_made', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acesso a módulo (individual)',
                'verbose_name_plural': 'Acessos a módulos (individuais)',
                'ordering': ['user__first_name', 'module_key'],
                'constraints': [models.UniqueConstraint(fields=('user', 'module_key'), name='uniq_user_module')],
            },
        ),
    ]
