# Generated by Django 5.2.5 on 2026-09-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_usermoduleaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pix_key',
            field=models.CharField(blank=True, default='', help_text='CPF, CNPJ, celular, e-mail ou chave aleatória.', max_length=140, verbose_name='Chave PIX'),
        ),
    ]
