# Generated by Django 5.2.5 on 2026-09-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_pix_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='commission_view_access',
            field=models.JSONField(blank=True, default=dict, help_text='Quem pode abrir cada visão de /users/commission/ (Todos, Gerentes, Coordenadores)', verbose_name='Liberação das visões do comissionamento'),
        ),
    ]
