# Generated by Django 5.2.5 on 2026-09-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_systemconfig_commission_view_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='commission_view_access',
        ),
        migrations.AddField(
            model_name='commissionspreadsheetversion',
            name='liberado_para',
            field=models.CharField(choices=[('TODOS', 'Todos'), ('GERENTES', 'Somente Gerentes'), ('COORDENADORES', 'Somente Coordenadores'), ('GERENTES_COORDENADORES', 'Gerentes e Coordenadores')], default='TODOS', help_text='Quem enxerga esta versão no comissionamento', max_length=24, verbose_name='Liberado para'),
        ),
    ]
