# Generated by Django 5.2.5 on 2026-09-23 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_systemconfig_commission_view_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_dependents',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Possui dependentes'),
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('document', models.CharField(help_text='CPF ou número da certidão de nascimento.', max_length=30, verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
                'ordering': ['id'],
            },
        ),
    ]
