# Generated by Django 5.2.5 on 2026-10-01 12:06

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_dependentes_do_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformativoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Como funciona o Comissionamento?', help_text='O que a pessoa lê no botão, em qualquer visão do comissionamento.', max_length=120, verbose_name='Texto do botão')),
                ('descricao', models.CharField(blank=True, help_text='Uma linha explicando o que é o material.', max_length=240, verbose_name='Descrição (opcional)')),
                ('arquivo', models.FileField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to='comissionamento/informativo/%Y/%m/', verbose_name='Arquivo (PDF, imagem ou vídeo)')),
                ('link', models.URLField(blank=True, help_text='Vídeo no YouTube/Drive, apresentação, página.', verbose_name='Ou um link')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo'), ('LINK', 'Link')], default='PDF', max_length=8, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Mostrar no comissionamento')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informativos_comissao', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Informativo do comissionamento',
                'verbose_name_plural': 'Informativos do comissionamento',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
