# Generated by Django 5.2.5 on 2026-10-01 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_informativo_comissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacaoHC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateField(help_text='Sempre o dia 1º do mês conferido.', verbose_name='Mês de referência')),
                ('validado_em', models.DateTimeField(auto_now_add=True, verbose_name='Validado em')),
                ('quantidade', models.PositiveSmallIntegerField(default=0, help_text='Quantos colaboradores ativos a loja tinha quando foi conferida.', verbose_name='Quadro no momento da validação')),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='Observação')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes_hc', to='users.sector', verbose_name='Loja')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes_hc', to=settings.AUTH_USER_MODEL, verbose_name='Quem validou')),
            ],
            options={
                'verbose_name': 'Validação de HC',
                'verbose_name_plural': 'Validações de HC',
                'ordering': ['-referencia', 'setor__name'],
                'constraints': [models.UniqueConstraint(fields=('setor', 'referencia'), name='uniq_hc_setor_mes')],
            },
        ),
    ]
