# Generated by Django 5.2.5 on 2026-10-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_validacao_hc'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='display_reference_phase',
            field=models.CharField(blank=True, db_default='', default='', help_text='Fase padrão (antes/pos) exibida no /users/commission/ quando não houver seleção manual', max_length=10, verbose_name='Fase de Exibição do Comissionamento'),
        ),
    ]
