# Generated by Django 5.2.5 on 2025-09-16 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da empresa fornecedora', max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(help_text='CNPJ da empresa (formato: 00.000.000/0000-00)', max_length=18, unique=True, verbose_name='CNPJ')),
                ('contact', models.CharField(help_text='Nome da pessoa de contato ou telefone/email', max_length=200, verbose_name='Contato')),
                ('area_of_operation', models.CharField(help_text='Área de atuação da empresa', max_length=300, verbose_name='Onde atua')),
                ('services', models.TextField(help_text='Descrição dos serviços/produtos oferecidos', verbose_name='O que faz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_suppliers', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
    ]
