# Generated by Django 5.2.5 on 2026-06-01 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SniperAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sniper_coordinator_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador')),
                ('sniper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sniper_assignment', to=settings.AUTH_USER_MODEL, verbose_name='Sniper')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sniper_assignment_updates', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Atribuição de Sniper',
                'verbose_name_plural': 'Atribuições de Snipers',
            },
        ),
    ]
