# Generated by Django 5.2.5 on 2026-04-06 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('source_file_name', models.CharField(blank=True, max_length=255, verbose_name='Arquivo origem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Carga de Metas',
                'verbose_name_plural': 'Cargas de Metas',
                'ordering': ['-year', '-month', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_type', models.CharField(choices=[('METAS_CN_REAL', 'METAS CN REAL'), ('META_PDV_REAL', 'META PDV REAL')], max_length=20, verbose_name='Sheet')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do usuario')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='Loja')),
                ('pilar', models.CharField(blank=True, max_length=255, verbose_name='Pilar')),
                ('goal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Meta')),
                ('row_number', models.PositiveIntegerField(default=0, verbose_name='Linha na planilha')),
                ('row_data', models.JSONField(blank=True, default=dict, verbose_name='Dados da linha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='power_bi.goalupload', verbose_name='Carga')),
            ],
            options={
                'verbose_name': 'Item de Meta',
                'verbose_name_plural': 'Itens de Metas',
                'ordering': ['sheet_type', 'row_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='goalupload',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_goal_upload_by_month_year'),
        ),
        migrations.AddIndex(
            model_name='goalentry',
            index=models.Index(fields=['sheet_type'], name='power_bi_go_sheet_t_87159a_idx'),
        ),
        migrations.AddIndex(
            model_name='goalentry',
            index=models.Index(fields=['user_name'], name='power_bi_go_user_na_b7d183_idx'),
        ),
        migrations.AddIndex(
            model_name='goalentry',
            index=models.Index(fields=['store_name'], name='power_bi_go_store_n_9ca017_idx'),
        ),
        migrations.AddIndex(
            model_name='goalentry',
            index=models.Index(fields=['pilar'], name='power_bi_go_pilar_68414d_idx'),
        ),
    ]
