# Generated by Django 5.2.5 on 2026-04-06 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0002_goalupload_goalentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de acesso')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='power_bi.powerbireport', verbose_name='Relatorio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_bi_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Acesso Power BI',
                'verbose_name_plural': 'Logs de Acesso Power BI',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['accessed_at'], name='power_bi_po_accesse_c844d2_idx'), models.Index(fields=['user', 'accessed_at'], name='power_bi_po_user_id_52db31_idx'), models.Index(fields=['report', 'accessed_at'], name='power_bi_po_report__a49cdb_idx')],
            },
        ),
    ]
