# Generated by Django 5.2.5 on 2026-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0013_communicationimage'),
        ('power_bi', '0003_powerbiaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerbireport',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='power_bi_reports', to='communications.communicationgroup', verbose_name='Grupos permitidos'),
        ),
    ]
