# Generated by Django 5.2.5 on 2026-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0004_alter_powerbireport_allowed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbireport',
            name='allow_open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Nova guia permitida'),
        ),
    ]
