# Generated by Django 5.2.5 on 2026-04-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0005_powerbireport_allow_open_in_new_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalupload',
            name='fixa_as_percentage',
            field=models.BooleanField(default=False, verbose_name='FIXA em percentual'),
        ),
    ]
