# Generated by Django 4.2.16 on 2025-10-13 14:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_add_uniform_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('comment', models.TextField(help_text='Descreva o motivo do elogio', verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliments_given', to=settings.AUTH_USER_MODEL, verbose_name='De')),
                ('to_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliments_received', to='users.sector', verbose_name='Para setor')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliments_received', to=settings.AUTH_USER_MODEL, verbose_name='Para usuário')),
            ],
            options={
                'verbose_name': 'Elogio',
                'verbose_name_plural': 'Elogios',
                'ordering': ['-created_at'],
            },
        ),
    ]
