# Generated by Django 4.2.16 on 2025-10-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliments', '0001_initial'),
    ]

    operations = [
    ]
