# Generated by Django 5.2.5 on 2025-09-16 19:06

import django.db.models.deletion
import projects.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_user_disc_profile_alter_user_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Atividade')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('deadline', models.DateField(verbose_name='Prazo')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('NAO_INICIADA', 'Não Iniciada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='NAO_INICIADA', max_length=15, verbose_name='Status')),
                ('priority', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parent_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_activities', to='projects.activity', verbose_name='Atividade Pai')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_activities', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['order', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.activity', verbose_name='Atividade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Comentário da Atividade',
                'verbose_name_plural': 'Comentários das Atividades',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('scope', models.TextField(help_text='Descrição completa do escopo do projeto', verbose_name='Escopo Total')),
                ('reason', models.TextField(help_text='Justificativa para o projeto', verbose_name='Motivo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('deadline', models.DateField(verbose_name='Prazo')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('STANDBY', 'Stand By'), ('EM_ANDAMENTO', 'Em Andamento'), ('EM_TESTE', 'Em Teste'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='STANDBY', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentagem de conclusão do projeto', max_digits=5, verbose_name='Progresso (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Principal')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sector', verbose_name='Setor Responsável')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project', verbose_name='Projeto'),
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models.upload_project_attachment, verbose_name='Arquivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome Original do Arquivo')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('content_type', models.CharField(blank=True, max_length=255, verbose_name='Tipo de Conteúdo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project', verbose_name='Projeto')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo do Projeto',
                'verbose_name_plural': 'Anexos dos Projetos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSectorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_projects', models.BooleanField(default=False, verbose_name='Pode ver projetos')),
                ('can_create_projects', models.BooleanField(default=False, verbose_name='Pode criar projetos')),
                ('can_manage_all_projects', models.BooleanField(default=False, verbose_name='Pode gerenciar todos os projetos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_access', to='users.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Acesso de Setor a Projetos',
                'verbose_name_plural': 'Acessos de Setores a Projetos',
            },
        ),
    ]
