# Generated by Django 5.2.5 on 2025-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20250916_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, help_text='Categoria para organização no Kanban', max_length=50, verbose_name='Categoria'),
        ),
    ]
