# Generated by Django 5.2.5 on 2025-10-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_supportchat_taskchat_taskchatmessage_and_more'),
        ('users', '0008_add_uniform_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchat',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_chats', to='users.sector', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_categories', to='users.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Categoria de Suporte',
                'verbose_name_plural': 'Categorias de Suporte',
                'unique_together': {('name', 'sector')},
            },
        ),
        migrations.AddField(
            model_name='supportchat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_chats', to='projects.supportcategory', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='SupportChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_chat_files/%Y/%m/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio'), ('DOCUMENT', 'Documento')], max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.supportchat')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.supportchatmessage')),
            ],
            options={
                'verbose_name': 'Arquivo do Chat',
                'verbose_name_plural': 'Arquivos do Chat',
            },
        ),
        migrations.CreateModel(
            name='SupportChatRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')])),
                ('feedback', models.TextField(blank=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='projects.supportchat')),
            ],
            options={
                'verbose_name': 'Avaliação do Atendimento',
                'verbose_name_plural': 'Avaliações do Atendimento',
            },
        ),
    ]
