# Generated by Django 5.2.7 on 2025-10-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_supportchat_sector_supportcategory_and_more'),
        ('users', '0008_add_uniform_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportagent',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='support_agents', to='users.sector', verbose_name='Setores atendidos'),
        ),
    ]
