# Generated by Django 5.2.5 on 2025-12-11 14:13

from django.db import migrations, models
import random
import string
from datetime import datetime


def generate_protocol():
    """Gera um protocolo único no formato: YYYYMMDD-XXXXX"""
    date_part = datetime.now().strftime('%Y%m%d')
    random_part = ''.join(random.choices(string.ascii_uppercase + string.digits, k=5))
    return f"{date_part}-{random_part}"


def populate_protocols(apps, schema_editor):
    """Gera protocolos para chats existentes"""
    SupportChat = apps.get_model('projects', 'SupportChat')
    existing_protocols = set()
    
    for chat in SupportChat.objects.all():
        protocol = generate_protocol()
        # Garantir unicidade
        while protocol in existing_protocols:
            protocol = generate_protocol()
        existing_protocols.add(protocol)
        chat.protocol = protocol
        chat.save(update_fields=['protocol'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_supportagent_sectors'),
    ]

    operations = [
        # Primeiro adicionar campo sem unique
        migrations.AddField(
            model_name='supportchat',
            name='protocol',
            field=models.CharField(blank=True, max_length=20, verbose_name='Protocolo'),
        ),
        # Preencher protocolos existentes
        migrations.RunPython(populate_protocols, migrations.RunPython.noop),
        # Agora adicionar unique constraint
        migrations.AlterField(
            model_name='supportchat',
            name='protocol',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='supportchat',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando na Fila'), ('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado')], default='AGUARDANDO', max_length=20),
        ),
    ]
