# Generated by Django 5.2.5 on 2026-02-05 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_protocol_and_queue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcategory',
            name='default_agent',
            field=models.ForeignKey(blank=True, help_text='Agente que será automaticamente atribuído aos tickets desta categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_support_categories', to=settings.AUTH_USER_MODEL, verbose_name='Agente Padrão'),
        ),
    ]
