# Generated by Django 5.2.5 on 2026-03-09 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_default_agent_to_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchat',
            name='agent_first_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primeira resposta do agente'),
        ),
        migrations.AddField(
            model_name='supportchat',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do atendimento'),
        ),
        migrations.AddField(
            model_name='supportchat',
            name='store_first_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primeira resposta da loja'),
        ),
        migrations.AlterField(
            model_name='supportcategory',
            name='default_agents',
            field=models.ManyToManyField(blank=True, help_text='Agentes que serão notificados automaticamente sobre tickets desta categoria', related_name='default_support_categories', to=settings.AUTH_USER_MODEL, verbose_name='Agentes Padrão'),
        ),
    ]
