# Generated by Django 5.2.5 on 2026-05-26 13:45

import core.storage
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_supportcategory_request_customer_cpf_and_chat_customer_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattachment',
            name='file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=projects.models.upload_project_attachment, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='supportchatfile',
            name='file',
            field=models.FileField(storage=core.storage.MediaStorage(), upload_to='support_chat_files/%Y/%m/'),
        ),
    ]
