# Generated by Django 4.2.16 on 2026-06-23 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_user_pcn'),
        ('projects', '0012_alter_projectattachment_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=40, verbose_name='IMEI')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('status', models.CharField(choices=[('AGUARDANDO_RECEBIMENTO', 'Aguardando resposta da loja que irá receber'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO_RECEBIMENTO', max_length=30, verbose_name='Status')),
                ('response_notes', models.TextField(blank=True, verbose_name='Observação da resposta')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_transfer_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('receiving_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Gerente/ADM responsável por receber')),
                ('receiving_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_requests', to='users.sector', verbose_name='Loja que irá receber')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_transfer_responses', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('sending_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Gerente/ADM responsável por enviar')),
                ('sending_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_requests', to='users.sector', verbose_name='Loja que irá enviar')),
            ],
            options={
                'verbose_name': 'Transferência de Suporte',
                'verbose_name_plural': 'Transferências de Suporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
