# Generated by Django 5.2.5 on 2026-08-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_supporttransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporttransferrequest',
            name='material',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Material'),
        ),
    ]
