[variables]
PYTHON_VERSION = "3.11"

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn redeconfianca.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
