# Configuração mínima para Nixpacks
[variables]
PYTHON_VERSION = "3.11"

[start]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn redeconfianca.wsgi:application --bind 0.0.0.0:$PORT"
