# Generated by Django 5.2.5 on 2025-08-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_LOGIN', 'Login de Usuário'), ('USER_LOGOUT', 'Logout de Usuário'), ('TICKET_CREATE', 'Criação de Chamado'), ('TICKET_UPDATE', 'Atualização de Chamado'), ('CS_CHANGE', 'Alteração de C$'), ('PRIZE_REDEEM', 'Resgate de Prêmio'), ('COMMUNICATION_SEND', 'Envio de Comunicado'), ('USER_CREATE', 'Criação de Usuário'), ('USER_UPDATE', 'Atualização de Usuário'), ('ADMIN_ACTION', 'Ação Administrativa')], max_length=20, verbose_name='Tipo de Ação')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'ordering': ['-created_at'],
            },
        ),
    ]
