# Generated by Django 5.2.5 on 2025-09-07 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tutorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action_type',
            field=models.CharField(choices=[('USER_LOGIN', 'Login de Usuário'), ('USER_LOGOUT', 'Logout de Usuário'), ('TICKET_CREATE', 'Criação de Chamado'), ('TICKET_UPDATE', 'Atualização de Chamado'), ('CS_CHANGE', 'Alteração de C$'), ('PRIZE_REDEEM', 'Resgate de Prêmio'), ('COMMUNICATION_SEND', 'Envio de Comunicado'), ('USER_CREATE', 'Criação de Usuário'), ('USER_UPDATE', 'Atualização de Usuário'), ('ADMIN_ACTION', 'Ação Administrativa'), ('PRIZE_CATEGORY_CREATE', 'Criação de Categoria de Prêmio'), ('PRIZE_CATEGORY_UPDATE', 'Atualização de Categoria de Prêmio'), ('PRIZE_CATEGORY_DELETE', 'Exclusão de Categoria de Prêmio')], max_length=50, verbose_name='Tipo de Ação'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('HARASSMENT', 'Assédio/Bullying'), ('INAPPROPRIATE_CONTENT', 'Conteúdo Inadequado'), ('SPAM', 'Spam'), ('FAKE_INFO', 'Informação Falsa'), ('DISCRIMINATION', 'Discriminação'), ('VIOLENCE', 'Violência/Ameaças'), ('OTHER', 'Outro')], max_length=30, verbose_name='Tipo de Denúncia')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='reports/evidence/', verbose_name='Evidência')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('UNDER_REVIEW', 'Em Análise'), ('RESOLVED', 'Resolvida'), ('DISMISSED', 'Descartada')], default='PENDING', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20, verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas do Administrador')),
                ('resolution', models.TextField(blank=True, verbose_name='Resolução')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Denúncia Anônima')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Denunciado')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Denunciante')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False, verbose_name='Comentário Interno')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário da Denúncia',
                'verbose_name_plural': 'Comentários das Denúncias',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='core_report_status_9a134a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', 'created_at'], name='core_report_reporte_858505_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user', 'created_at'], name='core_report_reporte_b1c360_idx'),
        ),
    ]
