# Generated by Django 5.2.5 on 2025-09-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_systemlog_action_type_report_reportcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action_type',
            field=models.CharField(choices=[('USER_LOGIN', 'Login de Usuário'), ('USER_LOGOUT', 'Logout de Usuário'), ('TICKET_CREATE', 'Criação de Chamado'), ('TICKET_UPDATE', 'Atualização de Chamado'), ('CS_CHANGE', 'Alteração de C$'), ('PRIZE_REDEEM', 'Resgate de Prêmio'), ('COMMUNICATION_SEND', 'Envio de Comunicado'), ('USER_CREATE', 'Criação de Usuário'), ('USER_UPDATE', 'Atualização de Usuário'), ('ADMIN_ACTION', 'Ação Administrativa'), ('PRIZE_CATEGORY_CREATE', 'Criação de Categoria de Prêmio'), ('PRIZE_CATEGORY_UPDATE', 'Atualização de Categoria de Prêmio'), ('PRIZE_CATEGORY_DELETE', 'Exclusão de Categoria de Prêmio'), ('SECTOR_CREATE', 'Criação de Setor'), ('SECTOR_EDIT', 'Edição de Setor'), ('SECTOR_DELETE', 'Exclusão de Setor'), ('CATEGORY_CREATE', 'Criação de Categoria'), ('CATEGORY_UPDATE', 'Atualização de Categoria'), ('CATEGORY_DELETE', 'Exclusão de Categoria'), ('WEBHOOK_CREATE', 'Criação de Webhook'), ('WEBHOOK_UPDATE', 'Atualização de Webhook'), ('WEBHOOK_DELETE', 'Exclusão de Webhook'), ('REPORT_CREATE', 'Criação de Denúncia'), ('REPORT_UPDATE', 'Atualização de Denúncia'), ('REPORT_COMMENT', 'Comentário em Denúncia')], max_length=50, verbose_name='Tipo de Ação'),
        ),
    ]
