# Generated by Django 5.2.5 on 2025-09-07 06:35

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_systemlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.upload_report_evidence, verbose_name='Evidência'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='pdf_file',
            field=models.FileField(upload_to=core.utils.upload_tutorial_pdf, verbose_name='Arquivo PDF'),
        ),
    ]
