# Generated by Django 5.2.5 on 2025-09-11 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_report_evidence_alter_tutorial_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('notification_type', models.CharField(choices=[('FILE', 'Novo Arquivo'), ('TICKET', 'Novo Chamado'), ('TRAINING', 'Novo Treinamento'), ('COMMUNICATION', 'Novo Comunicado'), ('TICKET_UPDATE', 'Atualização de Chamado'), ('SYSTEM', 'Notificação do Sistema')], max_length=20, verbose_name='Tipo')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do objeto relacionado')),
                ('related_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL relacionada')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
