# Generated by Django 5.2.5 on 2025-09-12 18:20

import core.storage
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='evidence',
            field=models.FileField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=core.utils.upload_report_evidence, verbose_name='Evidência'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='pdf_file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=core.utils.upload_tutorial_pdf, verbose_name='Arquivo PDF'),
        ),
    ]
