# Generated by Django 5.2.5 on 2025-09-26 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_trainingcategory_checklisttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailychecklist',
            unique_together={('user', 'title', 'date')},
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='repeat_daily',
            field=models.BooleanField(default=False, verbose_name='Repetir todos os dias'),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_checklists', to='core.checklisttemplate', verbose_name='Template'),
        ),
    ]
