# Generated by Django 5.2.5 on 2025-09-30 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notification_user'),
        ('users', '0008_add_uniform_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='blue', help_text='Cor para exibição no Kanban', max_length=20, verbose_name='Cor')),
                ('icon', models.CharField(default='fas fa-tag', max_length=50, verbose_name='Ícone Font Awesome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sectors', models.ManyToManyField(blank=True, to='users.sector', verbose_name='Setores que podem usar esta categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Tarefa',
                'verbose_name_plural': 'Categorias de Tarefas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.taskcategory', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('message_type', models.CharField(choices=[('MESSAGE', 'Mensagem'), ('STATUS_UPDATE', 'Atualização de Status'), ('SYSTEM', 'Sistema')], default='MESSAGE', max_length=20, verbose_name='Tipo da Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.taskactivity', verbose_name='Tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Mensagem da Tarefa',
                'verbose_name_plural': 'Mensagens das Tarefas',
                'ordering': ['created_at'],
            },
        ),
    ]
