# Generated by Django 5.2.5 on 2025-10-07 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_taskcategory_taskactivity_category_taskmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychecklist',
            name='is_recurring_instance',
            field=models.BooleanField(default=False, verbose_name='Instância de Recorrência'),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='parent_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='core.dailychecklist'),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='repeat_days',
            field=models.JSONField(blank=True, default=list, help_text='Lista de dias: 0=Segunda, 1=Terça, ..., 6=Domingo', verbose_name='Dias da Semana'),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='repeat_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final da Repetição'),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='repeat_type',
            field=models.CharField(choices=[('NONE', 'Não repetir'), ('DAILY', 'Todos os dias'), ('WEEKDAYS', '30 dias (exceto finais de semana)'), ('CUSTOM_DAYS', 'Dias específicos')], default='NONE', max_length=20, verbose_name='Tipo de Repetição'),
        ),
    ]
