# Generated by Django 5.2.5 on 2025-10-09 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dailychecklist_is_recurring_instance_and_more'),
        ('users', '0008_add_uniform_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20, verbose_name='Prioridade')),
                ('estimated_time_minutes', models.PositiveIntegerField(default=30, verbose_name='Tempo Estimado (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requer Aprovação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_admin_templates', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_checklist_templates', to='users.sector', verbose_name='Setor Responsável')),
            ],
            options={
                'verbose_name': 'Template de Checklist Administrativo',
                'verbose_name_plural': 'Templates de Checklist Administrativo',
                'ordering': ['sector__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DailyAdminChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_daily_admin_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Checklist Administrativo Diário',
                'verbose_name_plural': 'Checklists Administrativos Diários',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='AdminChecklistAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_admin_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.adminchecklisttemplate', verbose_name='Template da Tarefa')),
            ],
            options={
                'verbose_name': 'Atribuição de Tarefa Administrativa',
                'verbose_name_plural': 'Atribuições de Tarefas Administrativas',
                'ordering': ['task_template__sector__name', 'task_template__title'],
                'unique_together': {('task_template', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AdminChecklistTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas da Revisão')),
                ('execution_notes', models.TextField(blank=True, verbose_name='Observações da Execução')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admin_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído para')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admin_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='core.adminchecklisttemplate', verbose_name='Template')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.dailyadminchecklist', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Tarefa do Checklist Administrativo',
                'verbose_name_plural': 'Tarefas do Checklist Administrativo',
                'ordering': ['template__sector__name', 'template__title'],
                'unique_together': {('checklist', 'template')},
            },
        ),
    ]
