# Generated by Django 5.2.5 on 2025-10-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_adminchecklisttemplate_dailyadminchecklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchecklisttemplate',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instruções detalhadas sobre como executar esta tarefa', null=True, verbose_name='Instruções de Execução'),
        ),
    ]
