# Generated by Django 5.2.5 on 2025-10-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_adminchecklisttask_options_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Criar o novo modelo AdminChecklistSectorTask
        migrations.CreateModel(
            name='AdminChecklistSectorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20, verbose_name='Prioridade')),
                ('estimated_time_minutes', models.PositiveIntegerField(default=30, verbose_name='Tempo Estimado (minutos)')),
                ('instructions', models.TextField(blank=True, verbose_name='Instruções de Execução')),
                ('date_requested', models.DateField(verbose_name='Data Solicitada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado pelo Superadmin')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sector_tasks', to='users.sector', verbose_name='Setor que Criou')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_admin_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sector_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
            ],
            options={
                'verbose_name': 'Tarefa de Setor - Checklist ADM',
                'verbose_name_plural': 'Tarefas de Setor - Checklist ADM',
                'ordering': ['-created_at', 'priority'],
            },
        ),
        
        # Modificar AdminChecklistTemplate para tornar null=True
        migrations.AlterField(
            model_name='adminchecklisttask',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='core.adminchecklisttemplate', verbose_name='Template'),
        ),
        
        # Adicionar novos campos ao AdminChecklistTask
        migrations.AddField(
            model_name='adminchecklisttask',
            name='sector_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='core.adminchecklistsectortask', verbose_name='Tarefa do Setor'),
        ),
        migrations.AddField(
            model_name='adminchecklisttask',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='adminchecklisttask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='adminchecklisttask',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Instruções'),
        ),
    ]
