# Generated by Django 4.2.16 on 2025-10-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20251009_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='custom_status',
            field=models.CharField(blank=True, help_text='Para templates com status personalizados', max_length=100, verbose_name='Status Personalizado'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_not_applicable',
            field=models.BooleanField(default=False, verbose_name='Não se aplica'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='custom_statuses',
            field=models.JSONField(blank=True, default=list, help_text="Lista de status customizados: [{'label': 'Nome', 'icon': 'fas fa-star', 'color': 'blue'}]", verbose_name='Status Personalizados'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='use_custom_statuses',
            field=models.BooleanField(default=False, verbose_name='Usar Status Personalizados'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('DOING', 'Fazendo'), ('DONE', 'Feito'), ('NOT_APPLICABLE', 'Não se aplica')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
    ]
