# Generated by Django 4.2.16 on 2025-10-28 14:40

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_checklistitem_custom_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.upload_task_attachment, verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('file_size', models.BigIntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.taskactivity', verbose_name='Tarefa')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo da Tarefa',
                'verbose_name_plural': 'Anexos das Tarefas',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
