# Generated by Django 4.2.16 on 2025-12-04 14:09

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_add_task_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('document', 'Documento')], max_length=20, verbose_name='Tipo de Evidência')),
                ('file', models.FileField(upload_to=core.models.upload_checklist_item_evidence, verbose_name='Arquivo')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nome Original do Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='core.checklistitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_item_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Evidência do Item de Checklist',
                'verbose_name_plural': 'Evidências dos Itens de Checklist',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
