# Generated by Django 5.2.5 on 2026-01-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo'),
        ),
    ]
