# Generated by Django 5.2.5 on 2026-09-03 17:50

import core.models
import core.storage
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_make_due_date_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemevidence',
            name='file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=core.models.upload_checklist_item_evidence, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='evidence',
            field=models.FileField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=core.utils.upload_report_evidence, verbose_name='Evidência'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=core.models.upload_task_attachment, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='pdf_file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=core.utils.upload_tutorial_pdf, verbose_name='Arquivo PDF'),
        ),
    ]
