# Generated by Django 5.2.5 on 2026-09-24 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=40, unique=True, verbose_name='Chave')),
                ('tipo_erro', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Tipo do erro')),
                ('data_venda', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data da venda')),
                ('pdv', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='PDV')),
                ('loja_vivogo', models.CharField(blank=True, max_length=120, verbose_name='Loja Vivo go')),
                ('id_venda', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='ID da venda')),
                ('nome_cliente', models.CharField(blank=True, max_length=180, verbose_name='Cliente')),
                ('documento_vivogo', models.CharField(blank=True, max_length=30, verbose_name='Documento')),
                ('produto_vivogo', models.CharField(blank=True, max_length=255, verbose_name='Produto Vivo go')),
                ('produto_sap', models.CharField(blank=True, max_length=255, verbose_name='Produto SAP')),
                ('sku_vivogo', models.CharField(blank=True, max_length=60, verbose_name='SKU Vivo go')),
                ('serial_vivogo', models.CharField(blank=True, max_length=300, verbose_name='Serial Vivo go')),
                ('serial_sap', models.TextField(blank=True, verbose_name='Serial SAP')),
                ('ordem_sap', models.CharField(blank=True, max_length=30, verbose_name='Ordem SAP')),
                ('num_fat_sap', models.CharField(blank=True, max_length=40, verbose_name='Nota fiscal')),
                ('status_nf', models.CharField(blank=True, max_length=60, verbose_name='Status da NF')),
                ('valor_sap', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor SAP')),
                ('valor_vivogo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Vivo go')),
                ('diferenca_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Diferença de valor')),
                ('situacao_valor', models.CharField(blank=True, max_length=180, verbose_name='Situação do valor')),
                ('status_documento', models.CharField(blank=True, max_length=40, verbose_name='Documento')),
                ('status_produto', models.CharField(blank=True, max_length=40, verbose_name='Produto')),
                ('status_valor', models.CharField(blank=True, max_length=40, verbose_name='Valor')),
                ('status_loja', models.CharField(blank=True, max_length=40, verbose_name='Loja')),
                ('status_data', models.CharField(blank=True, max_length=40, verbose_name='Data')),
                ('diferenca_dias', models.IntegerField(blank=True, null=True, verbose_name='Diferença em dias')),
                ('diferenca_explicita', models.TextField(blank=True, verbose_name='O que está diferente')),
                ('pontuacao_indicios', models.IntegerField(blank=True, null=True, verbose_name='Pontuação dos indícios')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Linha completa')),
                ('ativa', models.BooleanField(db_index=True, default=True, verbose_name='Ainda está na auditoria')),
                ('visto_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Visto pela última vez em')),
                ('sumiu_em', models.DateTimeField(blank=True, null=True, verbose_name='Sumiu da auditoria em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('resolvida', models.BooleanField(db_index=True, default=False, verbose_name='Resolvida')),
                ('resolvida_em', models.DateTimeField(blank=True, null=True, verbose_name='Marcada em')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('resolvida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_sap_marcadas', to=settings.AUTH_USER_MODEL, verbose_name='Quem marcou')),
            ],
            options={
                'verbose_name': 'Linha da auditoria SAP',
                'verbose_name_plural': 'Linhas da auditoria SAP',
                'ordering': ['-data_venda', 'pdv', 'id_venda'],
            },
        ),
        migrations.CreateModel(
            name='MarcacaoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolvida', models.BooleanField(verbose_name='Marcou como resolvida')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('quando', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Quando')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes', to='auditoria_sap.linhaauditoria', verbose_name='Linha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcacoes_sap', to=settings.AUTH_USER_MODEL, verbose_name='Quem')),
            ],
            options={
                'verbose_name': 'Marcação da auditoria SAP',
                'verbose_name_plural': 'Marcações da auditoria SAP',
                'ordering': ['-quando'],
            },
        ),
        migrations.CreateModel(
            name='SincronizacaoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quando', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('novas', models.IntegerField(default=0, verbose_name='Linhas novas')),
                ('atualizadas', models.IntegerField(default=0, verbose_name='Linhas que mudaram')),
                ('sumiram', models.IntegerField(default=0, verbose_name='Linhas que saíram')),
                ('total', models.IntegerField(default=0, verbose_name='Linhas na auditoria')),
                ('segundos', models.FloatField(default=0, verbose_name='Tempo (s)')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizacoes_sap', to=settings.AUTH_USER_MODEL, verbose_name='Quem mandou atualizar')),
            ],
            options={
                'verbose_name': 'Sincronização da auditoria SAP',
                'verbose_name_plural': 'Sincronizações da auditoria SAP',
                'ordering': ['-quando'],
            },
        ),
        migrations.AddIndex(
            model_name='linhaauditoria',
            index=models.Index(fields=['ativa', 'resolvida'], name='auditoria_s_ativa_529d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='linhaauditoria',
            index=models.Index(fields=['tipo_erro', 'data_venda'], name='auditoria_s_tipo_er_1b3c15_idx'),
        ),
        migrations.AddIndex(
            model_name='linhaauditoria',
            index=models.Index(fields=['pdv', 'data_venda'], name='auditoria_s_pdv_548639_idx'),
        ),
    ]
