# Generated by Django 5.2.5 on 2026-10-08 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria_sap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaLeituraSap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ler o SAP automaticamente')),
                ('intervalo_horas', models.PositiveSmallIntegerField(default=3, verbose_name='A cada quantas horas')),
                ('ultima_automatica', models.DateTimeField(blank=True, null=True, verbose_name='Última leitura automática')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agenda da leitura do SAP',
                'verbose_name_plural': 'Agenda da leitura do SAP',
            },
        ),
    ]
