# Generated by Django 5.2.5 on 2026-07-13 18:57

import core.storage
import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='green', help_text='Cor do selo no portal (ex.: green, blue, purple, red, amber).', max_length=20, verbose_name='Cor')),
                ('icon', models.CharField(default='fa-file-contract', help_text='Classe do Font Awesome (ex.: fa-file-contract).', max_length=40, verbose_name='Ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_categories_created', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('pdf_file', models.FileField(storage=core.storage.MediaStorage(), upload_to=documentos.models.upload_document_pdf, verbose_name='Arquivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documentos.documentcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Assinado em')),
                ('signature_image', models.TextField(blank=True, help_text='Imagem da assinatura em base64 (PNG).', verbose_name='Assinatura (base64)')),
                ('signature_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da assinatura')),
                ('signature_user_agent', models.TextField(blank=True, verbose_name='User-Agent da assinatura')),
                ('signature_hash', models.CharField(blank=True, help_text='SHA-256 do conteúdo assinado para garantir integridade.', max_length=64, verbose_name='Hash de verificação')),
                ('signed_pdf', models.FileField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to=documentos.models.upload_signed_pdf, verbose_name='PDF assinado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documentos.document', verbose_name='Documento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Signatário')),
            ],
            options={
                'verbose_name': 'Assinatura de Documento',
                'verbose_name_plural': 'Assinaturas de Documentos',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'user')},
            },
        ),
    ]
