# Generated by Django 5.2.5 on 2026-08-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_seed_documentos_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Desmarque para preparar o documento sem que as pessoas o vejam.', verbose_name='Visível para os signatários'),
        ),
    ]
