# Generated by Django 5.2.5 on 2026-08-19 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_document_is_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='assinatura_obrigatoria',
            field=models.BooleanField(default=True, help_text='Desligue para parar de cobrar a assinatura com popup e pendência.', verbose_name='Assinatura obrigatória'),
        ),
        migrations.AddField(
            model_name='document',
            name='obrigatoriedade_alterada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Obrigatoriedade alterada em'),
        ),
        migrations.AddField(
            model_name='document',
            name='obrigatoriedade_alterada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_obrigatoriedade_alterada', to=settings.AUTH_USER_MODEL, verbose_name='Obrigatoriedade alterada por'),
        ),
    ]
