# Generated by Django 5.2.5 on 2026-02-12 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('event_type', models.CharField(choices=[('event', 'Evento'), ('meeting', 'Reunião'), ('call', 'Chamada'), ('task', 'Tarefa'), ('reminder', 'Lembrete'), ('block', 'Bloqueio')], default='event', max_length=20, verbose_name='Tipo')),
                ('color', models.CharField(choices=[('#4f46e5', 'Indigo'), ('#dc2626', 'Vermelho'), ('#16a34a', 'Verde'), ('#ca8a04', 'Amarelo'), ('#2563eb', 'Azul'), ('#9333ea', 'Roxo'), ('#ea580c', 'Laranja'), ('#0d9488', 'Teal'), ('#6b7280', 'Cinza')], default='#4f46e5', max_length=10, verbose_name='Cor')),
                ('start', models.DateTimeField(verbose_name='Início')),
                ('end', models.DateTimeField(verbose_name='Fim')),
                ('all_day', models.BooleanField(default=False, verbose_name='Dia inteiro')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('is_private', models.BooleanField(default=False, help_text='Eventos privados mostram apenas "Ocupado" para outros usuários', verbose_name='Evento privado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('participants', models.ManyToManyField(blank=True, related_name='invited_events', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição / Motivo')),
                ('meeting_type', models.CharField(choices=[('meeting', 'Reunião'), ('call', 'Chamada'), ('appointment', 'Horário')], default='meeting', max_length=20, verbose_name='Tipo')),
                ('proposed_start', models.DateTimeField(verbose_name='Horário proposto - Início')),
                ('proposed_end', models.DateTimeField(verbose_name='Horário proposto - Fim')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Local sugerido')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('response_notes', models.TextField(blank=True, verbose_name='Observação da resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_request', to='agenda.calendarevent', verbose_name='Evento criado')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Solicitação de Reunião',
                'verbose_name_plural': 'Solicitações de Reunião',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['owner', 'start', 'end'], name='agenda_cale_owner_i_a8678a_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start', 'end'], name='agenda_cale_start_fd0614_idx'),
        ),
    ]
