# Generated by Django 5.2.5 on 2026-02-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_add_event_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='link',
            field=models.URLField(blank=True, help_text='Link da reunião, videoconferência, etc.', max_length=500, verbose_name='Link'),
        ),
    ]
