# Generated by Django 4.2.16 on 2026-02-26 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0003_add_link_to_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Reunião')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='transcriptions/audio/%Y/%m/', verbose_name='Arquivo de Áudio')),
                ('raw_transcription', models.TextField(blank=True, verbose_name='Transcrição Bruta')),
                ('formatted_transcription', models.TextField(blank=True, verbose_name='Transcrição Formatada')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo')),
                ('action_items', models.JSONField(blank=True, default=list, verbose_name='Itens de Ação')),
                ('suggested_events', models.JSONField(blank=True, default=list, verbose_name='Eventos Sugeridos')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Duração (segundos)')),
                ('status', models.CharField(choices=[('recording', 'Gravando'), ('processing', 'Processando'), ('completed', 'Concluída'), ('error', 'Erro')], default='recording', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='agenda.calendarevent', verbose_name='Evento')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Transcrição de Reunião',
                'verbose_name_plural': 'Transcrições de Reunião',
                'ordering': ['-created_at'],
            },
        ),
    ]
