# Generated by Django 5.2.5 on 2026-03-09 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_meetingtranscription_tasks_created'),
        ('core', '0023_make_due_date_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_children', to='agenda.calendarevent', verbose_name='Evento pai (recorrência)'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_rule',
            field=models.CharField(choices=[('none', 'Sem recorrência'), ('weekly', 'Semanal')], default='none', max_length=20, verbose_name='Recorrência'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_until',
            field=models.DateField(blank=True, help_text='Data limite da recorrência (opcional)', null=True, verbose_name='Repetir até'),
        ),
        migrations.AlterField(
            model_name='meetingtranscription',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Resumo Executivo'),
        ),
        migrations.AlterField(
            model_name='meetingtranscription',
            name='tasks_created',
            field=models.ManyToManyField(blank=True, related_name='source_transcription', to='core.taskactivity', verbose_name='Tarefas criadas'),
        ),
    ]
