# Generated by Django 4.2.16 on 2026-06-03 04:10

import core.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0009_meetingtranscription_risks'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtranscription',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Usuários que podem visualizar esta transcrição (somente leitura).', related_name='shared_transcriptions', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhada com'),
        ),
        migrations.AlterField(
            model_name='meetingtranscription',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to='transcriptions/audio/%Y/%m/', verbose_name='Arquivo de Áudio'),
        ),
    ]
