# Generated by Django 5.2.5 on 2026-09-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_meetingtranscription_shared_with_and_more'),
        ('core', '0024_alter_checklistitemevidence_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='tarefa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_agenda', to='core.taskactivity', verbose_name='Tarefa vinculada'),
        ),
    ]
