# Generated by Django 5.2.5 on 2026-09-10 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_calendarevent_tarefa'),
        ('core', '0024_alter_checklistitemevidence_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtranscription',
            name='batimento_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último sinal do processamento'),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='etapa',
            field=models.CharField(blank=True, choices=[('montagem', 'Juntando o áudio'), ('transcricao', 'Transcrevendo'), ('analise', 'Analisando com IA'), ('tarefas', 'Gravando na agenda')], default='', max_length=16, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='finalizada_automaticamente',
            field=models.BooleanField(default=False, help_text='O navegador de quem gravava sumiu e o portal fechou a gravação com o que tinha chegado.', verbose_name='Finalizada automaticamente'),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='origem',
            field=models.CharField(blank=True, choices=[('gravador', 'Gravador da agenda'), ('reuniao', 'Sala de reunião'), ('arquivo', 'Arquivo enviado')], default='', max_length=12, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='partes_recebidas',
            field=models.PositiveIntegerField(default=0, verbose_name='Partes recebidas'),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='processando_por',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Processando em'),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='progresso',
            field=models.JSONField(blank=True, default=dict, help_text='Partes juntadas, trechos já transcritos… — o que a retomada não precisa refazer.', verbose_name='Progresso do processamento'),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='proxima_tentativa_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima tentativa em'),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='tentativas',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas de processamento'),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='ultima_parte_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última parte recebida em'),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='upload_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Pasta transcriptions/parts/<upload_id>/ no storage.', max_length=80, verbose_name='Sessão de envio'),
        ),
        migrations.AddConstraint(
            model_name='meetingtranscription',
            constraint=models.UniqueConstraint(condition=models.Q(('upload_id', ''), _negated=True), fields=('upload_id',), name='transcricao_upload_id_unico'),
        ),
    ]
