# Generated by Django 5.2.5 on 2026-09-04 16:06

import core.storage
import curriculos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0016_alter_communication_image_and_more'),
        ('reunioes', '0003_configuracaoreunioes_aplicar_fundo_padrao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCurriculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_sistema_perfil', models.URLField(blank=True, default='https://rede-confianca-sistema-perfil.lpl0df.easypanel.host', help_text='Onde vive a IA do RH. Usado para montar o link da entrevista.', max_length=300, verbose_name='Endereço do sistema de perfil')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grupos', models.ManyToManyField(blank=True, help_text='Quem enxerga e usa o banco de talentos, além do SUPERADMIN.', related_name='+', to='communications.communicationgroup', verbose_name='Grupos com acesso')),
            ],
            options={
                'verbose_name': 'Configuração do banco de talentos',
                'verbose_name_plural': 'Configuração do banco de talentos',
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(storage=core.storage.MediaStorage(), upload_to=curriculos.models.caminho_curriculo, verbose_name='Currículo (PDF)')),
                ('nome_arquivo', models.CharField(blank=True, max_length=255)),
                ('nome', models.CharField(blank=True, db_index=True, max_length=180, verbose_name='Nome')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('experiencia', models.TextField(blank=True, verbose_name='Experiência')),
                ('cargos', models.TextField(blank=True, help_text='Um por linha. É o que a busca por vaga compara primeiro.', verbose_name='Cargos identificados')),
                ('texto', models.TextField(blank=True, verbose_name='Texto do PDF')),
                ('busca', models.TextField(blank=True, editable=False)),
                ('situacao', models.CharField(choices=[('NOVO', 'No banco'), ('ENTREVISTA', 'Em entrevista'), ('CONTRATADO', 'Contratado'), ('DESCARTADO', 'Descartado')], db_index=True, default='NOVO', max_length=12, verbose_name='Situação')),
                ('contratado_em', models.DateField(blank=True, null=True, verbose_name='Contratado em')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação do RH')),
                ('entrevista_token', models.CharField(blank=True, db_index=True, help_text='Token do link público no sistema de perfil.', max_length=80, verbose_name='Token da entrevista')),
                ('entrevista_em', models.DateTimeField(blank=True, null=True, verbose_name='Entrevista em')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contratado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculos_contratados', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
                ('reuniao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculos', to='reunioes.reuniao', verbose_name='Reunião de entrevista')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['situacao', '-enviado_em'], name='curriculos__situaca_80ecaa_idx')],
            },
        ),
    ]
