# Generated by Django 5.2.5 on 2026-09-16 16:36

import apresentacoes.models
import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nova apresentação', max_length=200, verbose_name='Título')),
                ('pedido', models.TextField(blank=True, default='', verbose_name='Pedido para a IA')),
                ('documento', models.JSONField(blank=True, default=dict, verbose_name='Slides')),
                ('revisao', models.PositiveIntegerField(default=0, verbose_name='Revisão')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('GERANDO', 'Gerando com IA'), ('PERGUNTAS', 'Aguardando respostas'), ('PRONTA', 'Pronta'), ('ERRO', 'Erro na geração')], db_index=True, default='RASCUNHO', max_length=10)),
                ('origem', models.CharField(choices=[('MANUAL', 'Pedido livre'), ('MODULO', 'Módulo do portal')], db_index=True, default='MANUAL', max_length=8)),
                ('modulo', models.CharField(blank=True, db_index=True, default='', max_length=60, verbose_name='Módulo apresentado')),
                ('opcoes', models.JSONField(blank=True, default=dict, verbose_name='Opções do pedido')),
                ('erro', models.TextField(blank=True, default='')),
                ('canva_design_id', models.CharField(blank=True, default='', max_length=80)),
                ('canva_edit_url', models.URLField(blank=True, default='', max_length=1000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
            ],
            options={
                'verbose_name': 'Apresentação',
                'verbose_name_plural': 'Apresentações',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConexaoCanva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_cifrado', models.TextField(blank=True, default='')),
                ('refresh_token_cifrado', models.TextField(blank=True, default='')),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('escopos', models.CharField(blank=True, default='', max_length=300)),
                ('estado', models.CharField(blank=True, default='', max_length=80)),
                ('verificador_cifrado', models.TextField(blank=True, default='')),
                ('volta', models.CharField(blank=True, default='', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conexao_canva', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão com o Canva',
                'verbose_name_plural': 'Conexões com o Canva',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoApresentacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_texto', models.CharField(default='gpt-4.1', max_length=60, verbose_name='Modelo de texto e visão')),
                ('modelo_imagem', models.CharField(default='gpt-image-1', max_length=60, verbose_name='Modelo de imagem')),
                ('modelo_video', models.CharField(default='sora-2', max_length=60, verbose_name='Modelo de vídeo')),
                ('modelo_voz', models.CharField(default='gpt-4o-mini-tts', max_length=60, verbose_name='Modelo de voz')),
                ('voz', models.CharField(default='nova', max_length=30, verbose_name='Voz da narração')),
                ('canva_client_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Canva — Client ID')),
                ('canva_client_secret_cifrado', models.TextField(blank=True, default='', verbose_name='Canva — Client secret (cifrado)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('liberados', models.ManyToManyField(blank=True, help_text='Além do SUPERADMIN, que sempre pode.', related_name='apresentacoes_liberadas', to=settings.AUTH_USER_MODEL, verbose_name='Quem pode usar')),
            ],
            options={
                'verbose_name': 'Configuração das apresentações',
                'verbose_name_plural': 'Configuração das apresentações',
            },
        ),
        migrations.CreateModel(
            name='TarefaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GERAR', 'Gerar apresentação'), ('EDITAR', 'Editar apresentação com IA'), ('REFAZER_SLIDE', 'Refazer slide'), ('NOVO_SLIDE', 'Novo slide'), ('TEXTO', 'Reescrever texto'), ('IMAGEM', 'Gerar imagem'), ('VIDEO', 'Gerar vídeo'), ('NARRACAO', 'Gerar narração'), ('ANALISAR_TEMPLATE', 'Analisar template'), ('CANVA', 'Enviar ao Canva')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Na fila'), ('RODANDO', 'Rodando'), ('PERGUNTAS', 'Aguardando respostas'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=10)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('progresso', models.JSONField(blank=True, default=dict)),
                ('perguntas', models.JSONField(blank=True, default=list)),
                ('respostas', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('apresentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='apresentacoes.apresentacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_tarefas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa da IA',
                'verbose_name_plural': 'Tarefas da IA',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('USUARIO', 'Você'), ('IA', 'IA')], max_length=8)),
                ('texto', models.TextField(blank=True, default='')),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='apresentacoes.apresentacao')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='apresentacoes.tarefaia')),
            ],
            options={
                'verbose_name': 'Mensagem com a IA',
                'verbose_name_plural': 'Mensagens com a IA',
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateApresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('estilo', models.TextField(blank=True, default='', help_text='Como é a identidade: tom, cores, tipo de imagem. A IA segue isso ao montar os slides.', verbose_name='Estilo para a IA')),
                ('documento', models.JSONField(blank=True, default=dict, verbose_name='Tema e layouts')),
                ('origem', models.CharField(choices=[('SISTEMA', 'Padrão do portal'), ('IMAGENS', 'Importado de imagens'), ('PPTX', 'Importado de PowerPoint'), ('PDF', 'Importado de PDF')], default='IMAGENS', max_length=10)),
                ('status', models.CharField(choices=[('PRONTO', 'Pronto'), ('ANALISANDO', 'Analisando'), ('ERRO', 'Erro na análise')], default='PRONTO', max_length=12)),
                ('erro', models.TextField(blank=True, default='')),
                ('padrao_da_rede', models.BooleanField(default=False, help_text='Aparece para todo mundo que usa o módulo. Só o SUPERADMIN marca.', verbose_name='Disponível para todos')),
                ('principal', models.BooleanField(default=False, verbose_name='Template principal (vem marcado)')),
                ('ativo', models.BooleanField(default=True)),
                ('revisao', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apresentacoes_templates', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de apresentação',
                'verbose_name_plural': 'Templates de apresentação',
                'ordering': ['-principal', '-padrao_da_rede', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='tarefaia',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='apresentacoes.templateapresentacao'),
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio'), ('DOCUMENTO', 'Documento')], db_index=True, default='IMAGEM', max_length=10)),
                ('origem', models.CharField(choices=[('UPLOAD', 'Enviada'), ('PRINT', 'Print para a IA'), ('CAPTURA', 'Captura de tela do portal'), ('IA_IMAGEM', 'Imagem gerada pela IA'), ('IA_VIDEO', 'Vídeo gerado pela IA'), ('IA_VOZ', 'Narração gerada pela IA'), ('TEMPLATE', 'Do template'), ('EXPORTACAO', 'Exportação')], default='UPLOAD', max_length=10)),
                ('arquivo', models.FileField(max_length=300, storage=core.storage.MediaStorage(), upload_to=apresentacoes.models.upload_midia)),
                ('nome', models.CharField(blank=True, default='', max_length=200)),
                ('mime', models.CharField(blank=True, default='', max_length=100)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('largura', models.PositiveIntegerField(blank=True, null=True)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('duracao', models.FloatField(blank=True, null=True, verbose_name='Duração (s)')),
                ('prompt', models.TextField(blank=True, default='', verbose_name='Pedido à IA')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('apresentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='apresentacoes.apresentacao')),
                ('dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apresentacoes_midias', to=settings.AUTH_USER_MODEL, verbose_name='Enviada por')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='apresentacoes.templateapresentacao')),
            ],
            options={
                'verbose_name': 'Mídia de apresentação',
                'verbose_name_plural': 'Mídias de apresentação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apresentacoes', to='apresentacoes.templateapresentacao', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='VersaoApresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.JSONField(default=dict)),
                ('titulo', models.CharField(blank=True, default='', max_length=200)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='apresentacoes.apresentacao')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versão de apresentação',
                'verbose_name_plural': 'Versões de apresentação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
