# Generated by Django 5.2.5 on 2026-05-13 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações da atribuição')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_assignments_to_receive', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado (quem receberá o feedback)')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_assignments_to_give', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador (quem dará o feedback)')),
            ],
            options={
                'verbose_name': 'Atribuição de Feedback',
                'verbose_name_plural': 'Atribuições de Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_area', models.CharField(blank=True, max_length=200, verbose_name='Setor / Área')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('nome_colaborador', models.CharField(blank=True, max_length=200, verbose_name='Nome do Colaborador(a)')),
                ('gestor_imediato', models.CharField(blank=True, max_length=200, verbose_name='Gestor Imediato')),
                ('gestor_mediato', models.CharField(blank=True, max_length=200, verbose_name='Gestor Mediato')),
                ('pontos_fortes', models.TextField(blank=True, verbose_name='Pontos Fortes')),
                ('oportunidades_melhoria', models.TextField(blank=True, verbose_name='Oportunidades de Melhoria')),
                ('acoes_propostas', models.TextField(blank=True, verbose_name='Ações Propostas')),
                ('nota_comunicacao', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Como você avalia sua comunicação (0 insatisfeito, 10 muito satisfeito).', null=True, verbose_name='Comunicação (0-10)')),
                ('nota_trabalho_equipe', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Trabalho em equipe (0-10)')),
                ('nota_organizacao', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Organização (0-10)')),
                ('comunicacao_clara_texto', models.TextField(blank=True, verbose_name='Você sente que se comunica de forma clara e eficaz com sua equipe e superiores?')),
                ('nota_ferramentas_recursos', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Possui as ferramentas e recursos necessários (0-10)')),
                ('nota_iniciativa', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Tomou iniciativa / foi além (0-10)')),
                ('nota_mudancas', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Lida com mudanças e imprevistos (0-10)')),
                ('nota_conflitos', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Lida com conflitos / desentendimentos (0-10)')),
                ('cumpriu_metas_texto', models.TextField(blank=True, verbose_name='Você acredita que cumpriu as metas estabelecidas para este período? Por quê?')),
                ('suporte_orientacao_texto', models.TextField(blank=True, verbose_name='Como avalia o suporte e a orientação que recebe de seus superiores?')),
                ('evolution_notes', models.TextField(blank=True, help_text='Considerações sobre a evolução do colaborador desde o último feedback.', verbose_name='Evolução do colaborador')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Resumo gerado por IA')),
                ('ai_summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador avaliado')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='feedback.feedbackassignment', verbose_name='Atribuição de origem')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
