# Generated by Django 5.2.5 on 2026-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackassignment',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='feedbackassignment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20),
        ),
    ]
