# Generated by Django 5.2.5 on 2026-05-14 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedbackassignment_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackassignment',
            name='monthly',
            field=models.BooleanField(default=False, help_text='Se marcado, o avaliador será lembrado todo mês (10 dias antes do fim) para aplicar este feedback.', verbose_name='Fazer todo mês'),
        ),
        migrations.CreateModel(
            name='FeedbackReminderDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reminder_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lembrete dispensado',
                'verbose_name_plural': 'Lembretes dispensados',
                'unique_together': {('user', 'key')},
            },
        ),
    ]
