# Generated by Django 4.2.16 on 2026-06-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedbackassignment_monthly_feedbackreminderdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='audio_context',
            field=models.CharField(blank=True, choices=[('CONVERSA', 'Conversa entre avaliador e avaliado'), ('AVALIADOR', 'Somente o avaliador'), ('AVALIADO', 'Somente o avaliado')], help_text='Quem aparece no áudio gravado.', max_length=20, verbose_name='Contexto do áudio'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='feedback/audio/%Y/%m/', verbose_name='Áudio do feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='audio_transcribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='audio_transcription',
            field=models.TextField(blank=True, verbose_name='Transcrição do áudio'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='audio_transcription_error',
            field=models.TextField(blank=True),
        ),
    ]
