# Generated by Django 5.2.5 on 2026-06-16 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_audio_context_feedback_audio_file_and_more'),
        ('users', '0018_commission_version_unique_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_key', models.CharField(db_index=True, default='clima_organizacional_2026', max_length=80)),
                ('answers', models.JSONField(default=dict, verbose_name='Respostas')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_survey_responses', to='users.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Resposta Anônima da Pesquisa de Clima',
                'verbose_name_plural': 'Respostas Anônimas da Pesquisa de Clima',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClimateSurveyParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_key', models.CharField(db_index=True, default='clima_organizacional_2026', max_length=80)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluída')], default='IN_PROGRESS', max_length=20)),
                ('last_step', models.CharField(blank=True, max_length=120, verbose_name='Última etapa')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_survey_participations', to='users.sector', verbose_name='Setor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_survey_participations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Participação na Pesquisa de Clima',
                'verbose_name_plural': 'Participações na Pesquisa de Clima',
                'ordering': ['status', 'user__first_name', 'user__last_name'],
                'unique_together': {('survey_key', 'user')},
            },
        ),
    ]
