# Generated by Django 5.2.5 on 2026-06-22 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_climatesurveyresponse_climatesurveyparticipation'),
        ('users', '0019_user_pcn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_key', models.CharField(db_index=True, default='desligamento_2026', max_length=80)),
                ('answers', models.JSONField(default=dict, verbose_name='Respostas')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resposta da Entrevista de Desligamento',
                'verbose_name_plural': 'Respostas da Entrevista de Desligamento',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyManagerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_manager_permission', to=settings.AUTH_USER_MODEL, verbose_name='Usuário liberado')),
            ],
            options={
                'verbose_name': 'Acesso à gestão de pesquisas',
                'verbose_name_plural': 'Acessos à gestão de pesquisas',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ExitInterviewParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_key', models.CharField(db_index=True, default='desligamento_2026', max_length=80)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluída')], default='IN_PROGRESS', max_length=20)),
                ('last_step', models.CharField(blank=True, max_length=120, verbose_name='Última etapa')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interview_participations', to='users.sector', verbose_name='Setor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview_participations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Participação na Entrevista de Desligamento',
                'verbose_name_plural': 'Participações na Entrevista de Desligamento',
                'ordering': ['status', 'user__first_name', 'user__last_name'],
                'unique_together': {('survey_key', 'user')},
            },
        ),
    ]
