# Generated by Django 5.2.5 on 2026-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_exitinterviewresponse_surveymanagerpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_menu_visible', models.BooleanField(default=True, help_text='Quando desligado, apenas superadmins e gestores das pesquisas veem o item no menu.', verbose_name='Mostrar "Pesquisa de Clima" no menu para usuários comuns')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração das Pesquisas',
                'verbose_name_plural': 'Configurações das Pesquisas',
            },
        ),
    ]
