# Generated by Django 5.2.5 on 2026-06-22 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_surveysettings'),
        ('users', '0019_user_pcn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatesurveyresponse',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Resposta da Pesquisa de Clima', 'verbose_name_plural': 'Respostas da Pesquisa de Clima'},
        ),
        migrations.AddField(
            model_name='climatesurveyresponse',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de resposta (s)'),
        ),
        migrations.AddField(
            model_name='climatesurveyresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_survey_responses_made', to=settings.AUTH_USER_MODEL, verbose_name='Respondente'),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de resposta (s)'),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interview_responses', to='users.sector', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interview_responses_made', to=settings.AUTH_USER_MODEL, verbose_name='Respondente'),
        ),
    ]
