# Generated by Django 5.2.5 on 2026-07-02 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_survey_managers_to_exit_access(apps, schema_editor):
    SurveyManagerPermission = apps.get_model('feedback', 'SurveyManagerPermission')
    ExitInterviewAccessPermission = apps.get_model('feedback', 'ExitInterviewAccessPermission')
    for permission in SurveyManagerPermission.objects.all():
        ExitInterviewAccessPermission.objects.get_or_create(
            user_id=permission.user_id,
            defaults={'granted_by_id': permission.granted_by_id},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_exit_interview_conducted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveymanagerpermission',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Acesso à gestão da Pesquisa de Clima', 'verbose_name_plural': 'Acessos à gestão da Pesquisa de Clima'},
        ),
        migrations.CreateModel(
            name='ExitInterviewAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interview_permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview_access_permission', to=settings.AUTH_USER_MODEL, verbose_name='Usuário liberado')),
            ],
            options={
                'verbose_name': 'Acesso à Entrevista de Desligamento',
                'verbose_name_plural': 'Acessos à Entrevista de Desligamento',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.RunPython(copy_existing_survey_managers_to_exit_access, migrations.RunPython.noop),
    ]
