# Generated by Django 5.2.5 on 2026-07-10 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_surveymanagerpermission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenClientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Texto exibido ao avaliador no formulário de feedback deste colaborador.', verbose_name='Relatório')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_client_reports_written', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_client_report', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Relatório cliente oculto',
                'verbose_name_plural': 'Relatórios cliente oculto',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ClimateSurveyExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_key', models.CharField(db_index=True, default='clima_organizacional_2026', max_length=80)),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_exemptions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Isentado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_survey_exemptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário isento')),
            ],
            options={
                'verbose_name': 'Isenção da Pesquisa de Clima',
                'verbose_name_plural': 'Isenções da Pesquisa de Clima',
                'ordering': ['user__first_name', 'user__last_name'],
                'unique_together': {('survey_key', 'user')},
            },
        ),
    ]
