# Generated by Django 5.2.5 on 2026-08-24 19:28

import core.storage
import core.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_hiddenclientreport_climatesurveyexemption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterviewRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(storage=core.storage.MediaStorage(), upload_to=core.utils.upload_exit_interview_video, verbose_name='Vídeo da entrevista')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Arquivo enviado')),
                ('status', models.CharField(choices=[('PENDING', 'Na fila'), ('PROCESSING', 'Analisando'), ('DONE', 'Pronto'), ('ERROR', 'Falhou')], db_index=True, default='PENDING', max_length=12)),
                ('error', models.TextField(blank=True, verbose_name='Erro')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('transcription', models.TextField(blank=True, verbose_name='Transcrição')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo da IA')),
                ('highlights', models.JSONField(blank=True, default=dict, verbose_name='Pontos destacados')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Nota da IA (1 a 5)')),
                ('score_reason', models.TextField(blank=True, verbose_name='Justificativa da nota')),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('public_enabled', models.BooleanField(default=True, help_text='Desligue para invalidar o endereço já compartilhado.', verbose_name='Link público ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Analisado em')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='feedback.exitinterviewresponse', verbose_name='Entrevista')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interview_recordings', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Gravação da Entrevista de Desligamento',
                'verbose_name_plural': 'Gravações da Entrevista de Desligamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
