# Generated by Django 5.2.5 on 2026-09-25 14:58

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_exitinterviewrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to='feedback/audio/%Y/%m/', verbose_name='Áudio do feedback'),
        ),
    ]
