# Generated by Django 5.2.5 on 2026-09-22 14:37

import django.core.validators
import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('enunciado', models.TextField(max_length=500, verbose_name='Pergunta')),
                ('tempo_limite', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)], verbose_name='Tempo para responder (segundos)')),
                ('explicacao', models.TextField(blank=True, help_text='Aparece no resultado de cada participante, junto da resposta certa.', max_length=500, verbose_name='Explicação (opcional)')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaproveitamentos', to='quiz.pergunta', verbose_name='Reaproveitada de')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('texto', models.CharField(max_length=200, verbose_name='Alternativa')),
                ('correta', models.BooleanField(default=False, verbose_name='Correta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='quiz.pergunta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='Categoria ou tema')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado')], default='RASCUNHO', max_length=10, verbose_name='Situação')),
                ('tempo_padrao', models.PositiveSmallIntegerField(default=20, help_text='Sugestão para cada pergunta nova; cada uma pode ter o seu.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)], verbose_name='Tempo padrão por pergunta (segundos)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('duplicado_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copias', to='quiz.quiz', verbose_name='Cópia de')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Opcional — sem nome, a sala usa o nome do quiz.', max_length=150, verbose_name='Nome da sala')),
                ('codigo', models.CharField(default=quiz.models.gerar_codigo, max_length=8, unique=True, verbose_name='Código')),
                ('agendada_para', models.DateTimeField(verbose_name='Data e horário')),
                ('fase', models.CharField(choices=[('AGENDADA', 'Aguardando início'), ('PERGUNTA', 'Pergunta no ar'), ('RESULTADO', 'Resultado da pergunta'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=10)),
                ('pergunta_atual', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pergunta no ar (posição)')),
                ('pergunta_inicio', models.DateTimeField(blank=True, null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas', to='quiz.quiz', verbose_name='Quiz')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_salas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['-agendada_para'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('MANUAL', 'Escolhido na lista'), ('LOJA', 'Pela loja'), ('SETOR', 'Pelo setor'), ('CARGO', 'Pelo cargo'), ('GRUPO', 'Pelo grupo'), ('COORDENACAO', 'Pela coordenação')], default='MANUAL', max_length=12)),
                ('rotulo_origem', models.CharField(blank=True, max_length=120, verbose_name='De onde veio')),
                ('entrou_em', models.DateTimeField(blank=True, null=True, verbose_name='Entrou na sala')),
                ('visto_em', models.DateTimeField(blank=True, null=True)),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('acertos', models.PositiveSmallIntegerField(default=0)),
                ('erros', models.PositiveSmallIntegerField(default=0)),
                ('tempo_acertos_ms', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_participacoes', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='quiz.sala')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'unique_together': {('sala', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista_em', models.DateTimeField()),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('tempo_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('correta', models.BooleanField(default=False)),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('alternativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='quiz.alternativa')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='quiz.participante')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='quiz.pergunta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'unique_together': {('participante', 'pergunta')},
            },
        ),
    ]
