# Generated by Django 5.2.5 on 2026-09-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='origem',
            field=models.CharField(choices=[('MANUAL', 'Escolhido na lista'), ('LOJA', 'Pela loja'), ('SETOR', 'Pelo setor'), ('CARGO', 'Pelo cargo'), ('GRUPO', 'Pelo grupo'), ('COORDENACAO', 'Pela coordenação'), ('CODIGO', 'Entrou pelo código')], default='MANUAL', max_length=12),
        ),
    ]
