# Generated by Django 5.2.5 on 2026-08-12 22:33

import cartoes.models
import core.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0012_alter_ticketcomment_comment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, help_text='Nome amigável para identificar o cartão (opcional).', max_length=60, verbose_name='Apelido')),
                ('first4', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Informe exatamente 4 dígitos.')], verbose_name='4 primeiros dígitos')),
                ('last4', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Informe exatamente 4 dígitos.')], verbose_name='4 últimos dígitos')),
                ('validade_mes', models.PositiveSmallIntegerField(verbose_name='Mês de validade')),
                ('validade_ano', models.PositiveSmallIntegerField(verbose_name='Ano de validade')),
                ('bandeira', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('ELO', 'Elo'), ('AMEX', 'American Express')], max_length=15, verbose_name='Bandeira')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'ordering': ['apelido', 'last4'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('estabelecimento', models.CharField(blank=True, max_length=200, verbose_name='Estabelecimento')),
                ('data_gasto', models.DateField(verbose_name='Data do gasto')),
                ('categoria_gasto', models.CharField(blank=True, max_length=120, verbose_name='Categoria do gasto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to=cartoes.models.upload_cartao_gasto_foto, verbose_name='Foto do comprovante')),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('FOTO', 'Foto')], default='MANUAL', max_length=10, verbose_name='Origem')),
                ('ia_dados', models.JSONField(blank=True, default=dict, verbose_name='Dados extraídos pela IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='cartoes.cartao', verbose_name='Cartão')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_cartao', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartao_gastos', to='tickets.ticket', verbose_name='Chamado gerado')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-data_gasto', '-created_at'],
            },
        ),
    ]
