# Generated by Django 5.2.5 on 2026-09-29 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoCartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, help_text='Por que esta pessoa cuida dos cartões (opcional).', max_length=200, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('liberado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_cartoes_liberados', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acesso_cartoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acesso aos cartões',
                'verbose_name_plural': 'Acessos aos cartões',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
