# Generated by Django 5.2.5 on 2025-09-02 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_numero', models.CharField(max_length=20, unique=True, verbose_name='N° Patrimônio')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('localizado', models.CharField(max_length=200, verbose_name='Localizado')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('pdv', models.CharField(max_length=50, verbose_name='PDV')),
                ('estado_fisico', models.CharField(choices=[('excelente', 'Excelente'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('pessimo', 'Péssimo')], default='bom', max_length=20, verbose_name='Estado Físico')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['patrimonio_numero'],
            },
        ),
    ]
