# Generated by Django 5.2.5 on 2025-09-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Foto do Asset'),
        ),
    ]
