# Generated by Django 5.2.5 on 2025-09-07 06:35

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_asset_photo, verbose_name='Foto do Asset'),
        ),
    ]
