# Generated by Django 5.2.5 on 2026-02-02 18:23

import assets.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_photo'),
        ('users', '0011_add_hr_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor')),
                ('icon', models.CharField(default='fas fa-box', max_length=50, verbose_name='Ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria de Inventário',
                'verbose_name_plural': 'Categorias de Inventário',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['patrimonio_numero'], 'verbose_name': 'Ativo (Legado)', 'verbose_name_plural': 'Ativos (Legado)'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Foto do Asset'),
        ),
        migrations.CreateModel(
            name='InventoryManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_products', models.BooleanField(default=True, verbose_name='Pode gerenciar produtos')),
                ('can_manage_items', models.BooleanField(default=True, verbose_name='Pode gerenciar itens')),
                ('can_register_entries', models.BooleanField(default=True, verbose_name='Pode registrar entradas')),
                ('can_register_exits', models.BooleanField(default=True, verbose_name='Pode registrar saídas')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='Pode visualizar relatórios')),
                ('can_manage_managers', models.BooleanField(default=False, verbose_name='Pode gerenciar outros gestores')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_managers_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_manager_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Gestor de Inventário',
                'verbose_name_plural': 'Gestores de Inventário',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('sku', models.CharField(help_text='Código único do produto', max_length=50, unique=True, verbose_name='Código SKU')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('size', models.CharField(blank=True, choices=[('', 'Não aplicável'), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XGG', 'XGG'), ('UNICO', 'Tamanho Único'), ('PERSONALIZADO', 'Personalizado')], max_length=20, verbose_name='Tamanho')),
                ('size_custom', models.CharField(blank=True, help_text='Especifique o tamanho se for personalizado', max_length=50, verbose_name='Tamanho Personalizado')),
                ('unit_of_measure', models.CharField(default='UN', help_text='Ex: UN, KG, L, M, CX', max_length=20, verbose_name='Unidade de Medida')),
                ('min_stock', models.PositiveIntegerField(default=0, help_text='Quantidade mínima para alerta', verbose_name='Estoque Mínimo')),
                ('max_stock', models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade máxima recomendada (0 = sem limite)', verbose_name='Estoque Máximo')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo Unitário')),
                ('location', models.CharField(blank=True, help_text='Ex: Prateleira A-1, Corredor 3', max_length=100, verbose_name='Localização no Almoxarifado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='assets.inventorycategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Código único do item', max_length=50, unique=True, verbose_name='Número de Inventário')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Número do Lote')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('in_use', 'Em Uso'), ('maintenance', 'Em Manutenção'), ('damaged', 'Danificado'), ('disposed', 'Descartado')], default='available', max_length=20, verbose_name='Status')),
                ('condition', models.CharField(choices=[('new', 'Novo'), ('excellent', 'Excelente'), ('good', 'Bom'), ('fair', 'Regular'), ('poor', 'Ruim')], default='new', max_length=20, verbose_name='Condição')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data de Compra')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de Compra')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Validade da Garantia')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localização Atual')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=assets.models.upload_inventory_item_media, verbose_name='Foto do Item')),
                ('assigned_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atribuição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inventory_items', to='users.sector', verbose_name='Setor Atual')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atual')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='assets.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], default='image', max_length=10, verbose_name='Tipo de Mídia')),
                ('file', models.FileField(upload_to=assets.models.upload_product_media, verbose_name='Arquivo')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='assets.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Mídia do Produto',
                'verbose_name_plural': 'Mídias do Produto',
                'ordering': ['order', '-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída'), ('transfer', 'Transferência'), ('adjustment', 'Ajuste'), ('return', 'Devolução')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('reason', models.CharField(choices=[('purchase', 'Compra'), ('donation', 'Doação'), ('return_from_user', 'Devolução de Usuário'), ('return_from_maintenance', 'Retorno de Manutenção'), ('inventory_adjustment', 'Ajuste de Inventário'), ('initial_stock', 'Estoque Inicial'), ('assigned_to_user', 'Atribuído a Usuário'), ('assigned_to_sector', 'Atribuído a Setor'), ('maintenance', 'Enviado para Manutenção'), ('disposed', 'Descarte'), ('lost', 'Perda/Extravio'), ('damaged', 'Dano'), ('other', 'Outro')], max_length=30, verbose_name='Motivo')),
                ('from_location', models.CharField(blank=True, max_length=100, verbose_name='De (Local)')),
                ('to_location', models.CharField(blank=True, max_length=100, verbose_name='Para (Local)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('document_reference', models.CharField(blank=True, help_text='Ex: Número da NF, requisição, etc.', max_length=100, verbose_name='Referência do Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('from_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_from', to='users.sector', verbose_name='De (Setor)')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_from', to=settings.AUTH_USER_MODEL, verbose_name='De (Usuário)')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='assets.inventoryitem', verbose_name='Item de Inventário')),
                ('to_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_to', to='users.sector', verbose_name='Para (Setor)')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_to', to=settings.AUTH_USER_MODEL, verbose_name='Para (Usuário)')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
