# Generated by Django 5.2.5 on 2026-02-11 16:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_inventorycategory_alter_asset_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymanager',
            name='can_approve_requests',
            field=models.BooleanField(default=True, verbose_name='Pode aprovar/reprovar solicitações'),
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('reason', models.TextField(help_text='Descreva o motivo pelo qual precisa deste item', verbose_name='Motivo da Solicitação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Revisão')),
                ('review_notes', models.TextField(blank=True, verbose_name='Observações da Revisão')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Entrega')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Observações da Entrega')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests_delivered', to=settings.AUTH_USER_MODEL, verbose_name='Entregue por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='assets.product', verbose_name='Produto')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Solicitação de Item',
                'verbose_name_plural': 'Solicitações de Itens',
                'ordering': ['-requested_at'],
            },
        ),
    ]
