# Generated by Django 5.2.5 on 2026-02-11 17:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_inventorymanager_can_approve_requests_itemrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='reason',
            field=models.TextField(help_text='Descreva o motivo pelo qual precisa destes itens', verbose_name='Motivo da Solicitação'),
        ),
        migrations.CreateModel(
            name='ItemRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='assets.product', verbose_name='Produto')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.itemrequest', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Item da Solicitação',
                'verbose_name_plural': 'Itens da Solicitação',
                'unique_together': {('request', 'product')},
            },
        ),
    ]
