# Generated by Django 5.2.5 on 2026-02-12 13:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_itemrequest_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='counterproposal_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Contraproposta'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='counterproposal_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests_counterproposed', to=settings.AUTH_USER_MODEL, verbose_name='Contraproposta por'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='counterproposal_notes',
            field=models.TextField(blank=True, help_text='Explicação do motivo da contraproposta', verbose_name='Observações da Contraproposta'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='counterproposal_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta à Contraproposta'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='counterproposal_response_notes',
            field=models.TextField(blank=True, verbose_name='Observações da Resposta à Contraproposta'),
        ),
        migrations.AddField(
            model_name='itemrequestitem',
            name='proposed_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade sugerida pelo gestor na contraproposta (0 = item removido)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Proposta'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('counterproposal', 'Contraproposta'), ('accepted', 'Aceita pelo Solicitante'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itemrequestitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade Solicitada'),
        ),
    ]
