# Generated by Django 5.2.5 on 2026-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_itemrequest_counterproposal_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='imei_serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IMEI/Serial'),
        ),
    ]
