# Generated by Django 5.2.5 on 2026-06-02 15:21

import assets.models
import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_add_imei_serial_to_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(default='fas fa-box-open', max_length=50, verbose_name='Ícone Font Awesome')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Produto (Pedidos)',
                'verbose_name_plural': 'Categorias de Produtos (Pedidos)',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to=assets.models.upload_inventory_item_media, verbose_name='Foto do Item'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(storage=core.storage.MediaStorage(), upload_to=assets.models.upload_product_media, verbose_name='Arquivo'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=15, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Justificativa / Observações')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Avaliado em')),
                ('review_notes', models.TextField(blank=True, verbose_name='Observação da avaliação')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Observação da entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_delivered', to=settings.AUTH_USER_MODEL, verbose_name='Entregue por')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_requested', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to=assets.models.upload_order_product_image, verbose_name='Imagem')),
                ('unit', models.CharField(blank=True, default='Unidade', max_length=30, verbose_name='Unidade de Medida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='assets.orderproductcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto de Pedido',
                'verbose_name_plural': 'Produtos de Pedido',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='assets.orderproduct', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['id'],
            },
        ),
    ]
