# Generated by Django 5.2.5 on 2026-09-03 03:06

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_orderproductcategory_alter_inventoryitem_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to='assets/', verbose_name='Foto do Asset'),
        ),
    ]
