# Generated by Django 5.2.5 on 2026-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_asset_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='pdv',
            field=models.CharField(max_length=100, verbose_name='PDV'),
        ),
    ]
