# Generated by Django 5.2.5 on 2026-10-09 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_categoria_localizado_sim_nao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_numero', models.CharField(db_index=True, max_length=20, verbose_name='N° Patrimônio')),
                ('acao', models.CharField(choices=[('criado', 'Cadastrado'), ('editado', 'Editado'), ('excluido', 'Excluído')], max_length=10, verbose_name='Ação')),
                ('origem', models.CharField(choices=[('tela', 'Tela do ativo'), ('massa', 'Edição em massa'), ('planilha', 'Importação de planilha'), ('admin', 'Admin do Django')], default='tela', max_length=10, verbose_name='Origem')),
                ('usuario_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do usuário')),
                ('quando', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e hora')),
                ('mudancas', models.JSONField(blank=True, default=list, help_text='[{"campo", "rotulo", "antes", "depois"}]', verbose_name='Mudanças')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='assets.asset', verbose_name='Ativo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico do ativo (legado)',
                'verbose_name_plural': 'Histórico dos ativos (legado)',
                'ordering': ['-quando', '-id'],
            },
        ),
    ]
