# Generated by Django 5.2.7 on 2025-11-24 17:31

import django.core.validators
import django.db.models.deletion
import knowledge_trails.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_add_uniform_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Lição')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('lesson_type', models.CharField(choices=[('text', 'Texto'), ('video', 'Vídeo'), ('quiz', 'Quiz'), ('interactive', 'Interativo')], default='text', max_length=20, verbose_name='Tipo de Lição')),
                ('content', models.TextField(blank=True, help_text='Conteúdo em texto (suporta markdown)', verbose_name='Conteúdo')),
                ('video_url', models.URLField(blank=True, help_text='URL do YouTube, Vimeo, etc.', verbose_name='URL do Vídeo')),
                ('media_file', models.FileField(blank=True, help_text='PDF, imagens, etc.', null=True, upload_to=knowledge_trails.models.upload_lesson_media, verbose_name='Arquivo de Mídia')),
                ('points', models.PositiveIntegerField(default=10, help_text='Pontos ganhos ao concluir esta lição', verbose_name='Pontos')),
                ('duration_minutes', models.PositiveIntegerField(default=5, help_text='Tempo estimado para completar', verbose_name='Duração (minutos)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Lição',
                'verbose_name_plural': 'Lições',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Trilha')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=knowledge_trails.models.upload_trail_icon, verbose_name='Ícone da Trilha')),
                ('color', models.CharField(default='#3B82F6', help_text='Código hexadecimal (ex: #3B82F6)', max_length=7, verbose_name='Cor Principal')),
                ('difficulty', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado'), ('expert', 'Especialista')], default='beginner', max_length=20, verbose_name='Dificuldade')),
                ('estimated_hours', models.PositiveIntegerField(default=1, help_text='Tempo estimado para conclusão', verbose_name='Horas Estimadas')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Pontos totais da trilha (calculado automaticamente)', verbose_name='Total de Pontos')),
                ('enable_certificate', models.BooleanField(default=True, help_text='Gerar certificado ao concluir a trilha', verbose_name='Habilitar Certificado')),
                ('certificate_logo', models.ImageField(blank=True, help_text='Logo que aparecerá no certificado', null=True, upload_to=knowledge_trails.models.upload_certificate_logo, verbose_name='Logo para Certificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trails', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_trails', to='users.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Trilha de Conhecimento',
                'verbose_name_plural': 'Trilhas de Conhecimento',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pergunta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='knowledge_trails.lesson', verbose_name='Lição')),
            ],
            options={
                'verbose_name': 'Pergunta de Quiz',
                'verbose_name_plural': 'Perguntas de Quiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texto da Opção')),
                ('is_correct', models.BooleanField(default=False, verbose_name='É a Resposta Correta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='knowledge_trails.quizquestion', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Opção de Resposta',
                'verbose_name_plural': 'Opções de Resposta',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrailModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Módulo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('map_x', models.IntegerField(default=0, help_text='Coordenada horizontal no minimapa (0-100)', verbose_name='Posição X no Mapa')),
                ('map_y', models.IntegerField(default=0, help_text='Coordenada vertical no minimapa (0-100)', verbose_name='Posição Y no Mapa')),
                ('icon_emoji', models.CharField(default='📚', help_text='Emoji que representa o módulo', max_length=10, verbose_name='Emoji do Módulo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='knowledge_trails.knowledgetrail', verbose_name='Trilha')),
            ],
            options={
                'verbose_name': 'Módulo da Trilha',
                'verbose_name_plural': 'Módulos da Trilha',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='knowledge_trails.trailmodule', verbose_name='Módulo'),
        ),
        migrations.CreateModel(
            name='TrailProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Não Iniciado'), ('in_progress', 'Em Progresso'), ('completed', 'Concluído')], default='not_started', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('total_points_earned', models.PositiveIntegerField(default=0, verbose_name='Pontos Conquistados')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='knowledge_trails.knowledgetrail', verbose_name='Trilha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Progresso na Trilha',
                'verbose_name_plural': 'Progressos nas Trilhas',
                'unique_together': {('trail', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(max_length=50, unique=True, verbose_name='Código do Certificado')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Emitido em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='knowledge_trails.knowledgetrail', verbose_name='Trilha')),
                ('trail_progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='knowledge_trails.trailprogress', verbose_name='Progresso da Trilha')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('quiz_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pontuação no Quiz')),
                ('quiz_attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas no Quiz')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='knowledge_trails.lesson', verbose_name='Lição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Progresso na Lição',
                'verbose_name_plural': 'Progressos nas Lições',
                'unique_together': {('lesson', 'user')},
            },
        ),
    ]
