# Generated by Django 5.2.7 on 2025-11-24 18:33

import knowledge_trails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='document_file',
            field=models.FileField(blank=True, help_text='PDF, DOC, PPT, XLS, etc.', null=True, upload_to=knowledge_trails.models.upload_lesson_media, verbose_name='Arquivo de Documento'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Lição obrigatória para conclusão do módulo', verbose_name='Obrigatória'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload de vídeo (MP4, WebM, etc.)', null=True, upload_to=knowledge_trails.models.upload_lesson_media, verbose_name='Arquivo de Vídeo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='media_file',
            field=models.FileField(blank=True, help_text='Outros arquivos (imagens, etc.)', null=True, upload_to=knowledge_trails.models.upload_lesson_media, verbose_name='Arquivo de Mídia'),
        ),
    ]
