# Generated by Django 5.2.7 on 2025-11-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_trails', '0003_rename_quiz_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Texto'), ('video', 'Vídeo'), ('document', 'Documento'), ('quiz', 'Quiz'), ('interactive', 'Interativo')], default='text', max_length=20, verbose_name='Tipo de Lição'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='points',
            field=models.PositiveIntegerField(default=10, help_text='Pontos ganhos ao acertar esta questão', verbose_name='Pontos'),
        ),
    ]
