# Generated by Django 5.2.5 on 2025-12-12 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_trails', '0004_alter_lesson_lesson_type_alter_quizquestion_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Resposta Correta')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Número da Tentativa')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Respondido em')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='knowledge_trails.quizquestion', verbose_name='Pergunta')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='knowledge_trails.quizoption', verbose_name='Opção Selecionada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resposta do Quiz',
                'verbose_name_plural': 'Respostas do Quiz',
                'ordering': ['-answered_at'],
            },
        ),
    ]
