# Generated by Django 5.2.5 on 2026-03-11 11:11

import django.db.models.deletion
import knowledge_trails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_trails', '0005_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Texto'), ('video', 'Vídeo'), ('document', 'Documento'), ('quiz', 'Quiz'), ('interactive', 'Interativo'), ('slides_images', 'Slides (Imagens)'), ('slides_pdf', 'Slides (PDF)')], default='text', max_length=20, verbose_name='Tipo de Lição'),
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=knowledge_trails.models.upload_slide_image, verbose_name='Imagem do Slide')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_images', to='knowledge_trails.lesson', verbose_name='Lição')),
            ],
            options={
                'verbose_name': 'Imagem de Slide',
                'verbose_name_plural': 'Imagens de Slide',
                'ordering': ['order'],
            },
        ),
    ]
