# Generated by Django 5.2.5 on 2026-04-06 13:32

import core.storage
import knowledge_trails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_trails', '0007_trail_module_lesson_logo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetrail',
            name='certificate_logo',
            field=models.ImageField(blank=True, help_text='Logo que aparecerá no certificado', null=True, storage=core.storage.MediaStorage, upload_to=knowledge_trails.models.upload_certificate_logo, verbose_name='Logo para Certificado'),
        ),
        migrations.AlterField(
            model_name='knowledgetrail',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=knowledge_trails.models.upload_trail_icon, verbose_name='Ícone da Trilha'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='document_file',
            field=models.FileField(blank=True, help_text='PDF, DOC, PPT, XLS, etc.', null=True, storage=core.storage.MediaStorage, upload_to=knowledge_trails.models.upload_lesson_media, verbose_name='Arquivo de Documento'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Imagem exibida no lugar do emoji quando enviada', null=True, storage=core.storage.MediaStorage, upload_to=knowledge_trails.models.upload_lesson_logo, verbose_name='Logo da Lição'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='media_file',
            field=models.FileField(blank=True, help_text='Outros arquivos (imagens, etc.)', null=True, storage=core.storage.MediaStorage, upload_to=knowledge_trails.models.upload_lesson_media, verbose_name='Arquivo de Mídia'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload de vídeo (MP4, WebM, etc.)', null=True, storage=core.storage.MediaStorage, upload_to=knowledge_trails.models.upload_lesson_media, verbose_name='Arquivo de Vídeo'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='image',
            field=models.ImageField(storage=core.storage.MediaStorage, upload_to=knowledge_trails.models.upload_slide_image, verbose_name='Imagem do Slide'),
        ),
        migrations.AlterField(
            model_name='trailmodule',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Imagem exibida no lugar do emoji quando enviada', null=True, storage=core.storage.MediaStorage, upload_to=knowledge_trails.models.upload_module_logo, verbose_name='Logo do Módulo'),
        ),
    ]
