# Generated by Django 5.2.5 on 2026-06-16 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_trails', '0008_alter_knowledgetrail_certificate_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetrail',
            name='mandatory_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Período Obrigatório'),
        ),
        migrations.AddField(
            model_name='knowledgetrail',
            name='mandatory_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Período Obrigatório'),
        ),
        migrations.AddField(
            model_name='knowledgetrail',
            name='mandatory_users',
            field=models.ManyToManyField(blank=True, help_text='Usuários que devem concluir esta trilha', related_name='mandatory_trails', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Obrigatórios'),
        ),
    ]
