# Generated by Django 5.2.5 on 2026-06-26 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_trails', '0009_knowledgetrail_mandatory_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='answer_text',
            field=models.TextField(blank=True, help_text='Texto enviado pelo aluno em questões discursivas.', verbose_name='Resposta Discursiva'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='awarded_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Pontos Concedidos'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Avaliado em'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quiz_answers', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='grader_feedback',
            field=models.TextField(blank=True, verbose_name='Comentário do Avaliador'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='grading_status',
            field=models.CharField(choices=[('auto', 'Corrigida automaticamente'), ('pending', 'Aguardando avaliação'), ('graded', 'Avaliada')], default='auto', max_length=20, verbose_name='Status da Avaliação'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('discursive', 'Discursiva')], default='multiple_choice', help_text='Múltipla escolha é corrigida automaticamente; discursiva é avaliada pelo gestor.', max_length=20, verbose_name='Tipo de Pergunta'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas em questões de múltipla escolha.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='knowledge_trails.quizoption', verbose_name='Opção Selecionada'),
        ),
    ]
