# Generated by Django 5.2.5 on 2026-10-01 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_trails', '0011_popup_trilha5_gerente_adm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetrail',
            name='blocks_portal',
            field=models.BooleanField(db_default=False, default=False, help_text='Só gestores (ADMIN/SUPERADMIN) podem ligar. Vale no período obrigatório.', verbose_name='Travar o portal até concluir'),
        ),
        migrations.AddField(
            model_name='knowledgetrail',
            name='require_signature',
            field=models.BooleanField(db_default=False, default=False, help_text='Ao terminar, a pessoa declara que assistiu e assina com o próprio nome.', verbose_name='Pedir assinatura ao concluir'),
        ),
        migrations.CreateModel(
            name='TrailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_name', models.CharField(max_length=160, verbose_name='Nome digitado')),
                ('declaration', models.TextField(verbose_name='Declaração assinada')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Assinada em')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Navegador')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='knowledge_trails.knowledgetrail', verbose_name='Trilha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Assinatura de trilha',
                'verbose_name_plural': 'Assinaturas de trilha',
                'ordering': ['-signed_at'],
                'constraints': [models.UniqueConstraint(fields=('trail', 'user'), name='uniq_assinatura_trilha')],
            },
        ),
    ]
