# Generated by Django 5.2.5 on 2026-07-27 15:01

import core.storage
import django.db.models.deletion
import limpeza.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0027_user_vacation_end_date_user_vacation_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimpezaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilar', models.CharField(blank=True, max_length=200, verbose_name='Pilar')),
                ('item', models.CharField(blank=True, max_length=200, verbose_name='Item')),
                ('gravidade', models.CharField(blank=True, choices=[('leve', 'Leve'), ('media', 'Média'), ('grave', 'Grave'), ('inegociavel', 'Inegociável')], max_length=20, verbose_name='Gravidade')),
                ('text', models.CharField(max_length=500, verbose_name='Pergunta')),
                ('detalhamento', models.TextField(blank=True, verbose_name='Detalhamento')),
                ('contestavel', models.BooleanField(default=True, verbose_name='Contestável?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Pontos')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LimpezaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_se_aplica', 'Não se aplica')], default='nao', max_length=20, verbose_name='Resposta')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('ticket_number', models.CharField(blank=True, help_text='Preenchido quando a resposta é "Não".', max_length=50, verbose_name='Número do Chamado')),
                ('photo', models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to=limpeza.models.upload_limpeza_photo, verbose_name='Foto')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Recusa')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpeza_answers', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='limpeza.limpezaquestion', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['question__order', 'question__id'],
            },
        ),
        migrations.CreateModel(
            name='LimpezaAnswerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(storage=core.storage.MediaStorage(), upload_to=limpeza.models.upload_limpeza_photo, verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='limpeza.limpezaanswer', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Foto da Resposta',
                'verbose_name_plural': 'Fotos das Respostas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LimpezaEvaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sectors', models.ManyToManyField(blank=True, related_name='limpeza_evaluators', to='users.sector', verbose_name='Setores que avalia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpeza_evaluator_roles', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
            ],
            options={
                'verbose_name': 'Avaliador',
                'verbose_name_plural': 'Avaliadores',
            },
        ),
        migrations.CreateModel(
            name='LimpezaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpeza_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Limpeza',
                'verbose_name_plural': 'Templates de Limpeza',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='limpezaquestion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='limpeza.limpezatemplate', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='LimpezaTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Mês')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado Parcialmente'), ('finalizado', 'Finalizado')], default='aberto', max_length=20, verbose_name='Status')),
                ('evaluation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Avaliação')),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pontuação (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpeza_todos_evaluated', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
                ('launched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpeza_todos_launched', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpeza_todos', to='users.sector', verbose_name='Setor')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpeza_todos_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='limpeza.limpezatemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'To-Do Limpeza',
                'verbose_name_plural': 'To-Dos Limpeza',
                'ordering': ['-year', '-month', 'sector__name'],
            },
        ),
        migrations.AddField(
            model_name='limpezaanswer',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='limpeza.limpezatodo', verbose_name='To-Do'),
        ),
        migrations.AddConstraint(
            model_name='limpezatodo',
            constraint=models.UniqueConstraint(fields=('sector', 'month', 'year', 'template'), name='unique_limpeza_todo_sector_month_template'),
        ),
        migrations.AddConstraint(
            model_name='limpezaanswer',
            constraint=models.UniqueConstraint(fields=('todo', 'question'), name='unique_limpeza_answer_per_question'),
        ),
    ]
