# Generated by Django 5.2.5 on 2026-08-18 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limpeza', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limpezatodo',
            options={'ordering': ['-realizada_em', '-year', '-month', 'sector__name'], 'verbose_name': 'To-Do Limpeza', 'verbose_name_plural': 'To-Dos Limpeza'},
        ),
        migrations.RemoveConstraint(
            model_name='limpezatodo',
            name='unique_limpeza_todo_sector_month_template',
        ),
        migrations.AddField(
            model_name='limpezatodo',
            name='realizada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da limpeza'),
        ),
        migrations.AddField(
            model_name='limpezatodo',
            name='realizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpezas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Limpeza feita por'),
        ),
        migrations.AlterField(
            model_name='limpezatodo',
            name='launched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limpeza_todos_launched', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por'),
        ),
    ]
