# Generated by Django 5.2.5 on 2025-09-16 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Detalhes dos itens/serviços solicitados', verbose_name='Descrição')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Total')),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('APROVADA', 'Aprovada'), ('EM_PROCESSAMENTO', 'Em Processamento'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Solicitação')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Entrega Prevista')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('notes', models.TextField(blank=True, help_text='Observações adicionais sobre a compra', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='suppliers.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-created_at'],
            },
        ),
    ]
