# Generated by Django 5.2.7 on 2025-10-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='accumulated_livelo_points',
            field=models.BooleanField(default=False, verbose_name='Acumulou Pontos Livelo'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='livelo_points_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Pontos Livelo'),
        ),
    ]
