# Generated by Django 5.2.7 on 2025-10-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_accumulated_livelo_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Cartão de Crédito, Boleto, PIX, etc.', max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Detalhes sobre esta forma de pagamento', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('requires_approval', models.BooleanField(default=False, help_text='Compras com esta forma de pagamento precisam de aprovação', verbose_name='Requer Aprovação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='purchases.paymentmethod', verbose_name='Forma de Pagamento'),
        ),
    ]
