# Generated by Django 5.2.7 on 2025-11-26 17:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_add_uniform_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('home', 'Vitória Casa'), ('draw', 'Empate'), ('away', 'Vitória Visitante')], max_length=10, verbose_name='Tipo de Aposta')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Apostado (C$)')),
                ('odds_at_bet', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Odds no Momento')),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Potencial')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('won', 'Ganhou'), ('lost', 'Perdeu'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending', max_length=20, verbose_name='Status')),
                ('winnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Ganho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Apostado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aposta',
                'verbose_name_plural': 'Apostas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('bet', 'Aposta'), ('win', 'Ganho'), ('refund', 'Reembolso')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Antes')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Depois')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='betting.bet', verbose_name='Aposta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação de Aposta',
                'verbose_name_plural': 'Transações de Apostas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Campeonato')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('google_sheet_url', models.URLField(blank=True, help_text='Cole aqui o link da planilha com a tabela do campeonato', verbose_name='URL da Planilha Google Sheets')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('paused', 'Pausado'), ('finished', 'Finalizado')], default='draft', max_length=20, verbose_name='Status')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='betting/championships/', verbose_name='Banner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_championships', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('participating_sectors', models.ManyToManyField(related_name='championships', to='users.sector', verbose_name='Setores Participantes')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='Gols Casa')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='Gols Visitante')),
                ('odds_home', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='Odds Vitória Casa')),
                ('odds_draw', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='Odds Empate')),
                ('odds_away', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='Odds Vitória Visitante')),
                ('match_date', models.DateTimeField(verbose_name='Data e Hora do Jogo')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('live', 'Ao Vivo'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Status')),
                ('round_number', models.PositiveIntegerField(default=1, verbose_name='Rodada')),
                ('result', models.CharField(choices=[('pending', 'Pendente'), ('home', 'Vitória Casa'), ('draw', 'Empate'), ('away', 'Vitória Visitante')], default='pending', max_length=10, verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='users.sector', verbose_name='Time Visitante (Setor 2)')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='betting.championship', verbose_name='Campeonato')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='users.sector', verbose_name='Time da Casa (Setor 1)')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['match_date'],
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betting.match', verbose_name='Partida'),
        ),
    ]
