# Generated by Django 5.2.7 on 2025-11-28 14:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        ('users', '0008_add_uniform_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championships_won', to='users.sector', verbose_name='Campeão'),
        ),
        migrations.CreateModel(
            name='ChampionBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Apostado (C$)')),
                ('odds_at_bet', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Odds no Momento')),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Potencial')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('won', 'Ganhou'), ('lost', 'Perdeu'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending', max_length=20, verbose_name='Status')),
                ('winnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Ganho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Apostado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_bets', to='betting.championship', verbose_name='Campeonato')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_bets_received', to='users.sector', verbose_name='Time Apostado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_bets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aposta de Campeão',
                'verbose_name_plural': 'Apostas de Campeão',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScorerBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Apostado (C$)')),
                ('odds_at_bet', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Odds no Momento')),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Potencial')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('won', 'Ganhou'), ('lost', 'Perdeu'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending', max_length=20, verbose_name='Status')),
                ('winnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Ganho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Apostado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer_bets', to='betting.match', verbose_name='Partida')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer_bets_received', to=settings.AUTH_USER_MODEL, verbose_name='Jogador Apostado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer_bets', to=settings.AUTH_USER_MODEL, verbose_name='Apostador')),
            ],
            options={
                'verbose_name': 'Aposta de Artilheiro',
                'verbose_name_plural': 'Apostas de Artilheiro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChampionOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6, verbose_name='Odds')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, não aceita mais apostas', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_odds', to='betting.championship', verbose_name='Campeonato')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_odds', to='users.sector', verbose_name='Time (Setor)')),
            ],
            options={
                'verbose_name': 'Odd de Campeão',
                'verbose_name_plural': 'Odds de Campeões',
                'ordering': ['odds'],
                'unique_together': {('championship', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='MatchScorerOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=6, verbose_name='Odds')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, não aceita mais apostas', verbose_name='Ativo')),
                ('scored', models.BooleanField(default=False, verbose_name='Marcou Gol')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Gols Marcados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer_odds', to='betting.match', verbose_name='Partida')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer_odds', to=settings.AUTH_USER_MODEL, verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Odd de Artilheiro',
                'verbose_name_plural': 'Odds de Artilheiros',
                'ordering': ['odds'],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
