# Generated by Django 5.2.7 on 2025-11-28 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_championship_champion_championbet_scorerbet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('bet', 'Aposta'), ('win', 'Ganho'), ('win_profit', 'Lucro Aprovado'), ('refund', 'Reembolso')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='BetWinApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('match', 'Aposta de Partida'), ('champion', 'Aposta de Campeão'), ('scorer', 'Aposta de Artilheiro')], max_length=20, verbose_name='Tipo de Aposta')),
                ('bet_id', models.PositiveIntegerField(help_text='ID da aposta no modelo correspondente', verbose_name='ID da Aposta')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Apostado')),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro (para aprovação)')),
                ('total_win', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Total')),
                ('odds_at_bet', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Odds')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição da Aposta')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Revisão')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_approvals_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_win_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aprovação de Lucro de Aposta',
                'verbose_name_plural': 'Aprovações de Lucros de Apostas',
                'ordering': ['-created_at'],
            },
        ),
    ]
