# Generated by Django 4.2.16 on 2025-11-30 09:53

import betting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_alter_bettransaction_transaction_type_betwinapproval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championship',
            old_name='google_sheet_url',
            new_name='table_url',
        ),
        migrations.AlterField(
            model_name='championship',
            name='table_url',
            field=models.URLField(blank=True, help_text='Cole aqui o link do site com a tabela do campeonato (será exibido em tela cheia)', verbose_name='URL da Tabela de Classificação'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=betting.models.upload_championship_banner, verbose_name='Banner'),
        ),
    ]
