# Generated by Django 5.2.5 on 2026-08-28 17:53

import core.storage
import cursos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0016_alter_communication_image_and_more'),
        ('users', '0036_userchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloquear_navegacao', models.BooleanField(default=False, help_text='Nasce desligado de propósito: confira o quadro com dados reais antes de ligar.', verbose_name='Travar o portal de quem está com curso vencido')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('gestores', models.ManyToManyField(blank=True, help_text='Publicam o curso do mês, escrevem as orientações e conferem os comprovantes.', related_name='cursos_gestor_de', to=settings.AUTH_USER_MODEL, verbose_name='Gestores do módulo')),
                ('grupos', models.ManyToManyField(blank=True, related_name='cursos_config', to='communications.communicationgroup', verbose_name='Grupos cobrados')),
                ('setores', models.ManyToManyField(blank=True, related_name='cursos_config', to='users.sector', verbose_name='Setores cobrados')),
            ],
            options={
                'verbose_name': 'Configuração de Cursos',
                'verbose_name_plural': 'Configuração de Cursos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOCO', 'Curso Foco (mensal)'), ('CAPACITACAO', 'Capacitação Inicial (sob demanda)')], default='FOCO', max_length=12, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('orientacoes', models.TextField(blank=True, help_text='O que a pessoa precisa saber para fazer o curso. Aparece na tela dela.', verbose_name='Orientações')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Link do curso')),
                ('competencia', models.DateField(blank=True, help_text='Só para o Curso Foco. Guarda sempre o dia 1º do mês.', null=True, verbose_name='Mês de referência')),
                ('prazo', models.DateField(verbose_name='Prazo para anexar o comprovante')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-prazo', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(storage=core.storage.MediaStorage, upload_to=cursos.models.caminho_comprovante, verbose_name='Comprovante')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando conferência'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=10)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação do gestor')),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes_curso', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprovantes_revisados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Comprovante de curso',
                'verbose_name_plural': 'Comprovantes de curso',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['curso', 'colaborador'], name='cursos_comp_curso_i_366fa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atribuido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_atribuidos_por_mim', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Atribuição de curso',
                'verbose_name_plural': 'Atribuições de curso',
                'unique_together': {('curso', 'colaborador')},
            },
        ),
    ]
