# Generated by Django 5.2.5 on 2026-09-01 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocursos',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Escolhidas uma a uma. Somam-se aos grupos e setores — servem para incluir quem não está em nenhum deles.', related_name='cursos_cobrado_em', to=settings.AUTH_USER_MODEL, verbose_name='Pessoas cobradas'),
        ),
    ]
