# Generated by Django 5.2.5 on 2026-10-05 17:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# O grupo de gestão de cada loja, como veio da operação em 05/10/2026.
GRUPOS = [
    ('Loja Piuma', '120363406942610139'),
    ('Loja Anchieta', '120363406118073903'),
    ('Loja Quissama', '120363422221690678'),
    ('Loja Miracema', '120363405550977466'),
    ('Loja Bom Jesus do Itabapoana', '120363424798431502'),
    ('Loja Sao Fidelis', '120363422481137292'),
    ('Loja Iconha', '120363423466184045'),
    ('Loja Santo Antonio de Padua', '120363424904060013'),
    ('Loja Centro Vila Velha', '120363425034330338'),
    ('Loja Centro VIX', '120363406843832968'),
    ('Loja Glória', '120363406488274140'),
    ('Loja Itaciba', '120363425841414354'),
    ('Loja Marcilio De Noronha', '120363408273926315'),
    ('Loja Masterplace', '5527997784149-1612196334'),
    ('Loja Montserrat', '5527997784149-1568645578'),
    ('Loja Jacaraípe', '120363425148654553'),
    ('Loja Laranjeiras', '120363406341761193'),
    ('Loja Norte Sul', '120363404670542017'),
    ('Loja Serra Sede', '120363422992696729'),
    ('Loja Porto Canoa', '120363421913879275'),
]


def cadastrar_grupos(apps, schema_editor):
    Sector = apps.get_model('users', 'Sector')
    Grupo = apps.get_model('cursos', 'GrupoWhatsappLoja')
    for nome, grupo in GRUPOS:
        setor = Sector.objects.filter(name__iexact=nome).order_by('id').first()
        if setor and not Grupo.objects.filter(setor=setor).exists():
            Grupo.objects.create(setor=setor, grupo=grupo, ativo=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_configuracaocursos_usuarios'),
        ('users', '0043_validacao_hc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocursos',
            name='cobranca_automatica',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Cobrar sozinho no WhatsApp das lojas'),
        ),
        migrations.AddField(
            model_name='configuracaocursos',
            name='cobranca_dias',
            field=models.CharField(blank=True, db_default='0,2,4', default='0,2,4', help_text='Dias da semana separados por vírgula: 0 = segunda … 6 = domingo.', max_length=20, verbose_name='Dias da cobrança'),
        ),
        migrations.AddField(
            model_name='configuracaocursos',
            name='cobranca_hora',
            field=models.TimeField(db_default=datetime.time(9, 0), default=datetime.time(9, 0), verbose_name='Hora da cobrança'),
        ),
        migrations.AddField(
            model_name='configuracaocursos',
            name='ultima_cobranca_automatica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CobrancaWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=80)),
                ('pessoas', models.PositiveIntegerField(default=0)),
                ('texto', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('MANUAL', 'Pelo quadro'), ('AUTOMATICA', 'Automática')], default='MANUAL', max_length=10)),
                ('enviado', models.BooleanField(help_text='Vazio enquanto está sendo enviada.', null=True, verbose_name='Saiu?')),
                ('detalhe', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cursos', models.ManyToManyField(blank=True, related_name='cobrancas_whatsapp', to='cursos.curso')),
                ('disparado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas_cursos_disparadas', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas_cursos', to='users.sector')),
            ],
            options={
                'verbose_name': 'Cobrança de curso no WhatsApp',
                'verbose_name_plural': 'Cobranças de curso no WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='GrupoWhatsappLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=80, verbose_name='ID do grupo no WhatsApp')),
                ('ativo', models.BooleanField(db_default=True, default=True, verbose_name='Cobrar neste grupo')),
                ('setor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_whatsapp_cursos', to='users.sector', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Grupo de WhatsApp da loja',
                'verbose_name_plural': 'Grupos de WhatsApp das lojas',
                'ordering': ['setor__name'],
            },
        ),
        migrations.RunPython(cadastrar_grupos, migrations.RunPython.noop),
    ]
