# Generated by Django 5.2.5 on 2026-02-12 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=100, verbose_name='Filial')),
                ('vendedor', models.CharField(max_length=200, verbose_name='Vendedor')),
                ('receita', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita')),
                ('pilar', models.CharField(max_length=50, verbose_name='Pilar')),
                ('coordenacao', models.CharField(blank=True, default='', max_length=200, verbose_name='Coordenação')),
                ('numero_venda', models.CharField(blank=True, default='', max_length=100, verbose_name='Nº da Venda')),
                ('data_venda', models.CharField(blank=True, default='', max_length=50, verbose_name='Data da Venda')),
                ('nome_cliente', models.CharField(blank=True, default='', max_length=300, verbose_name='Nome Cliente')),
                ('cpf_cnpj', models.CharField(blank=True, default='', max_length=30, verbose_name='CPF/CNPJ')),
                ('plano_produto', models.CharField(blank=True, default='', max_length=300, verbose_name='Plano/Produto')),
                ('numero_acesso', models.CharField(blank=True, default='', max_length=100, verbose_name='Número Acesso')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
            ],
            options={
                'verbose_name': 'Registro de Exclusão',
                'verbose_name_plural': 'Registros de Exclusão',
                'ordering': ['-imported_at'],
                'indexes': [models.Index(fields=['filial'], name='contestacao_filial_6d768c_idx'), models.Index(fields=['vendedor'], name='contestacao_vendedo_e98974_idx'), models.Index(fields=['pilar'], name='contestacao_pilar_45d34a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motivo da Contestação')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contestacoes/%Y/%m/', verbose_name='Anexo/Evidência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('not_applicable', 'N/A'), ('pending_payment', 'Aguardando Pagamento'), ('paid', 'Pago')], default='not_applicable', max_length=20, verbose_name='Status do Pagamento')),
                ('review_notes', models.TextField(blank=True, default='', verbose_name='Observações da Análise')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Análise')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestations_created', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestations_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Analisado por')),
                ('exclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestations', to='contestacao.exclusionrecord', verbose_name='Registro de Exclusão')),
            ],
            options={
                'verbose_name': 'Contestação',
                'verbose_name_plural': 'Contestações',
                'ordering': ['-created_at'],
            },
        ),
    ]
