# Generated by Django 5.2.5 on 2026-02-13 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contestation',
            name='confirmation_notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações da Confirmação'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Confirmação'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestations_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AlterField(
            model_name='contestation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aprovada pelo Gestor'), ('rejected', 'Rejeitada'), ('confirmed', 'Confirmada pelo Gerente'), ('denied', 'Negada pelo Gerente')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
