# Generated by Django 4.2.16 on 2026-02-26 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contestacao', '0002_contestation_confirmation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusionrecord',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.CreateModel(
            name='ContestationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Contestação Criada'), ('approved', 'Aprovada pelo Gestor'), ('rejected', 'Rejeitada pelo Gestor'), ('confirmed', 'Confirmada pelo Gerente'), ('denied', 'Negada pelo Gerente'), ('paid', 'Marcada como Paga'), ('synced', 'Planilha Sincronizada')], max_length=20, verbose_name='Ação')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('contestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='contestacao.contestation', verbose_name='Contestação')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Contestação',
                'verbose_name_plural': 'Históricos de Contestações',
                'ordering': ['-created_at'],
            },
        ),
    ]
