# Generated by Django 5.2.5 on 2026-08-25 18:01

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestacao', '0010_exclusionsyncbatch_exclusionrecord_sync_batch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contestationcartdraft',
            new_name='contestacao_user_id_949fd8_idx',
            old_name='contestacao__user_id_6dbd40_idx',
        ),
        migrations.RenameIndex(
            model_name='exclusionrecord',
            new_name='contestacao_sync_ba_25c927_idx',
            old_name='contestacao_sync_ba_idx',
        ),
        migrations.AddField(
            model_name='exclusionrecord',
            name='recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Recebido'),
        ),
        migrations.AddField(
            model_name='exclusionrecord',
            name='record_type',
            field=models.CharField(choices=[('exclusao', 'BASE_EXCLUSAO'), ('pagamento', 'BASE_PAGAMENTO (valores)')], db_index=True, default='exclusao', max_length=12, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='exclusionsyncbatch',
            name='record_type',
            field=models.CharField(choices=[('exclusao', 'BASE_EXCLUSAO'), ('pagamento', 'BASE_PAGAMENTO (valores)')], db_index=True, default='exclusao', max_length=12, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='contestation',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to='contestacoes/%Y/%m/', verbose_name='Anexo/Evidência'),
        ),
        migrations.AlterField(
            model_name='exclusionsyncbatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='exclusionrecord',
            index=models.Index(fields=['record_type', 'sync_batch'], name='contestacao_record__9e4fb6_idx'),
        ),
    ]
