# Generated by Django 5.2.5 on 2026-08-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestacao', '0011_rename_contestacao__user_id_6dbd40_idx_contestacao_user_id_949fd8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestationhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Contestação Criada'), ('approved', 'Aprovada pelo Gestor'), ('approved_and_contested', 'Aprovada e Contestada pelo Gestor'), ('rejected', 'Rejeitada pelo Gestor'), ('confirmed', 'Confirmada pelo Gerente'), ('denied', 'Negada pelo Gerente'), ('paid', 'Marcada como Paga'), ('synced', 'Planilha Sincronizada'), ('synced_pagamento', 'Base de Pagamento Sincronizada')], max_length=30, verbose_name='Ação'),
        ),
    ]
