# Generated by Django 5.2.5 on 2026-08-31 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestacao', '0012_alter_contestationhistory_action'),
        ('users', '0036_userchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiberacaoContestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.DateTimeField(verbose_name='Liberado até')),
                ('motivo', models.CharField(blank=True, default='', help_text='Fica registrado para quem for auditar a rodada depois.', max_length=200, verbose_name='Motivo')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liberacoes_contestacao_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberacoes_contestacao', to='users.sector', verbose_name='Setor liberado')),
            ],
            options={
                'verbose_name': 'Liberação de contestação',
                'verbose_name_plural': 'Liberações de contestação',
                'ordering': ['-prazo'],
                'indexes': [models.Index(fields=['setor', 'prazo'], name='contestacao_setor_i_60bc7f_idx')],
            },
        ),
    ]
