# Generated by Django 5.2.5 on 2026-08-17 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPontoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(verbose_name='ID no Tangerino')),
                ('momento', models.DateTimeField(verbose_name='Horário registrado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atrasado', models.BooleanField(default=False, verbose_name='Marcação retroativa')),
                ('justificativa', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('retorno', models.TextField(blank=True, verbose_name='Resposta do Tangerino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes_portal', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ponto batido pelo portal',
                'verbose_name_plural': 'Pontos batidos pelo portal',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SincronizacaoTangerino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VINCULO', 'Vínculo de funcionários')], default='VINCULO', max_length=20)),
                ('executada_em', models.DateTimeField(auto_now_add=True)),
                ('casados_cpf', models.PositiveIntegerField(default=0, verbose_name='Casados por CPF')),
                ('casados_nome', models.PositiveIntegerField(default=0, verbose_name='Casados por nome')),
                ('ja_vinculados', models.PositiveIntegerField(default=0, verbose_name='Já vinculados')),
                ('sem_correspondencia', models.PositiveIntegerField(default=0, verbose_name='Sem correspondência')),
                ('sucesso', models.BooleanField(default=True)),
                ('detalhe', models.TextField(blank=True, verbose_name='Detalhe / erro')),
                ('executada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizacoes_tangerino', to=settings.AUTH_USER_MODEL, verbose_name='Executada por')),
            ],
            options={
                'verbose_name': 'Sincronização com o Tangerino',
                'verbose_name_plural': 'Sincronizações com o Tangerino',
                'ordering': ['-executada_em'],
            },
        ),
    ]
