# Generated by Django 5.2.5 on 2026-08-17 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_configuracao_padrao(apps, schema_editor):
    """Nasce fechado: módulo restrito ao GRUPO DE TESTE (id 38) e registro de
    ponto pelo portal desligado — a tela fica só informativa até alguém ligar."""
    Configuracao = apps.get_model('tangerino', 'ConfiguracaoTangerino')
    Grupo = apps.get_model('communications', 'CommunicationGroup')
    grupo = Grupo.objects.filter(id=38).first()
    Configuracao.objects.update_or_create(
        pk=1,
        defaults={
            'ativo': True,
            'restrito_ao_grupo': True,
            'grupo': grupo,
            'permitir_bater_ponto': False,
            'exigir_foto': True,
            'permitir_ponto_atrasado': False,
            'mostrar_widget_home': True,
            'mostrar_popup_ferias': True,
            'bloquear_navegacao_ferias': False,
        })


def remover_configuracao(apps, schema_editor):
    apps.get_model('tangerino', 'ConfiguracaoTangerino').objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0014_popup_comunicados_pendentes'),
        ('tangerino', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registropontoportal',
            name='com_foto',
            field=models.BooleanField(default=False, verbose_name='Enviou foto'),
        ),
        migrations.AddField(
            model_name='sincronizacaotangerino',
            name='atualizados',
            field=models.PositiveIntegerField(default=0, verbose_name='Registros atualizados'),
        ),
        migrations.AddField(
            model_name='sincronizacaotangerino',
            name='criados',
            field=models.PositiveIntegerField(default=0, verbose_name='Registros criados'),
        ),
        migrations.AlterField(
            model_name='sincronizacaotangerino',
            name='tipo',
            field=models.CharField(choices=[('VINCULO', 'Vínculo de funcionários'), ('PONTO', 'Marcações de ponto'), ('FERIAS', 'Lançamentos de férias')], default='VINCULO', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracaoTangerino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder as telas de ponto e férias de todo mundo.', verbose_name='Módulo Ponto e Férias ativo')),
                ('restrito_ao_grupo', models.BooleanField(default=True, help_text='Desmarque para liberar o módulo para todo o portal.', verbose_name='Liberar apenas para o grupo escolhido')),
                ('permitir_bater_ponto', models.BooleanField(default=False, help_text='Desligado, as telas mostram o ponto apenas como informação.', verbose_name='Permitir bater ponto pelo portal')),
                ('exigir_foto', models.BooleanField(default=True, help_text='O Tangerino recusa marcação pela web sem foto nesta empresa.', verbose_name='Exigir foto ao bater ponto')),
                ('permitir_ponto_atrasado', models.BooleanField(default=False, verbose_name='Permitir marcação retroativa pelo portal')),
                ('mostrar_widget_home', models.BooleanField(default=True, verbose_name='Mostrar o cartão de ponto na home')),
                ('mostrar_popup_ferias', models.BooleanField(default=True, verbose_name='Mostrar o popup de férias')),
                ('bloquear_navegacao_ferias', models.BooleanField(default=False, verbose_name='Bloquear o portal para quem está de férias')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('grupo', models.ForeignKey(blank=True, help_text='Grupo de comunicação cujos membros enxergam o módulo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.communicationgroup', verbose_name='Grupo liberado')),
            ],
            options={
                'verbose_name': 'Configuração do Tangerino',
                'verbose_name_plural': 'Configuração do Tangerino',
            },
        ),
        migrations.CreateModel(
            name='FeriasLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tangerino_id', models.BigIntegerField(unique=True, verbose_name='ID no Tangerino')),
                ('employee_id', models.IntegerField(db_index=True, verbose_name='ID do funcionário')),
                ('nome_funcionario', models.CharField(blank=True, max_length=200, verbose_name='Nome no Tangerino')),
                ('inicio', models.DateField(db_index=True, verbose_name='Início')),
                ('fim', models.DateField(db_index=True, verbose_name='Fim')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('origem', models.CharField(blank=True, max_length=40, verbose_name='Origem')),
                ('dia_inteiro', models.BooleanField(default=True, verbose_name='Dia inteiro')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='Sincronizado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferias_lancamentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do portal')),
            ],
            options={
                'verbose_name': 'Férias (sincronizada)',
                'verbose_name_plural': 'Férias (sincronizadas)',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='MarcacaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tangerino_id', models.BigIntegerField(unique=True, verbose_name='ID no Tangerino')),
                ('employee_id', models.IntegerField(db_index=True, verbose_name='ID do funcionário')),
                ('nome_funcionario', models.CharField(blank=True, max_length=200, verbose_name='Nome no Tangerino')),
                ('dia', models.DateField(db_index=True, verbose_name='Dia')),
                ('entrada', models.DateTimeField(blank=True, null=True, verbose_name='Entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('nsr_entrada', models.BigIntegerField(blank=True, null=True, verbose_name='NSR da entrada')),
                ('nsr_saida', models.BigIntegerField(blank=True, null=True, verbose_name='NSR da saída')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Status')),
                ('plataforma', models.CharField(blank=True, max_length=30, verbose_name='Plataforma')),
                ('editado', models.BooleanField(default=False, verbose_name='Editado no Tangerino')),
                ('ajuste', models.BooleanField(default=False, verbose_name='É ajuste/afastamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='Sincronizado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcacoes_ponto', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do portal')),
            ],
            options={
                'verbose_name': 'Marcação de ponto (sincronizada)',
                'verbose_name_plural': 'Marcações de ponto (sincronizadas)',
                'ordering': ['-dia', '-entrada'],
                'indexes': [models.Index(fields=['employee_id', 'dia'], name='tangerino_m_employe_a2849e_idx')],
            },
        ),
        migrations.RunPython(criar_configuracao_padrao, remover_configuracao),
    ]
