# Generated by Django 5.2.5 on 2026-08-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0002_registropontoportal_com_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaotangerino',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para esconder as telas de ponto e férias. Superusuários continuam entrando, para poder religar.', verbose_name='Módulo Ponto e Férias ativo'),
        ),
    ]
