# Generated by Django 5.2.5 on 2026-08-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0003_alter_configuracaotangerino_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropontoportal',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL da foto no Tangerino'),
        ),
        migrations.AddField(
            model_name='registropontoportal',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropontoportal',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
