# Generated by Django 5.2.5 on 2026-08-18 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0006_ferias_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sincronizacaotangerino',
            name='tipo',
            field=models.CharField(choices=[('VINCULO', 'Vínculo de funcionários'), ('PONTO', 'Marcações de ponto'), ('FERIAS', 'Lançamentos de férias'), ('SALDO', 'Saldo de banco de horas')], default='VINCULO', max_length=20),
        ),
        migrations.CreateModel(
            name='SaldoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True, verbose_name='ID do funcionário')),
                ('nome', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail no Tangerino')),
                ('saldo_minutos', models.IntegerField(default=0, help_text='Positivo = horas a favor do colaborador; negativo = horas devidas.', verbose_name='Saldo (minutos)')),
                ('periodo_inicio', models.DateField(verbose_name='Período — início')),
                ('periodo_fim', models.DateField(verbose_name='Período — fim')),
                ('sincronizado_em', models.DateTimeField(verbose_name='Sincronizado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_horas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do portal')),
            ],
            options={
                'verbose_name': 'Saldo de horas (sincronizado)',
                'verbose_name_plural': 'Saldos de horas (sincronizados)',
                'ordering': ['nome'],
            },
        ),
    ]
