# Generated by Django 5.2.5 on 2026-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0007_alter_sincronizacaotangerino_tipo_saldohoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tangerino_id', models.IntegerField(unique=True, verbose_name='ID no Tangerino')),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='Nome da escala')),
                ('horas_por_dia', models.JSONField(blank=True, default=dict, verbose_name='Segundos previstos por dia da semana')),
                ('segundos_semana', models.PositiveIntegerField(default=0, verbose_name='Total previsto na semana (segundos)')),
                ('sincronizado_em', models.DateTimeField(verbose_name='Sincronizado em')),
            ],
            options={
                'verbose_name': 'Jornada contratada (sincronizada)',
                'verbose_name_plural': 'Jornadas contratadas (sincronizadas)',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='marcacaoponto',
            name='previsto_segundos',
            field=models.PositiveIntegerField(default=0, verbose_name='Previsto (segundos)'),
        ),
        migrations.AddField(
            model_name='saldohoras',
            name='previsto_minutos',
            field=models.IntegerField(default=0, help_text='Jornada contratada no período, descontados feriados, férias e abonos.', verbose_name='Previsto no período (minutos)'),
        ),
        migrations.AddField(
            model_name='saldohoras',
            name='trabalhado_minutos',
            field=models.IntegerField(default=0, help_text='Soma das marcações registradas no período.', verbose_name='Trabalhado no período (minutos)'),
        ),
    ]
