# Generated by Django 5.2.5 on 2026-08-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0008_jornadatrabalho_marcacaoponto_previsto_segundos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldohoras',
            name='analise_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Previsto/trabalhado — fim'),
        ),
        migrations.AddField(
            model_name='saldohoras',
            name='analise_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Previsto/trabalhado — início'),
        ),
    ]
