# Generated by Django 5.2.5 on 2026-08-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0009_saldohoras_analise_fim_saldohoras_analise_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sincronizacaotangerino',
            name='tipo',
            field=models.CharField(choices=[('VINCULO', 'Vínculo de funcionários'), ('PONTO', 'Marcações de ponto'), ('FERIAS', 'Lançamentos de férias'), ('SALDO', 'Saldo de banco de horas'), ('JORNADA', 'Jornadas contratadas')], default='VINCULO', max_length=20),
        ),
    ]
