# Generated by Django 5.2.5 on 2026-08-21 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0010_alter_sincronizacaotangerino_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotangerino',
            name='almoco_maximo_minutos',
            field=models.PositiveSmallIntegerField(default=65, help_text='Acima disso o portal avisa que o almoço passou da hora.', verbose_name='Intervalo considerado longo (minutos)'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='almoco_minimo_minutos',
            field=models.PositiveSmallIntegerField(default=60, help_text='A volta do almoço é recusada antes disso.', verbose_name='Duração mínima do intervalo (minutos)'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='avisar_almoco',
            field=models.BooleanField(default=False, help_text='Popup de almoço esquecido e de intervalo passando do limite.', verbose_name='Avisar sobre o intervalo'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='bloquear_durante_almoco',
            field=models.BooleanField(default=False, help_text='Libera de volta assim que a volta do almoço for registrada.', verbose_name='Bloquear o portal durante o intervalo'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='bloquear_saida_pendente',
            field=models.BooleanField(default=False, help_text='Entrada de um dia anterior sem a saída correspondente.', verbose_name='Bloquear o portal com saída em aberto'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='bloquear_sem_entrada',
            field=models.BooleanField(default=False, help_text='Quem ainda não registrou a entrada só vê a tela de aviso.', verbose_name='Bloquear o portal antes da entrada do dia'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='entrada_manha_ate',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Entrada da manhã — até'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='entrada_manha_de',
            field=models.TimeField(default=datetime.time(7, 0), help_text='O lembrete de almoço só vale para quem entrou nesta faixa.', verbose_name='Entrada da manhã — de'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='lembrete_almoco_hora',
            field=models.TimeField(default=datetime.time(16, 0), help_text='Se não houver saída para o intervalo até esta hora, avisa.', verbose_name='Hora do lembrete de almoço'),
        ),
    ]
