# Generated by Django 5.2.5 on 2026-08-28 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0011_configuracaotangerino_almoco_maximo_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(db_index=True, verbose_name='Início da semana (segunda-feira)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizada por')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['-semana_inicio', 'colaborador__first_name'],
            },
        ),
        migrations.CreateModel(
            name='EscalaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('gestores', models.ManyToManyField(blank=True, help_text='Além do SUPERADMIN, enxergam e editam a escala de todos os setores.', related_name='escala_gestor_de', to=settings.AUTH_USER_MODEL, verbose_name='Gestores globais de escala')),
            ],
            options={
                'verbose_name': 'Configuração de Escala',
                'verbose_name_plural': 'Configuração de Escala',
            },
        ),
        migrations.CreateModel(
            name='EscalaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Dia')),
                ('entrada', models.TimeField(blank=True, null=True, verbose_name='Entrada')),
                ('saida', models.TimeField(blank=True, null=True, verbose_name='Saída')),
                ('folga', models.BooleanField(default=False, verbose_name='Folga')),
                ('observacao', models.CharField(blank=True, default='', max_length=120, verbose_name='Observação')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='tangerino.escala', verbose_name='Escala')),
            ],
            options={
                'verbose_name': 'Dia da escala',
                'verbose_name_plural': 'Dias da escala',
                'ordering': ['data'],
            },
        ),
        migrations.AddConstraint(
            model_name='escala',
            constraint=models.UniqueConstraint(fields=('colaborador', 'semana_inicio'), name='escala_unica_por_pessoa_semana'),
        ),
        migrations.AddConstraint(
            model_name='escaladia',
            constraint=models.UniqueConstraint(fields=('escala', 'data'), name='escala_dia_unico'),
        ),
    ]
