# Generated by Django 5.2.5 on 2026-08-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0012_escala_escalaconfig_escaladia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaladia',
            name='saida_almoco',
            field=models.TimeField(blank=True, null=True, verbose_name='Saída para o almoço'),
        ),
        migrations.AddField(
            model_name='escaladia',
            name='volta_almoco',
            field=models.TimeField(blank=True, null=True, verbose_name='Volta do almoço'),
        ),
    ]
