# Generated by Django 5.2.5 on 2026-09-02 14:27

import datetime
from django.db import migrations, models



def ligar_para_quem_ja_usa(apps, schema_editor):
    """O Vinicius pediu a sincronização das 7h, então a linha que já existe
    nasce ligada. O default do campo continua False para qualquer instalação
    nova — quem quiser, liga na tela."""
    Config = apps.get_model('tangerino', 'ConfiguracaoTangerino')
    Config.objects.filter(pk=1).update(sincronizar_automatico=True)


def desligar(apps, schema_editor):
    Config = apps.get_model('tangerino', 'ConfiguracaoTangerino')
    Config.objects.filter(pk=1).update(sincronizar_automatico=False)


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0013_escaladia_saida_almoco_escaladia_volta_almoco'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotangerino',
            name='dias_sincronizacao',
            field=models.PositiveSmallIntegerField(default=30, help_text='Janela de marcações que a sincronização automática recarrega.', verbose_name='Dias de ponto para trás'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='hora_sincronizacao',
            field=models.TimeField(default=datetime.time(7, 0), help_text='A primeira visita ao portal a partir deste horário dispara.', verbose_name='Hora da sincronização automática'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='sincronizar_automatico',
            field=models.BooleanField(default=False, help_text='Puxa jornadas, marcações, férias e saldo do Tangerino uma vez por dia.', verbose_name='Sincronizar sozinho todo dia'),
        ),
        migrations.AddField(
            model_name='configuracaotangerino',
            name='ultima_sincronizacao_automatica',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização automática'),
        ),
        migrations.RunPython(ligar_para_quem_ja_usa, desligar),
    ]
