# Generated by Django 5.2.5 on 2026-09-23 17:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0014_configuracaotangerino_dias_sincronizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisePontoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, help_text='Desligada, nada é enviado. Ligue só quando os destinatários estiverem certos.', verbose_name='Análise ligada')),
                ('diario', models.BooleanField(default=True, verbose_name='Todo dia (dia anterior)')),
                ('semanal', models.BooleanField(default=True, verbose_name='Toda segunda (semana anterior)')),
                ('mensal', models.BooleanField(default=True, verbose_name='No último dia útil (mês corrente)')),
                ('hora_envio', models.TimeField(default=datetime.time(8, 0), help_text='Depois da sincronização diária: a análise lê o que já foi sincronizado.', verbose_name='Horário do envio')),
                ('somente_com_pendencia', models.BooleanField(default=True, help_text='Desligado, manda mesmo em dia sem nenhuma pendência (o "tudo certo").', verbose_name='Só enviar quando houver divergência')),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True, verbose_name='Última rodada automática')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizada por')),
                ('destinatarios', models.ManyToManyField(blank=True, help_text='Recebem no WhatsApp do cadastro (campo Telefone). Sem telefone, não sai.', related_name='analises_de_ponto', to=settings.AUTH_USER_MODEL, verbose_name='Quem recebe')),
            ],
            options={
                'verbose_name': 'Análise de ponto no WhatsApp',
                'verbose_name_plural': 'Análise de ponto no WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='EnvioAnalisePonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIARIO', 'Diária (dia anterior)'), ('SEMANAL', 'Semanal (semana anterior)'), ('MENSAL', 'Mensal (mês corrente)')], max_length=10, verbose_name='Cadência')),
                ('periodo_inicio', models.DateField(verbose_name='Início do período')),
                ('periodo_fim', models.DateField(verbose_name='Fim do período')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('detalhe', models.CharField(blank=True, max_length=255, verbose_name='Retorno do envio')),
                ('pessoas', models.PositiveIntegerField(default=0, verbose_name='Pessoas com divergência')),
                ('dias', models.PositiveIntegerField(default=0, verbose_name='Dias com divergência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_analise_ponto', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Envio da análise de ponto',
                'verbose_name_plural': 'Envios da análise de ponto',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tipo', 'periodo_fim'), name='tangerino_analise_uma_por_periodo')],
            },
        ),
    ]
