# Generated by Django 5.2.5 on 2026-09-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerino', '0015_analise_de_ponto_no_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoberturaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.BigIntegerField(unique=True, verbose_name='ID no Tangerino')),
                ('desde', models.DateField(verbose_name='Buscado desde')),
                ('ate', models.DateField(verbose_name='Buscado até')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cobertura do ponto',
                'verbose_name_plural': 'Cobertura do ponto',
                'ordering': ['employee_id'],
            },
        ),
    ]
