# Generated by Django 4.2.16 on 2026-05-25 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_da_venda', models.CharField(max_length=60, unique=True, verbose_name='Número da venda')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('cliente', models.CharField(blank=True, max_length=200, verbose_name='Nome do cliente')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('numero_acesso', models.CharField(blank=True, max_length=60, verbose_name='Número de acesso')),
                ('plano', models.CharField(blank=True, max_length=200, verbose_name='Plano / produto')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('pdv', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='PDV')),
                ('vendedor', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Vendedor (nome)')),
                ('data_da_venda', models.DateField(blank=True, null=True, verbose_name='Data da venda')),
                ('pilar', models.CharField(blank=True, max_length=40, verbose_name='Pilar')),
                ('servico_tecnico', models.CharField(blank=True, max_length=80, verbose_name='Serviço Técnico')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('pendente', 'Pendente'), ('problema', 'Vendas com problema'), ('instalado', 'Instalado'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20, verbose_name='Status (Myrella)')),
                ('retorno_myrella', models.TextField(blank=True, verbose_name='Retorno da Myrella')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Primeira sincronização')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='Última sincronização')),
            ],
            options={
                'verbose_name': 'Fibra',
                'verbose_name_plural': 'Fibras',
                'ordering': ['-data_da_venda', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FibraChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('fibra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='fibras.fibra')),
            ],
            options={
                'verbose_name': 'Chat (Fibra)',
                'verbose_name_plural': 'Chats (Fibra)',
            },
        ),
        migrations.CreateModel(
            name='FibraStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('retorno', models.TextField(blank=True)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fibra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='fibras.fibra')),
            ],
            options={
                'verbose_name': 'Histórico de status (Fibra)',
                'verbose_name_plural': 'Históricos de status (Fibra)',
                'ordering': ['-alterado_em'],
            },
        ),
        migrations.CreateModel(
            name='FibraIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(verbose_name='Observação do CN')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_tratativa', 'Em tratativa'), ('resolvido', 'Resolvido')], default='aberto', max_length=20)),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta da Ilha')),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aberto_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fibra_incidentes_abertos', to=settings.AUTH_USER_MODEL)),
                ('fibra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='fibras.fibra')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente de Fibra',
                'verbose_name_plural': 'Incidentes de Fibra',
                'ordering': ['-aberto_em'],
            },
        ),
        migrations.CreateModel(
            name='FibraChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='fibras.fibrachat')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='fibra',
            index=models.Index(fields=['status'], name='fibras_fibr_status_ebc771_idx'),
        ),
        migrations.AddIndex(
            model_name='fibra',
            index=models.Index(fields=['data_da_venda'], name='fibras_fibr_data_da_ac7ef6_idx'),
        ),
    ]
