# Generated by Django 5.2.5 on 2026-05-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibras', '0001_initial'),
        ('projects', '0012_alter_projectattachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibra',
            name='last_planilha_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última atualização via planilha'),
        ),
        migrations.AddField(
            model_name='fibra',
            name='numero_protocolo',
            field=models.CharField(blank=True, db_index=True, help_text='Usado para casar com a planilha diária (coluna Nº_protocolo).', max_length=60, verbose_name='Nº do protocolo'),
        ),
        migrations.AddField(
            model_name='fibra',
            name='ordem_planilha',
            field=models.IntegerField(blank=True, db_index=True, help_text='Posição na planilha do último import. Define a ordem visual no Kanban.', null=True, verbose_name='Ordem (planilha)'),
        ),
        migrations.AddField(
            model_name='fibra',
            name='status_planilha_raw',
            field=models.CharField(blank=True, help_text='Texto original da coluna de status da planilha (auditoria).', max_length=120, verbose_name='Status bruto da planilha'),
        ),
        migrations.AddField(
            model_name='fibraincidente',
            name='last_opener_view_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fibraincidente',
            name='support_chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fibra_incidente', to='projects.supportchat'),
        ),
    ]
