# Generated by Django 5.2.5 on 2026-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibras', '0002_fibra_last_planilha_at_fibra_numero_protocolo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaOrdemInconsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status_raw', models.CharField(blank=True, max_length=120)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('occurrences', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Ordem inconsistente (planilha)',
                'verbose_name_plural': 'Ordens inconsistentes (planilha)',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
