# Generated by Django 5.2.5 on 2026-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibras', '0003_planilhaordeminconsistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibra',
            name='motivo_planilha',
            field=models.CharField(blank=True, help_text='Valor da coluna MOTIVO na última importação (vendas com problema).', max_length=255, verbose_name='Motivo (planilha)'),
        ),
        migrations.AddField(
            model_name='fibra',
            name='sla_agenda',
            field=models.CharField(blank=True, help_text='Valor da coluna SLA AGENDA na última importação.', max_length=120, verbose_name='SLA Agenda (planilha)'),
        ),
    ]
