# Generated by Django 5.2.5 on 2026-08-20 06:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0032_user_tangerino_employee_id_user_tangerino_synced_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_index=True, max_length=60, verbose_name='Categoria (aba)')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('plano', models.CharField(blank=True, max_length=200, verbose_name='Plano')),
                ('sistema', models.CharField(blank=True, max_length=60, verbose_name='Sistema')),
                ('grupamento', models.CharField(blank=True, max_length=120, verbose_name='Grupamento')),
                ('cod_sap', models.CharField(blank=True, max_length=40, verbose_name='Cód. SAP')),
                ('cod_sistema', models.CharField(blank=True, max_length=40, verbose_name='Cód. Sistema')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor (R$)')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Outros campos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('importado_em', models.DateTimeField(blank=True, null=True, verbose_name='Importado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item da Tabela de Preços',
                'verbose_name_plural': 'Tabela de Preços',
                'ordering': ['categoria', 'nome'],
                'indexes': [models.Index(fields=['categoria', 'nome'], name='vendas_item_categor_5c0ba6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdv_nome', models.CharField(blank=True, max_length=120, verbose_name='PDV (texto)')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('estoque_avancado', models.BooleanField(default=False, verbose_name='Venda Estoque Avançado?')),
                ('cliente_nome', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('cliente_cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ do cliente')),
                ('tipo_venda', models.CharField(blank=True, max_length=80, verbose_name='Tipo de Venda')),
                ('comprovante_fiscal', models.CharField(choices=[('NFCE', 'NFC-e (Cupom Fiscal)'), ('NFE', 'NF-e (DANFE)')], default='NFCE', max_length=8, verbose_name='Comprovante Fiscal')),
                ('data_venda', models.DateTimeField(verbose_name='Data da venda')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_lancadas', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='users.sector', verbose_name='Loja / PDV')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produto', models.CharField(blank=True, max_length=120, verbose_name='Tipo de Produto')),
                ('categoria', models.CharField(blank=True, max_length=120, verbose_name='Categoria')),
                ('subcategoria', models.CharField(blank=True, max_length=120, verbose_name='Subcategoria')),
                ('nome_produto', models.CharField(max_length=200, verbose_name='Produto')),
                ('marca', models.CharField(blank=True, max_length=80, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=200, verbose_name='Modelo')),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='SKU')),
                ('serial', models.CharField(blank=True, max_length=120, verbose_name='Serial')),
                ('cor', models.CharField(blank=True, max_length=60, verbose_name='Cor')),
                ('qtde', models.PositiveIntegerField(default=1, verbose_name='Qtde')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo')),
                ('valor_venda', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor de Venda')),
                ('plano', models.CharField(blank=True, max_length=200, verbose_name='Plano')),
                ('tabela_preco', models.CharField(blank=True, max_length=120, verbose_name='Tabela de preço')),
                ('pilar', models.CharField(blank=True, max_length=40, verbose_name='Pilar')),
                ('preco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendas.itempreco', verbose_name='Item da tabela de preços')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Produto da Venda',
                'verbose_name_plural': 'Produtos da Venda',
            },
        ),
        migrations.CreateModel(
            name='VendaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=200, verbose_name='Serviço')),
                ('servico_tecnico', models.CharField(blank=True, max_length=200, verbose_name='Serviço Técnico')),
                ('tipo_plano', models.CharField(blank=True, max_length=120, verbose_name='Tipo do Plano')),
                ('plano_novo', models.CharField(blank=True, max_length=200, verbose_name='Plano')),
                ('grupamento', models.CharField(blank=True, max_length=120, verbose_name='Grupamento')),
                ('numero_acesso', models.CharField(blank=True, max_length=40, verbose_name='Nº de Acesso')),
                ('valor_plano', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor do Plano')),
                ('receita', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Receita')),
                ('status_servico', models.CharField(blank=True, max_length=60, verbose_name='Status do Serviço')),
                ('pilar', models.CharField(blank=True, max_length=40, verbose_name='Pilar')),
                ('preco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendas.itempreco', verbose_name='Item da tabela de preços')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Serviço da Venda',
                'verbose_name_plural': 'Serviços da Venda',
            },
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['data_venda'], name='vendas_vend_data_ve_933af3_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['loja'], name='vendas_vend_loja_id_5aa02e_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['vendedor'], name='vendas_vend_vendedo_089760_idx'),
        ),
    ]
