# Generated by Django 5.2.5 on 2026-10-09 14:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do plano')),
                ('segmentacao', models.CharField(choices=[('POS', 'Pós'), ('CONTROLE', 'Controle'), ('PRE', 'Pré'), ('EMPRESAS', 'Vivo Empresas')], db_index=True, max_length=10, verbose_name='Segmentação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor mensal (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano (SLV)',
                'verbose_name_plural': 'Planos (SLV)',
                'ordering': ['segmentacao', 'valor', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ServicoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEGURO', 'Seguro'), ('SVA', 'SVA')], max_length=10, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Seguro / SVA',
                'verbose_name_plural': 'Seguros e SVAs',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_telefone',
            field=models.CharField(blank=True, db_default='', default='', max_length=20, verbose_name='Telefone do cliente'),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('CARTAO', 'Cartão'), ('PIX', 'Pix')], db_default='', default='', max_length=10, verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='numero_fake',
            field=models.BooleanField(db_default=False, db_index=True, default=False, verbose_name='Tem número fictício'),
        ),
        migrations.AddField(
            model_name='venda',
            name='plano_anterior_nome',
            field=models.CharField(blank=True, db_default='', default='', max_length=200, verbose_name='Plano anterior'),
        ),
        migrations.AddField(
            model_name='venda',
            name='segmentacao_anterior',
            field=models.CharField(blank=True, db_default='', default='', max_length=10, verbose_name='Segmentação anterior'),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor que o cliente pagava'),
        ),
        migrations.AddField(
            model_name='venda',
            name='vivo_mais',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Pago pelo Vivo+'),
        ),
        migrations.AddField(
            model_name='venda',
            name='vivo_mais_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual Vivo+ (na época)'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='categoria_slv',
            field=models.CharField(blank=True, db_default='', default='', max_length=12, verbose_name='Categoria (aparelho/eletrônico/essencial)'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='desconto_vivo_mais',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Desconto Vivo+'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Valor editado por'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='prateleira_infinita',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Prateleira infinita'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='regra_preco',
            field=models.CharField(blank=True, db_default='', default='', max_length=120, verbose_name='Regra do preço'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='renova_alied',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Renova Alied'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='renova_alied_valor',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor Renova Alied'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='renova_codigo',
            field=models.CharField(blank=True, db_default='', default='', max_length=20, verbose_name='Código do Renova'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='renova_vini',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Renova Vini'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='renova_vini_valor',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor Renova Vini'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='valor_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor calculado pelo sistema'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='valor_editado',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Valor final editado à mão'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='valor_sugerido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor sugerido (tabela)'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='ativacao_confirmada',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Ativação confirmada'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='delta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Delta'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='linhas',
            field=models.JSONField(blank=True, db_default=[], default=list, verbose_name='Linhas do cliente'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='novo_titular_cpf',
            field=models.CharField(blank=True, db_default='', default='', max_length=11, verbose_name='CPF do novo titular'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='novo_titular_nome',
            field=models.CharField(blank=True, db_default='', default='', max_length=200, verbose_name='Novo titular'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='numero_anterior',
            field=models.CharField(blank=True, db_default='', default='', max_length=20, verbose_name='Número anterior'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='numero_fake',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Número fictício'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='numero_novo',
            field=models.CharField(blank=True, db_default='', default='', max_length=20, verbose_name='Número novo'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='plano_anterior_nome',
            field=models.CharField(blank=True, db_default='', default='', max_length=200, verbose_name='Plano anterior (texto)'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='segmentacao',
            field=models.CharField(blank=True, db_default='', default='', max_length=10, verbose_name='Segmentação'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='serial_simcard',
            field=models.CharField(blank=True, db_default='', default='', max_length=30, verbose_name='Serial do SimCard'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='tipo_servico',
            field=models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('REATIVACAO', 'Reativação'), ('TROCA_PLANO', 'Troca de plano'), ('TROCA_SIMCARD', 'Troca de SimCard'), ('MIGRACAO', 'Migração'), ('SEGURO', 'Seguro'), ('SVA', 'SVA'), ('TROCA_TITULARIDADE', 'Troca de titularidade'), ('TROCA_NUMERO', 'Troca de número')], db_default='', db_index=True, default='', max_length=20, verbose_name='Tipo de serviço'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='valor_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor anterior'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('plano_nome', models.CharField(blank=True, max_length=200, verbose_name='Plano atual (texto)')),
                ('segmentacao', models.CharField(blank=True, max_length=10, verbose_name='Segmentação')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor pago')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendas.plano', verbose_name='Plano atual')),
            ],
            options={
                'verbose_name': 'Cliente (SLV)',
                'verbose_name_plural': 'Clientes (SLV)',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='vendas.cliente', verbose_name='Cliente (cadastro)'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vivo_mais_percentual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Desconto Vivo+ (%)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de vendas',
                'verbose_name_plural': 'Configuração de vendas',
            },
        ),
        migrations.CreateModel(
            name='ImportacaoPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(choices=[('manual', 'Envio manual'), ('email', 'E-mail')], default='manual', max_length=10)),
                ('arquivo', models.CharField(blank=True, max_length=255)),
                ('incluidos', models.PositiveIntegerField(default=0)),
                ('alterados', models.PositiveIntegerField(default=0)),
                ('sem_mudanca', models.PositiveIntegerField(default=0)),
                ('rejeitados', models.JSONField(blank=True, default=list)),
                ('erro', models.TextField(blank=True, help_text='Se a importação falhou, a tabela vigente ficou como estava.')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação da tabela de produtos',
                'verbose_name_plural': 'Importações da tabela de produtos',
                'ordering': ['-quando'],
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='plano_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendas.plano', verbose_name='Plano anterior do cliente'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendas.plano', verbose_name='Plano novo'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='plano_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendas.plano', verbose_name='Plano anterior'),
        ),
        migrations.CreateModel(
            name='RegistroAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLANO', 'Plano'), ('VIVO_MAIS', 'Percentual Vivo+'), ('CLIENTE', 'Cliente'), ('SERVICO_ADICIONAL', 'Seguro / SVA')], db_index=True, max_length=20, verbose_name='O que mudou')),
                ('objeto_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('objeto_rotulo', models.CharField(blank=True, max_length=200, verbose_name='Registro')),
                ('campo', models.CharField(max_length=40, verbose_name='Campo')),
                ('rotulo', models.CharField(max_length=80, verbose_name='Campo (rótulo)')),
                ('antes', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('depois', models.TextField(blank=True, verbose_name='Valor novo')),
                ('usuario_nome', models.CharField(blank=True, max_length=200)),
                ('pdv', models.CharField(blank=True, max_length=120, verbose_name='PDV')),
                ('quando', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de alteração (SLV)',
                'verbose_name_plural': 'Histórico de alterações (SLV)',
                'ordering': ['-quando', '-id'],
            },
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='servico_adicional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendas.servicoadicional', verbose_name='Seguro / SVA'),
        ),
    ]
