# Generated by Django 5.2.5 on 2026-10-09 15:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_slv'),
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacaoVivoGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.DateTimeField(blank=True, null=True, verbose_name='Maior DATA_INSERCAO_VENDA já lida')),
                ('ultima_incremental', models.DateTimeField(blank=True, null=True)),
                ('ultima_completa', models.DateTimeField(blank=True, null=True)),
                ('em_andamento_desde', models.DateTimeField(blank=True, null=True)),
                ('ultimo_resumo', models.CharField(blank=True, max_length=255)),
                ('ultimo_erro', models.CharField(blank=True, max_length=500)),
                ('ultimo_erro_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sincronização do Vivo GO',
                'verbose_name_plural': 'Sincronização do Vivo GO',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='linha',
            field=models.CharField(blank=True, db_default='', default='', max_length=20, verbose_name='Última linha (Vivo GO)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origem',
            field=models.CharField(choices=[('PORTAL', 'Cadastrado no portal'), ('VIVOGO', 'Base do Vivo GO')], db_default='PORTAL', db_index=True, default='PORTAL', max_length=8),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pdv_ultimo',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=80, verbose_name='Último PDV'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='plano_vivogo',
            field=models.CharField(blank=True, db_default='', default='', max_length=200, verbose_name='Último plano (Vivo GO)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='primeira_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Primeira compra'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='qtd_vendas',
            field=models.PositiveIntegerField(db_default=0, default=0, verbose_name='Vendas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resumo do Vivo GO em'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_gasto',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Receita total'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_compra',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Última compra'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor_ultimo',
            field=models.CharField(blank=True, db_default='', default='', max_length=200, verbose_name='Último vendedor'),
        ),
        migrations.CreateModel(
            name='CompraVivoGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=48, unique=True)),
                ('tipo', models.CharField(choices=[('P', 'Produto'), ('S', 'Serviço')], db_index=True, max_length=1)),
                ('id_venda', models.CharField(blank=True, db_index=True, max_length=30)),
                ('data_venda', models.DateField(blank=True, db_index=True, null=True)),
                ('data_insercao', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=14, verbose_name='CPF/CNPJ do cliente')),
                ('nome_cliente', models.CharField(blank=True, max_length=200)),
                ('numero_acesso', models.CharField(blank=True, max_length=20)),
                ('pdv', models.CharField(blank=True, db_index=True, max_length=80)),
                ('coordenacao', models.CharField(blank=True, max_length=80)),
                ('vendedor', models.CharField(blank=True, max_length=200)),
                ('item', models.CharField(blank=True, max_length=255, verbose_name='Produto / serviço')),
                ('plano', models.CharField(blank=True, max_length=200)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('subcategoria', models.CharField(blank=True, max_length=120)),
                ('tipo_produto', models.CharField(blank=True, max_length=120)),
                ('qtd', models.IntegerField(default=1)),
                ('receita', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pilar', models.CharField(blank=True, max_length=60)),
                ('status_servico', models.CharField(blank=True, max_length=60)),
                ('data_cancelamento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compra (Vivo GO)',
                'verbose_name_plural': 'Compras (Vivo GO)',
                'ordering': ['-data_venda', '-id'],
                'indexes': [models.Index(fields=['cpf', 'data_venda'], name='vendas_comp_cpf_3240b2_idx')],
            },
        ),
    ]
