# Generated by Django 5.2.5 on 2026-10-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_clientes_vivogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaoprecos',
            name='removidos',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Saíram da tabela (apagados ou inativados).'),
        ),
    ]
