# Generated by Django 5.2.5 on 2026-10-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_importacao_removidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='segmentacao',
            field=models.CharField(choices=[('POS', 'Pós'), ('CONTROLE', 'Controle'), ('PRE', 'Pré'), ('EMPRESAS', 'Vivo Empresas'), ('FIBRA', 'Fibra e TV')], db_index=True, max_length=10, verbose_name='Segmentação'),
        ),
    ]
