# Generated by Django 5.2.5 on 2026-03-05 19:56

import django.db.models.deletion
import experiencia.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_add_hr_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaEvaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sectors', models.ManyToManyField(blank=True, related_name='experiencia_evaluators', to='users.sector', verbose_name='Setores que avalia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_evaluator_roles', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
            ],
            options={
                'verbose_name': 'Avaliador',
                'verbose_name_plural': 'Avaliadores',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Experiência',
                'verbose_name_plural': 'Templates de Experiência',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Pergunta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Pontos')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='experiencia.experienciatemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Mês')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado Parcialmente'), ('finalizado', 'Finalizado')], default='aberto', max_length=20, verbose_name='Status')),
                ('evaluation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Avaliação')),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pontuação (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiencia_todos_evaluated', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
                ('launched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_todos_launched', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_todos', to='users.sector', verbose_name='Setor')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiencia_todos_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='experiencia.experienciatemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'To-Do Experiência',
                'verbose_name_plural': 'To-Dos Experiência',
                'ordering': ['-year', '-month', 'sector__name'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, verbose_name='Observação/Resposta')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=experiencia.models.upload_experiencia_photo, verbose_name='Foto')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Recusa')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiencia_answers', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='experiencia.experienciaquestion', verbose_name='Pergunta')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='experiencia.experienciatodo', verbose_name='To-Do')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['question__order', 'question__id'],
            },
        ),
        migrations.AddConstraint(
            model_name='experienciatodo',
            constraint=models.UniqueConstraint(fields=('sector', 'month', 'year', 'template'), name='unique_todo_per_sector_month_template'),
        ),
        migrations.AddConstraint(
            model_name='experienciaanswer',
            constraint=models.UniqueConstraint(fields=('todo', 'question'), name='unique_answer_per_question'),
        ),
    ]
