# Generated by Django 5.2.5 on 2026-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaanswer',
            name='response',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_se_aplica', 'Não se aplica')], default='nao', max_length=20, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='experienciaanswer',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
