# Generated by Django 5.2.5 on 2026-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0002_experienciaanswer_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaquestion',
            name='contestavel',
            field=models.BooleanField(default=True, verbose_name='Contestável?'),
        ),
        migrations.AddField(
            model_name='experienciaquestion',
            name='detalhamento',
            field=models.TextField(blank=True, verbose_name='Detalhamento'),
        ),
        migrations.AddField(
            model_name='experienciaquestion',
            name='gravidade',
            field=models.CharField(blank=True, choices=[('leve', 'Leve'), ('media', 'Média'), ('grave', 'Grave'), ('inegociavel', 'Inegociável')], max_length=20, verbose_name='Gravidade'),
        ),
        migrations.AddField(
            model_name='experienciaquestion',
            name='item',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='experienciaquestion',
            name='pilar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pilar'),
        ),
    ]
