# Generated by Django 5.2.5 on 2026-03-10 17:24

import django.db.models.deletion
import experiencia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0003_experienciaquestion_contestavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaAnswerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=experiencia.models.upload_experiencia_photo, verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='experiencia.experienciaanswer', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Foto da Resposta',
                'verbose_name_plural': 'Fotos das Respostas',
                'ordering': ['created_at'],
            },
        ),
    ]
