# Generated by Django 5.2.5 on 2026-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0004_experienciaanswerphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaanswer',
            name='ticket_number',
            field=models.CharField(blank=True, help_text='Preenchido quando a resposta é "Não".', max_length=50, verbose_name='Número do Chamado'),
        ),
    ]
