# Generated by Django 5.2.5 on 2025-08-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito'), ('REDEMPTION', 'Resgate'), ('ADJUSTMENT', 'Ajuste')], max_length=15, verbose_name='Tipo')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Transação C$',
                'verbose_name_plural': 'Transações C$',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('value_cs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor em C$')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prizes/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('unlimited_stock', models.BooleanField(default=False, verbose_name='Estoque Ilimitado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prêmio',
                'verbose_name_plural': 'Prêmios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Resgate')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Aprovação')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Entrega')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Resgate',
                'verbose_name_plural': 'Resgates',
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
