# Generated by Django 5.2.5 on 2025-09-02 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(default='fas fa-gift', max_length=50, verbose_name='Ícone Font Awesome')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='Cor')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Prêmio',
                'verbose_name_plural': 'Categorias de Prêmios',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Prêmio', 'verbose_name_plural': 'Prêmios'},
        ),
        migrations.AddField(
            model_name='prize',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='prize',
            name='priority',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('DESTAQUE', 'Destaque')], default='NORMAL', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='prize',
            name='redeemed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade Resgatada'),
        ),
        migrations.AddField(
            model_name='prize',
            name='terms',
            field=models.TextField(blank=True, verbose_name='Termos e Condições'),
        ),
        migrations.AddField(
            model_name='prize',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Válido até'),
        ),
        migrations.AddField(
            model_name='prize',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prizes.prizecategory', verbose_name='Categoria'),
        ),
    ]
