# Generated by Django 5.2.5 on 2025-09-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0003_prizecategory_alter_prize_options_prize_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='Observações de Entrega'),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
    ]
