# Generated by Django 5.2.5 on 2025-09-07 06:35

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0005_cstransaction_approved_at_cstransaction_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_prize_image, verbose_name='Imagem'),
        ),
    ]
