# Generated by Django 5.2.5 on 2025-09-12 18:20

import core.storage
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0006_alter_prize_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=core.utils.upload_prize_image, verbose_name='Imagem'),
        ),
    ]
