# Generated by Django 5.2.5 on 2025-09-15 21:37

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0007_alter_prize_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito'), ('REDEMPTION', 'Resgate'), ('REFUND', 'Reembolso'), ('ADJUSTMENT', 'Ajuste')], max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_prize_image, verbose_name='Imagem'),
        ),
    ]
