# Generated by Django 5.2.5 on 2025-09-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0008_alter_cstransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cstransaction',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo da Rejeição'),
        ),
    ]
