# Generated by Django 5.2.7 on 2025-10-14 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0009_cstransaction_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Desconto'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='original_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Original'),
        ),
        migrations.CreateModel(
            name='PrizeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Desconto')),
                ('code', models.CharField(help_text='Código único para o desconto', max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentagem'), ('FIXED', 'Valor Fixo')], default='PERCENTAGE', max_length=20, verbose_name='Tipo de Desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentagem (ex: 10 para 10%) ou valor fixo em C$', max_digits=10, verbose_name='Valor do Desconto')),
                ('min_purchase_value', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo em C$ para aplicar o desconto', max_digits=10, verbose_name='Valor Mínimo de Compra')),
                ('max_discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo de desconto em C$ (apenas para porcentagem)', max_digits=10, null=True, verbose_name='Desconto Máximo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valid_from', models.DateField(verbose_name='Válido de')),
                ('valid_until', models.DateField(verbose_name='Válido até')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Número máximo de vezes que pode ser usado (deixe vazio para ilimitado)', null=True, verbose_name='Máximo de Usos')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Usos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_categories', models.ManyToManyField(blank=True, help_text='Deixe vazio para aplicar a todos os prêmios', to='prizes.prizecategory', verbose_name='Categorias Aplicáveis')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Desconto',
                'verbose_name_plural': 'Descontos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='redemption',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prizes.prizediscount', verbose_name='Desconto Aplicado'),
        ),
    ]
