# Generated by Django 5.2.7 on 2025-10-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0010_redemption_discount_value_redemption_final_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentagem de desconto (ex: 10 para 10%)', max_digits=5, null=True, verbose_name='Desconto (%)'),
        ),
        migrations.AddField(
            model_name='prize',
            name='discounted_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor final após aplicar o desconto', max_digits=10, null=True, verbose_name='Valor com Desconto'),
        ),
        migrations.AddField(
            model_name='prize',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='Tem Desconto'),
        ),
    ]
