# Generated by Django 5.2.5 on 2026-01-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0011_prize_discount_percentage_prize_discounted_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cstransaction',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Data em que as confianças irão expirar. Deixe em branco para não expirar.', null=True, verbose_name='Data de Validade'),
        ),
        migrations.AddField(
            model_name='cstransaction',
            name='expiration_notified_1_day',
            field=models.BooleanField(default=False, verbose_name='Notificado 1 dia antes'),
        ),
        migrations.AddField(
            model_name='cstransaction',
            name='expiration_notified_3_days',
            field=models.BooleanField(default=False, verbose_name='Notificado 3 dias antes'),
        ),
        migrations.AddField(
            model_name='cstransaction',
            name='expiration_notified_7_days',
            field=models.BooleanField(default=False, verbose_name='Notificado 7 dias antes'),
        ),
    ]
