# Generated by Django 5.2.5 on 2026-07-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0012_add_cs_expiration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='pickup_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Data Limite para Retirada'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='pickup_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notificado para Retirada em'),
        ),
    ]
