# Generated by Django 5.2.5 on 2026-09-14 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistenteConexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_cifrada', models.TextField(blank=True, default='', verbose_name='Chave (cifrada)')),
                ('key_hint', models.CharField(blank=True, default='', max_length=12, verbose_name='Final da chave')),
                ('modelo', models.CharField(choices=[('claude-sonnet-5', 'Claude Sonnet 5 — equilíbrio (recomendado)'), ('claude-opus-5', 'Claude Opus 5 — mais capaz'), ('claude-haiku-4-5-20251001', 'Claude Haiku 4.5 — rápido e econômico')], default='claude-sonnet-5', max_length=40)),
                ('conectado_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_ok_em', models.DateTimeField(blank=True, null=True, verbose_name='Último teste OK')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistente_conexao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão do Assistente',
                'verbose_name_plural': 'Conexões do Assistente',
            },
        ),
        migrations.CreateModel(
            name='AssistenteMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=12)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistente_mensagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem do Assistente',
                'verbose_name_plural': 'Mensagens do Assistente',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['user', 'criado_em'], name='assistente__user_id_2607e3_idx')],
            },
        ),
    ]
