# Generated by Django 5.2.5 on 2026-07-27 16:30

import core.storage
import django.db.models.deletion
import impulso.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoConectar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CURSO', 'Curso'), ('VIDEO', 'Vídeo'), ('POP', 'POP')], max_length=6, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(blank=True, help_text='Vídeo, PDF do POP ou material do curso (opcional).', null=True, storage=core.storage.MediaStorage, upload_to=impulso.models.upload_conteudo, verbose_name='Arquivo')),
                ('url', models.URLField(blank=True, help_text='Link do curso/vídeo (opcional).', verbose_name='Link externo')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Início do período')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Fim do período')),
                ('criado_por_equipe', models.BooleanField(default=False, help_text='POP enviado por um membro da equipe (não gestor).', verbose_name='Enviado pela equipe')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_conteudos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('obrigatorio_para', models.ManyToManyField(blank=True, help_text='Se vazio, vale para toda a equipe do Escritório (ADM).', related_name='impulso_conteudos_obrigatorios', to=settings.AUTH_USER_MODEL, verbose_name='Obrigatório para')),
            ],
            options={
                'verbose_name': 'Conteúdo CONECTAR',
                'verbose_name_plural': 'Conteúdos CONECTAR',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Informe de forma concreta a sua ideia.', verbose_name='Qual é a sua ideia?')),
                ('setor_impacto', models.CharField(max_length=150, verbose_name='Setor de impacto')),
                ('motivo', models.TextField(verbose_name='Qual o motivo?')),
                ('status', models.CharField(choices=[('NOVA', 'Nova'), ('EM_ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('ARQUIVADA', 'Arquivada')], default='NOVA', max_length=12, verbose_name='Status')),
                ('resposta_gestor', models.TextField(blank=True, verbose_name='Retorno do gestor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulso_ideias', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Ideia',
                'verbose_name_plural': 'Ideias',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImpulsoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_mes', models.DateField(help_text='Primeiro dia do mês de referência do feedback.', verbose_name='Mês de referência')),
                ('pontos_fortes', models.TextField(verbose_name='Pontos fortes')),
                ('pontos_melhoria', models.TextField(verbose_name='Pontos a melhorar')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário geral')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Resumo IA')),
                ('ai_summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary_error', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulso_feedbacks_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulso_feedbacks_dados', to=settings.AUTH_USER_MODEL, verbose_name='Gestor')),
            ],
            options={
                'verbose_name': 'Feedback (Impulso)',
                'verbose_name_plural': 'Feedbacks (Impulso)',
                'ordering': ['-referencia_mes', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da meta')),
                ('descricao', models.TextField(help_text='Descreva a meta de forma clara, por textos.', verbose_name='Descrição')),
                ('periodicidade', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='MENSAL', max_length=12, verbose_name='Periodicidade')),
                ('prazo', models.DateField(verbose_name='Prazo')),
                ('status', models.CharField(choices=[('A_FAZER', 'A Fazer'), ('EM_ANDAMENTO', 'Em Andamento'), ('ENTREGUE', 'Entregue (aguardando avaliação)'), ('CONCLUIDA', 'Concluída')], default='A_FAZER', max_length=14, verbose_name='Status')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem no Kanban')),
                ('entrega_link', models.URLField(blank=True, help_text='Link da tarefa ou projeto entregue (opcional).', verbose_name='Link da entrega')),
                ('entregue_em', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('nota_qualidade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Qualidade de entrega (0-5)')),
                ('nota_prazo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cumprimento de prazo (0-5)')),
                ('avaliacao_comentario', models.TextField(blank=True, verbose_name='Comentário do gestor')),
                ('avaliado_em', models.DateTimeField(blank=True, null=True, verbose_name='Avaliado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_metas_avaliadas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulso_metas', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_metas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulso_metas_gerenciadas', to=settings.AUTH_USER_MODEL, verbose_name='Gestor')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ARQUIVO', 'Arquivo'), ('LINK', 'Link')], max_length=8, verbose_name='Tipo')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('arquivo', models.FileField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=impulso.models.upload_meta_anexo, verbose_name='Arquivo')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_anexos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='impulso.meta', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Anexo de Meta',
                'verbose_name_plural': 'Anexos de Metas',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='MetaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulso_comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='impulso.meta', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Comentário de Meta',
                'verbose_name_plural': 'Comentários de Metas',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoFoco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_projetos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('membros', models.ManyToManyField(blank=True, related_name='impulso_projetos_foco', to=settings.AUTH_USER_MODEL, verbose_name='Equipe do projeto')),
            ],
            options={
                'verbose_name': 'Projeto Foco',
                'verbose_name_plural': 'Projetos Foco',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TarefaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('status', models.CharField(choices=[('A_FAZER', 'A Fazer'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='A_FAZER', max_length=14, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='impulso.projetofoco', verbose_name='Projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_tarefas_projeto', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa de Projeto Foco',
                'verbose_name_plural': 'Tarefas de Projeto Foco',
                'ordering': ['prazo', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConclusaoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('certificado', models.FileField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=impulso.models.upload_certificado, verbose_name='Certificado')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulso_conclusoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='impulso.conteudoconectar', verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Conclusão de Conteúdo',
                'verbose_name_plural': 'Conclusões de Conteúdo',
                'ordering': ['-concluido_em'],
                'unique_together': {('conteudo', 'user')},
            },
        ),
    ]
