# Generated by Django 5.2.5 on 2026-07-29 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0001_initial'),
        ('users', '0027_user_vacation_end_date_user_vacation_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='periodicidade',
            field=models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='MENSAL', max_length=12, verbose_name='Periodicidade'),
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do ciclo')),
                ('inicio', models.DateField(verbose_name='Início')),
                ('fim', models.DateField(verbose_name='Fim')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('encerrado_em', models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em')),
                ('confiancas_creditadas', models.BooleanField(default=False, verbose_name='Confianças já creditadas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_ciclos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('encerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_ciclos_encerrados', to=settings.AUTH_USER_MODEL, verbose_name='Encerrado por')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='CicloMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateField(help_text='Primeiro dia do mês de referência.', verbose_name='Mês de referência')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('fechado_em', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meses', to='impulso.ciclo', verbose_name='Ciclo')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_meses_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
            ],
            options={
                'verbose_name': 'Mês do Ciclo',
                'verbose_name_plural': 'Meses do Ciclo',
                'ordering': ['referencia'],
                'unique_together': {('ciclo', 'referencia')},
            },
        ),
        migrations.CreateModel(
            name='PontuacaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_metas_qualidade', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Metas — qualidade (0-10)')),
                ('p_metas_conclusao', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Metas — conclusão (0-10)')),
                ('p_feedback', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Feedback (0-10)')),
                ('p_assiduidade', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Assiduidade (0-10)')),
                ('p_curso', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Curso do mês (0-10)')),
                ('p_videos_pops', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Vídeos e POPs (0-10)')),
                ('p_projeto_foco', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Projeto foco (0-20)')),
                ('p_ideias', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ideias propostas (0-10)')),
                ('p_ideia_aprovada', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ideia aprovada (0-10)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total (0-100)')),
                ('pontos_aplicaveis', models.DecimalField(decimal_places=2, default=100, help_text='Máximo possível no mês (itens sem nada configurado não contam).', max_digits=6, verbose_name='Pontos aplicáveis')),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Percentual (%)')),
                ('faixa', models.CharField(choices=[('IMPULSO', 'Impulso'), ('OURO', 'Ouro'), ('PRATA', 'Prata'), ('BRONZE', 'Bronze')], default='BRONZE', max_length=10, verbose_name='Faixa')),
                ('confiancas_previstas', models.PositiveIntegerField(default=0, help_text='Creditadas ao encerrar o ciclo (Ouro e Impulso).', verbose_name='Confianças previstas')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes do cálculo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='impulso.ciclomes', verbose_name='Mês')),
                ('setor', models.ForeignKey(blank=True, help_text='Setor do colaborador no momento do fechamento (para o Setor Destaque).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_pontuacoes', to='users.sector', verbose_name='Setor principal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulso_pontuacoes', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Pontuação Mensal',
                'verbose_name_plural': 'Pontuações Mensais',
                'ordering': ['-total'],
                'unique_together': {('mes', 'user')},
            },
        ),
    ]
