# Generated by Django 5.2.5 on 2026-08-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0003_recorrencia_e_aprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclusaoconteudo',
            name='video_assistido_ate',
            field=models.FloatField(default=0, help_text='Maior ponto do vídeo alcançado sem pular à frente.', verbose_name='Assistido até (segundos)'),
        ),
        migrations.AddField(
            model_name='conclusaoconteudo',
            name='video_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último aviso de progresso'),
        ),
        migrations.AddField(
            model_name='conclusaoconteudo',
            name='video_concluido',
            field=models.BooleanField(default=False, verbose_name='Vídeo assistido até o fim'),
        ),
        migrations.AddField(
            model_name='conclusaoconteudo',
            name='video_duracao',
            field=models.FloatField(default=0, verbose_name='Duração do vídeo (segundos)'),
        ),
    ]
