# Generated by Django 5.2.5 on 2026-08-19 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0004_conclusaoconteudo_video_assistido_ate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='impulso_metas_participando', to=settings.AUTH_USER_MODEL, verbose_name='Outros responsáveis'),
        ),
        migrations.CreateModel(
            name='MetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='O que fazer')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_itens_concluidos', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_itens_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='impulso.meta', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Item da meta',
                'verbose_name_plural': 'Itens da meta',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MetaVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto_em', models.DateTimeField(auto_now=True, verbose_name='Visto em')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='impulso.meta', verbose_name='Meta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulso_metas_vistas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Visualização de meta',
                'verbose_name_plural': 'Visualizações de metas',
                'constraints': [models.UniqueConstraint(fields=('meta', 'user'), name='impulso_meta_vista_unica')],
            },
        ),
    ]
