# Generated by Django 5.2.5 on 2026-08-20 18:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0005_meta_participantes_metaitem_metavisualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='impulsofeedback',
            name='ai_tentativas',
            field=models.PositiveIntegerField(default=0, help_text='Quantas chamadas à IA já foram feitas para este feedback.', verbose_name='Tentativas de geração'),
        ),
        migrations.AddField(
            model_name='impulsofeedback',
            name='nota_ia',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Nota da IA'),
        ),
    ]
