# Generated by Django 5.2.5 on 2026-08-27 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0006_impulsofeedback_ai_tentativas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='participantes',
            field=models.ManyToManyField(blank=True, help_text='Até 3 pessoas, além do autor.', related_name='impulso_ideias_participando', to=settings.AUTH_USER_MODEL, verbose_name='Também participaram'),
        ),
    ]
