# Generated by Django 5.2.5 on 2026-08-31 20:23

import core.storage
import django.db.models.deletion
import impulso.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0007_ideia_participantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ARQUIVO', 'Arquivo'), ('LINK', 'Link')], max_length=8, verbose_name='Tipo')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('arquivo', models.FileField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=impulso.models.upload_projeto_anexo, verbose_name='Arquivo')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_projeto_anexos', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='impulso.projetofoco', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Anexo de Projeto Foco',
                'verbose_name_plural': 'Anexos de Projetos Foco',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
