# Generated by Django 5.2.5 on 2026-09-04 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0009_excecaoassiduidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PesosImpulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metas_qualidade', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('metas_conclusao', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('feedback', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('assiduidade', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('curso', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('videos_pops', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('projeto_foco', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('ideias', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('ideia_aprovada', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('ativos', models.JSONField(blank=True, default=dict, verbose_name='Tarefas ativas')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pesos do Impulso',
                'verbose_name_plural': 'Pesos do Impulso',
            },
        ),
    ]
