# Generated by Django 5.2.5 on 2026-09-04 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0010_pesosimpulso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pesosimpulso',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Vazio = régua geral, que vale para quem não tem a própria.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesos_impulso', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa'),
        ),
    ]
