# Generated by Django 5.2.5 on 2026-09-04 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



def aprovar_o_que_ja_valia(apps, schema_editor):
    """Tudo que já estava concluído nasce aprovado.

    A conferência é uma regra nova. Deixar o histórico em "pendente" tiraria os
    pontos do Conectar de todo mundo de uma vez, por algo que ninguém deixou de
    fazer — e a rede descobriria isso no fechamento do mês.
    """
    Conclusao = apps.get_model('impulso', 'ConclusaoConteudo')
    Conclusao.objects.filter(concluido=True).update(aprovacao='APROVADA')


def voltar_para_pendente(apps, schema_editor):
    Conclusao = apps.get_model('impulso', 'ConclusaoConteudo')
    Conclusao.objects.filter(concluido=True).update(aprovacao='PENDENTE')


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0011_pesosimpulso_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conclusaoconteudo',
            name='aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando conferência'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], db_index=True, default='PENDENTE', max_length=10, verbose_name='Aprovação'),
        ),
        migrations.AddField(
            model_name='conclusaoconteudo',
            name='decidida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conferido em'),
        ),
        migrations.AddField(
            model_name='conclusaoconteudo',
            name='decidida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_conclusoes_decididas', to=settings.AUTH_USER_MODEL, verbose_name='Conferido por'),
        ),
        migrations.AddField(
            model_name='conclusaoconteudo',
            name='observacao',
            field=models.TextField(blank=True, help_text='Obrigatória na recusa: é o que a pessoa lê para corrigir.', verbose_name='Observação de quem conferiu'),
        ),
        migrations.RunPython(aprovar_o_que_ja_valia, voltar_para_pendente),
    ]
