# Generated by Django 5.2.5 on 2026-09-04 19:00

import core.storage
import impulso.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0012_conclusaoconteudo_aprovacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoconectar',
            name='video',
            field=models.FileField(blank=True, help_text='Vídeo que acompanha o POP ou o material (opcional).', null=True, storage=core.storage.MediaStorage, upload_to=impulso.models.upload_conteudo, verbose_name='Vídeo'),
        ),
        migrations.AlterField(
            model_name='conteudoconectar',
            name='arquivo',
            field=models.FileField(blank=True, help_text='PDF do POP, material do curso ou o próprio vídeo (opcional).', null=True, storage=core.storage.MediaStorage, upload_to=impulso.models.upload_conteudo, verbose_name='Arquivo'),
        ),
    ]
