# Generated by Django 5.2.5 on 2026-09-04 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0013_conteudo_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projetofoco',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Projeto concluído'),
        ),
        migrations.AddField(
            model_name='projetofoco',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
        migrations.AddField(
            model_name='projetofoco',
            name='concluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_projetos_concluidos', to=settings.AUTH_USER_MODEL, verbose_name='Concluído por'),
        ),
    ]
