# Generated by Django 5.2.5 on 2026-09-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0014_projeto_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='apenas_dias_uteis',
            field=models.BooleanField(default=False, help_text='Prazo que cair no fim de semana passa para o próximo dia útil.', verbose_name='Somente dias úteis'),
        ),
    ]
