# Generated by Django 5.2.5 on 2026-09-10 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0015_meta_dias_uteis'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='duplicada_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicacoes', to='impulso.meta', verbose_name='Duplicada de'),
        ),
    ]
