# Generated by Django 5.2.5 on 2026-09-11 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_checklistitemevidence_file_and_more'),
        ('impulso', '0016_meta_duplicada_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='tarefa_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_impulso', to='core.taskactivity', verbose_name='Importada da tarefa'),
        ),
    ]
