# Generated by Django 5.2.5 on 2026-09-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0017_meta_tarefa_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaprojeto',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluída em'),
        ),
    ]
