# Generated by Django 5.2.5 on 2026-09-23 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def aprovar_o_que_ja_estava_concluido(apps, schema_editor):
    """Projeto já concluído antes desta regra continua valendo.

    A aprovação vale daqui para a frente. Sem isto, todo projeto encerrado
    voltaria a "aguardando" e a segunda metade dos pontos sairia da pontuação
    do mês de quem já a tinha — uma regra nova cobrando o passado.
    """
    apps.get_model('impulso', 'ProjetoFoco').objects.filter(
        concluido=True).update(aprovacao='APROVADA')


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0019_tarefas_concluidas_antigas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projetofoco',
            name='aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando aprovação'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Reprovada')], db_default='PENDENTE', db_index=True, default='PENDENTE', max_length=10, verbose_name='Aprovação da conclusão'),
        ),
        migrations.AddField(
            model_name='projetofoco',
            name='decidida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Decidido em'),
        ),
        migrations.AddField(
            model_name='projetofoco',
            name='decidida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_projetos_decididos', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por'),
        ),
        migrations.AddField(
            model_name='projetofoco',
            name='observacao',
            field=models.TextField(blank=True, db_default='', help_text='Obrigatória na reprovação: é o que o gestor lê para corrigir.', verbose_name='Observação de quem decidiu'),
        ),
        migrations.RunPython(aprovar_o_que_ja_estava_concluido,
                             migrations.RunPython.noop),
    ]
