# Generated by Django 5.2.5 on 2026-09-25 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0020_aprovacao_da_conclusao_do_projeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoAutoriaIdeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, help_text='Por que esta pessoa precisa ver a autoria das ideias.', max_length=200, verbose_name='Por quê')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Liberado em')),
                ('liberado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_autorias_liberadas', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impulso_acesso_autoria', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Acesso à autoria das ideias',
                'verbose_name_plural': 'Acessos à autoria das ideias',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
