# Generated by Django 5.2.5 on 2026-09-29 00:36

import core.storage
import django.db.models.deletion
import impulso.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0021_acessoautoriaideia'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoconectar',
            name='exige_entrega',
            field=models.BooleanField(db_default=False, default=False, help_text='Quem recebe só conclui depois de anexar arquivo(s) ou link.', verbose_name='Exige entrega'),
        ),
        migrations.CreateModel(
            name='EntregaConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, storage=core.storage.MediaStorage, upload_to=impulso.models.upload_entrega, verbose_name='Arquivo')),
                ('url', models.URLField(blank=True, verbose_name='Link')),
                ('titulo', models.CharField(blank=True, help_text='O que é este item (opcional).', max_length=200, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='impulso.conclusaoconteudo', verbose_name='Conclusão')),
            ],
            options={
                'verbose_name': 'Entrega do CONECTAR',
                'verbose_name_plural': 'Entregas do CONECTAR',
                'ordering': ['criado_em', 'id'],
            },
        ),
    ]
