# Generated by Django 5.2.5 on 2026-09-29 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0022_conteudoconectar_exige_entrega_entregaconteudo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulso_ideias_para_executar', to=settings.AUTH_USER_MODEL, verbose_name='Executor'),
        ),
        migrations.AddField(
            model_name='ideia',
            name='meta_gerada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideias_originadas', to='impulso.meta', verbose_name='Atividade criada'),
        ),
        migrations.AddField(
            model_name='ideia',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de execução'),
        ),
    ]
