# Generated by Django 5.2.5 on 2026-10-01 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0023_ideia_executor_ideia_meta_gerada_ideia_prazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParceriaMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(blank=True, max_length=200, verbose_name='Recado do convite')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando resposta'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_de_parceria', to=settings.AUTH_USER_MODEL, verbose_name='Convidado')),
                ('convidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcerias_pedidas', to=settings.AUTH_USER_MODEL, verbose_name='Quem convidou')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcerias', to='impulso.meta', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Parceria em meta',
                'verbose_name_plural': 'Parcerias em metas',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('meta', 'convidado'), name='uniq_parceria_meta')],
            },
        ),
    ]
