# Generated by Django 5.2.5 on 2026-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulso', '0024_parceria_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='como_deveria_ser',
            field=models.TextField(blank=True, db_default='', default='', verbose_name='Como deveria ser'),
        ),
        migrations.AddField(
            model_name='ideia',
            name='como_funciona_hoje',
            field=models.TextField(blank=True, db_default='', default='', verbose_name='Como funciona hoje'),
        ),
        migrations.AddField(
            model_name='ideia',
            name='tipo',
            field=models.CharField(choices=[('MELHORIA', 'Melhoria contínua'), ('PROJETO', 'Projeto')], db_default='MELHORIA', default='MELHORIA', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='descricao',
            field=models.TextField(help_text='Informe de forma concreta a sua ideia. No projeto, é o resumo dele.', verbose_name='Qual é a sua ideia?'),
        ),
    ]
