# Generated by Django 5.2.5 on 2025-09-12 14:39

import django.core.validators
import django.db.models.deletion
import trainings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do treinamento', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descrição detalhada do treinamento', verbose_name='Descrição')),
                ('video_file', models.FileField(help_text='Formatos aceitos: MP4, AVI, MOV, WMV, FLV, WebM, MKV', upload_to=trainings.models.training_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])], verbose_name='Arquivo de Vídeo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagem de miniatura para o vídeo (opcional)', null=True, upload_to='trainings/thumbnails/', verbose_name='Miniatura')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duração do vídeo em segundos', null=True, verbose_name='Duração (segundos)')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Tamanho do arquivo em bytes', null=True, verbose_name='Tamanho do Arquivo')),
                ('is_active', models.BooleanField(default=True, help_text='Se o treinamento está disponível para visualização', verbose_name='Ativo')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Número de Visualizações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Visualizado em')),
                ('duration_watched', models.PositiveIntegerField(default=0, help_text='Quantos segundos do vídeo foram assistidos', verbose_name='Duração assistida (segundos)')),
                ('completed', models.BooleanField(default=False, help_text='Se o usuário assistiu ao vídeo completo', verbose_name='Completado')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_views', to='trainings.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização de Treinamento',
                'verbose_name_plural': 'Visualizações de Treinamentos',
                'unique_together': {('training', 'user')},
            },
        ),
    ]
