# Generated by Django 5.2.5 on 2025-09-12 19:28

import django.core.validators
import trainings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_alter_training_thumbnail_alter_training_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagem de miniatura para o vídeo (opcional)', null=True, upload_to=trainings.models.training_thumbnail_path, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='training',
            name='video_file',
            field=models.FileField(help_text='Formatos aceitos: MP4, AVI, MOV, WMV, FLV, WebM, MKV', upload_to=trainings.models.training_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])], verbose_name='Arquivo de Vídeo'),
        ),
    ]
