# Generated by Django 5.2.5 on 2025-09-15 09:43

from django.db import migrations
import os


def fix_training_file_paths(apps, schema_editor):
    """Fix training file paths that use 'temp' instead of ID"""
    Training = apps.get_model('trainings', 'Training')
    
    for training in Training.objects.all():
        updated = False
        
        # Fix video file path
        if training.video_file and '/temp/' in training.video_file.name:
            # Extract filename
            filename = os.path.basename(training.video_file.name)
            name, ext = os.path.splitext(filename)
            safe_name = "".join(c for c in name if c.isalnum() or c in (' ', '-', '_')).rstrip()
            
            # Create new path with training ID
            new_path = f'trainings/videos/{training.id}/{safe_name}{ext}'
            training.video_file = new_path
            updated = True
        
        # Fix thumbnail file path
        if training.thumbnail and '/temp/' in training.thumbnail.name:
            # Extract filename
            filename = os.path.basename(training.thumbnail.name)
            name, ext = os.path.splitext(filename)
            safe_name = "".join(c for c in name if c.isalnum() or c in (' ', '-', '_')).rstrip()
            
            # Create new path with training ID
            new_path = f'trainings/thumbnails/{training.id}/{safe_name}{ext}'
            training.thumbnail = new_path
            updated = True
        
        if updated:
            training.save()


def reverse_fix_training_file_paths(apps, schema_editor):
    """Reverse the file path fix (not implemented as it's not easily reversible)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_training_thumbnail_alter_training_video_file'),
    ]

    operations = [
        migrations.RunPython(fix_training_file_paths, reverse_fix_training_file_paths),
    ]
