# Generated by Django 5.2.5 on 2025-09-24 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_fix_file_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#3B82F6', help_text='Cor em hexadecimal (ex: #FF5733)', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria de Treinamento',
                'verbose_name_plural': 'Categorias de Treinamento',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='trainingview',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='trainings.trainingcategory', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('progress_percentage', models.FloatField(default=0.0, verbose_name='Progresso (%)')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to='trainings.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso de Treinamento',
                'verbose_name_plural': 'Progressos de Treinamentos',
                'ordering': ['-started_at'],
                'unique_together': {('training', 'user')},
            },
        ),
    ]
