# Generated by Django 5.2.5 on 2026-09-15 17:28

import core.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0014_ticketcomment_excluido_em_ticketcomment_excluido_por_and_more'),
        ('users', '0038_pix_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRenova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto_b', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Desconto do padrão B (%)')),
                ('desconto_c', models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Desconto do padrão C (%)')),
                ('desconto_d', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Desconto do padrão D (%)')),
                ('imagem_tabela', models.ImageField(blank=True, storage=core.storage.MediaStorage(), upload_to='renova/materiais/', verbose_name='Imagem da tabela de avaliação')),
                ('imagem_checklist', models.ImageField(blank=True, storage=core.storage.MediaStorage(), upload_to='renova/materiais/', verbose_name='Imagem do checklist')),
                ('imagem_passo_a_passo', models.ImageField(blank=True, storage=core.storage.MediaStorage(), upload_to='renova/materiais/', verbose_name='Imagem do passo a passo')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, help_text='Cada Renova abre um chamado nesta categoria; quem é do setor dela marca a chegada do aparelho.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.category', verbose_name='Categoria do chamado')),
                ('habilitados', models.ManyToManyField(blank=True, related_name='renova_habilitacoes', to=settings.AUTH_USER_MODEL, verbose_name='Quem pode fazer Renova')),
            ],
            options={
                'verbose_name': 'Configuração do Vini Renova',
                'verbose_name_plural': 'Configuração do Vini Renova',
            },
        ),
        migrations.CreateModel(
            name='PrecoAparelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('APPLE', 'Apple'), ('SAMSUNG', 'Samsung'), ('MOTOROLA', 'Motorola'), ('XIAOMI', 'Xiaomi'), ('OUTROS', 'Outros')], default='APPLE', max_length=12, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo')),
                ('armazenamento', models.CharField(max_length=10, verbose_name='Armazenamento')),
                ('valor_excelente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor no padrão A (R$)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preço da tabela de avaliação',
                'verbose_name_plural': 'Tabela de avaliação',
                'ordering': ['marca', 'ordem', 'id'],
                'constraints': [models.UniqueConstraint(fields=('marca', 'modelo', 'armazenamento'), name='renova_preco_unico')],
            },
        ),
        migrations.CreateModel(
            name='Renova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('APPLE', 'Apple'), ('SAMSUNG', 'Samsung'), ('MOTOROLA', 'Motorola'), ('XIAOMI', 'Xiaomi'), ('OUTROS', 'Outros')], max_length=12, verbose_name='Marca')),
                ('marca_outra', models.CharField(blank=True, max_length=60, verbose_name='Outra marca')),
                ('modelo', models.CharField(max_length=120, verbose_name='Modelo')),
                ('cor', models.CharField(blank=True, max_length=60, verbose_name='Cor')),
                ('armazenamento', models.CharField(choices=[('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Armazenamento')),
                ('armazenamento_outro', models.CharField(blank=True, max_length=20, verbose_name='Outro armazenamento')),
                ('imei1', models.CharField(db_index=True, max_length=15, verbose_name='IMEI 1')),
                ('imei2', models.CharField(blank=True, max_length=15, verbose_name='IMEI 2')),
                ('numero_serie', models.CharField(blank=True, max_length=40, verbose_name='Nº de série')),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da avaliação')),
                ('padrao', models.CharField(blank=True, choices=[('A', 'Excelente'), ('B', 'Bom'), ('C', 'Regular'), ('D', 'Abaixo do padrão')], max_length=1, verbose_name='Padrão de avaliação')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor estimado de troca (R$)')),
                ('saude_bateria', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Saúde da bateria (%)')),
                ('itens_obrigatorios', models.JSONField(blank=True, default=dict, verbose_name='Itens obrigatórios conferidos')),
                ('funcionalidades', models.JSONField(blank=True, default=dict, verbose_name='Funcionalidades')),
                ('estetica', models.JSONField(blank=True, default=dict, verbose_name='Condição estética')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('parecer', models.CharField(choices=[('APROVADO', 'Aprovado para troca'), ('APROVADO_OBS', 'Aprovado com observações'), ('NAO_APROVADO', 'Não aprovado')], max_length=14, verbose_name='Parecer final')),
                ('vendedor_nome', models.CharField(max_length=150, verbose_name='Nome do vendedor')),
                ('matricula', models.CharField(blank=True, max_length=40, verbose_name='Matrícula')),
                ('assinatura', models.TextField(blank=True, verbose_name='Assinatura (imagem)')),
                ('data_responsavel', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Feito em')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('recebimento', models.CharField(choices=[('PENDENTE', 'Aguardando chegada'), ('CHEGOU', 'Chegou'), ('NAO_CHEGOU', 'Não chegou')], db_index=True, default='PENDENTE', max_length=12, verbose_name='Recebimento')),
                ('recebido_em', models.DateTimeField(blank=True, null=True, verbose_name='Marcado em')),
                ('recebimento_obs', models.TextField(blank=True, verbose_name='Observação do recebimento')),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovas', to='tickets.ticket', verbose_name='Chamado')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovas_feitos', to=settings.AUTH_USER_MODEL, verbose_name='Feito por')),
                ('loja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovas', to='users.sector', verbose_name='Loja (origem)')),
                ('preco_tabela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovas', to='renova.precoaparelho', verbose_name='Linha da tabela usada')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por')),
            ],
            options={
                'verbose_name': 'Renova',
                'verbose_name_plural': 'Renovas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
