# Generated by Django 5.2.5 on 2026-09-16 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0002_tabela_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorenova',
            name='financeiro',
            field=models.ManyToManyField(blank=True, related_name='renova_financeiro', to=settings.AUTH_USER_MODEL, verbose_name='Quem acompanha o quadro de gestão (financeiro)'),
        ),
        migrations.AddField(
            model_name='renova',
            name='aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando aprovação do gerente'), ('APROVADA', 'Aprovada pelo gerente'), ('REPROVADA', 'Reprovada pelo gerente')], db_index=True, default='PENDENTE', max_length=10, verbose_name='Aprovação do gerente'),
        ),
        migrations.AddField(
            model_name='renova',
            name='aprovacao_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Decidido em'),
        ),
        migrations.AddField(
            model_name='renova',
            name='aprovacao_obs',
            field=models.TextField(blank=True, verbose_name='Observação do gerente'),
        ),
        migrations.AddField(
            model_name='renova',
            name='aprovacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por'),
        ),
        migrations.AddField(
            model_name='renova',
            name='padrao_motivos',
            field=models.JSONField(blank=True, default=list, verbose_name='Por que este padrão'),
        ),
    ]
