# Generated by Django 5.2.5 on 2026-09-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0004_trocas_antigas_aprovadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='renova',
            name='numero_venda',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Nº da venda'),
        ),
    ]
