# Generated by Django 5.2.5 on 2026-09-16 23:23

import core.storage
import django.db.models.deletion
import renova.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0005_renova_numero_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoRenova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('frente', 'Frente'), ('traseira', 'Traseira'), ('laterais', 'Laterais'), ('tela_ligada', 'Tela ligada'), ('avaria', 'Avaria')], max_length=20, verbose_name='Foto')),
                ('arquivo', models.ImageField(storage=core.storage.MediaStorage(), upload_to=renova.models._caminho_da_foto, verbose_name='Arquivo')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('renova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='renova.renova', verbose_name='Renova')),
            ],
            options={
                'verbose_name': 'Foto do Renova',
                'verbose_name_plural': 'Fotos do Renova',
                'ordering': ['renova', 'ordem', 'id'],
            },
        ),
    ]
