# Generated by Django 5.2.5 on 2026-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0006_fotos_do_aparelho'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorenova',
            name='contrato_cnpj',
            field=models.CharField(blank=True, help_text='Vale para as lojas que não têm CNPJ próprio abaixo.', max_length=18, verbose_name='CNPJ no contrato'),
        ),
        migrations.AddField(
            model_name='configuracaorenova',
            name='contrato_empresa',
            field=models.CharField(default='REDE CONFIANÇA TELECOM LTDA.', max_length=150, verbose_name='Razão social no contrato'),
        ),
        migrations.AddField(
            model_name='configuracaorenova',
            name='contrato_lojas',
            field=models.JSONField(blank=True, default=dict, verbose_name='Cidade e CNPJ de cada loja'),
        ),
        migrations.AddField(
            model_name='renova',
            name='aparelho_novo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Aparelho novo'),
        ),
        migrations.AddField(
            model_name='renova',
            name='assinatura_cliente',
            field=models.TextField(blank=True, verbose_name='Assinatura do cliente (imagem)'),
        ),
        migrations.AddField(
            model_name='renova',
            name='cliente_cpf',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF do cliente'),
        ),
        migrations.AddField(
            model_name='renova',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do cliente'),
        ),
        migrations.AddField(
            model_name='renova',
            name='contrato_cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade do contrato'),
        ),
        migrations.AddField(
            model_name='renova',
            name='contrato_cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ no contrato'),
        ),
        migrations.AddField(
            model_name='renova',
            name='contrato_empresa',
            field=models.CharField(blank=True, max_length=150, verbose_name='Empresa no contrato'),
        ),
        migrations.AddField(
            model_name='renova',
            name='observacoes_itens',
            field=models.JSONField(blank=True, default=dict, verbose_name='Observação de cada item'),
        ),
        migrations.AddField(
            model_name='renova',
            name='vendedor_cpf',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF do vendedor'),
        ),
        migrations.AlterField(
            model_name='renova',
            name='numero_venda',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Nº da venda (Vivo Go)'),
        ),
    ]
