# Generated by Django 5.2.5 on 2026-09-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0007_contrato_e_observacoes_dos_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotorenova',
            name='tipo',
            field=models.CharField(choices=[('frente', 'Frente'), ('traseira', 'Traseira'), ('laterais', 'Laterais'), ('tela_ligada', 'Tela ligada'), ('consulta_imei', 'Print da consulta do IMEI'), ('avaria', 'Avaria')], max_length=20, verbose_name='Foto'),
        ),
    ]
