# Generated by Django 5.2.7 on 2025-11-06 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descrição curta que aparece no card', verbose_name='Descrição Resumida')),
                ('full_description', models.TextField(help_text='Descrição detalhada que aparece ao abrir o benefício', verbose_name='Descrição Completa')),
                ('coupon_code', models.CharField(help_text='Cupom que será exibido ao usuário', max_length=100, verbose_name='Código do Cupom')),
                ('image', models.ImageField(blank=True, help_text='Imagem do benefício (recomendado: 800x600px)', null=True, upload_to='benefits/', verbose_name='Imagem')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('expired', 'Expirado')], default='active', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, help_text='Benefício em destaque aparece primeiro', verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido até')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('redeems_count', models.PositiveIntegerField(default=0, verbose_name='Resgates')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_benefits', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenefitRedeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Resgatado em')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeems', to='benefits.benefit', verbose_name='Benefício')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_redeems', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resgate de Benefício',
                'verbose_name_plural': 'Resgates de Benefícios',
                'ordering': ['-redeemed_at'],
                'unique_together': {('benefit', 'user')},
            },
        ),
    ]
