# Generated by Django 5.2.5 on 2026-07-03 14:47

import core.storage
import django.db.models.deletion
import folhaponto.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('pdf_file', models.FileField(storage=core.storage.MediaStorage, upload_to=folhaponto.models.upload_folha_pdf, verbose_name='Arquivo PDF')),
                ('employee_name', models.CharField(blank=True, max_length=200, verbose_name='Nome na Folha')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Função')),
                ('admission_date', models.CharField(blank=True, max_length=20, verbose_name='Data de Admissão')),
                ('employer_name', models.CharField(blank=True, max_length=200, verbose_name='Empregador')),
                ('period_start', models.CharField(blank=True, max_length=20, verbose_name='Início do período')),
                ('period_end', models.CharField(blank=True, max_length=20, verbose_name='Fim do período')),
                ('total_trabalhadas', models.CharField(blank=True, max_length=15, verbose_name='Horas trabalhadas')),
                ('total_abono', models.CharField(blank=True, max_length=15, verbose_name='Abono')),
                ('total_previstas', models.CharField(blank=True, max_length=15, verbose_name='Horas previstas')),
                ('total_saldo', models.CharField(blank=True, max_length=15, verbose_name='Saldo do período')),
                ('trabalhadas_abono', models.CharField(blank=True, max_length=15, verbose_name='Trabalhadas + Abono')),
                ('faltas_horas', models.CharField(blank=True, max_length=15, verbose_name='Faltas em horas')),
                ('saldo_anterior', models.CharField(blank=True, max_length=15, verbose_name='Saldo anterior banco de horas')),
                ('saldo_acumulado', models.CharField(blank=True, max_length=15, verbose_name='Saldo acumulado')),
                ('horas_extras', models.CharField(blank=True, max_length=15, verbose_name='Horas extras totais')),
                ('atrasos', models.CharField(blank=True, max_length=15, verbose_name='Atrasos')),
                ('dias_faltosos', models.PositiveIntegerField(default=0, verbose_name='Dias faltosos')),
                ('daily_records', models.JSONField(blank=True, default=list, verbose_name='Marcações diárias')),
                ('pdf_page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Página inicial no PDF original')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Assinado em')),
                ('signature_image', models.TextField(blank=True, verbose_name='Assinatura (base64)')),
                ('signature_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da assinatura')),
                ('signature_user_agent', models.TextField(blank=True, verbose_name='User-Agent da assinatura')),
                ('signature_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash de verificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folhas_ponto_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folhas_ponto', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Folha de Ponto',
                'verbose_name_plural': 'Folhas de Ponto',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
