# Generated by Django 5.2.5 on 2026-07-10 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhaponto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaPontoManagerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folhaponto_permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folhaponto_manager_permission', to=settings.AUTH_USER_MODEL, verbose_name='Usuário liberado')),
            ],
            options={
                'verbose_name': 'Acesso à gestão da Folha de Ponto',
                'verbose_name_plural': 'Acessos à gestão da Folha de Ponto',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
