# Generated by Django 5.2.5 on 2026-08-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhaponto', '0002_folhapontomanagerpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhaponto',
            name='force_mensal',
            field=models.BooleanField(default=False, help_text='Trata a folha sempre como mensal (assinável), ignorando a classificação automática semanal/mensal.', verbose_name='Forçar como Mensal'),
        ),
    ]
