# Generated by Django 5.2.5 on 2026-08-28 18:14

import django.db.models.deletion
import reunioes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0010_meetingtranscription_shared_with_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoReunioes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_jitsi', models.CharField(default='meet.jit.si', help_text='Servidor público por padrão. Trocar por um servidor da empresa é mudar só este campo.', max_length=200, verbose_name='Servidor de vídeo (Jitsi)')),
                ('gerar_ata', models.BooleanField(default=True, help_text='Ao encerrar a gravação, a IA monta a ata e envia para quem estava na agenda.', verbose_name='Gerar ata automaticamente')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Reuniões',
                'verbose_name_plural': 'Configuração de Reuniões',
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Tema da reunião')),
                ('pauta', models.TextField(blank=True, verbose_name='Pauta')),
                ('inicio', models.DateTimeField(verbose_name='Início')),
                ('fim', models.DateTimeField(blank=True, help_text='Só uma previsão para a agenda. A sala não fecha na hora marcada.', null=True, verbose_name='Fim previsto')),
                ('sala', models.CharField(default=reunioes.models.nova_sala, max_length=64, unique=True, verbose_name='Sala de vídeo')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=14)),
                ('gravar_ata', models.BooleanField(default=True, verbose_name='Gerar ata')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniao', to='agenda.calendarevent', verbose_name='Evento na agenda')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_organizadas', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('MANUAL', 'Escolhido na lista'), ('CARGO', 'Pelo cargo'), ('SETOR', 'Pelo setor'), ('GRUPO', 'Pelo grupo'), ('COORDENACAO', 'Pela coordenação')], default='MANUAL', max_length=12)),
                ('rotulo_origem', models.CharField(blank=True, help_text='Nome do cargo/setor/grupo que trouxe a pessoa, para ela saber o porquê.', max_length=120, verbose_name='De onde veio')),
                ('entrou_em', models.DateTimeField(blank=True, null=True, verbose_name='Entrou na sala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_convidado', to=settings.AUTH_USER_MODEL)),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='reunioes.reuniao')),
            ],
            options={
                'verbose_name': 'Participante da reunião',
                'verbose_name_plural': 'Participantes da reunião',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='reuniao',
            index=models.Index(fields=['inicio', 'status'], name='reunioes_re_inicio_6dd613_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantereuniao',
            unique_together={('reuniao', 'user')},
        ),
    ]
