# Generated by Django 5.2.5 on 2026-08-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoreunioes',
            name='jaas_api_key_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='JaaS — ID da chave (kid)'),
        ),
        migrations.AddField(
            model_name='configuracaoreunioes',
            name='jaas_app_id',
            field=models.CharField(blank=True, help_text='Começa com "vpaas-magic-cookie-".', max_length=120, verbose_name='JaaS — AppID'),
        ),
        migrations.AddField(
            model_name='configuracaoreunioes',
            name='jaas_chave_privada',
            field=models.TextField(blank=True, help_text='O arquivo .pk baixado no painel do 8x8, colado inteiro.', verbose_name='JaaS — chave privada (PEM)'),
        ),
    ]
