# Generated by Django 5.2.5 on 2026-09-01 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0002_configuracaoreunioes_jaas_api_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoreunioes',
            name='aplicar_fundo_padrao',
            field=models.BooleanField(default=True, help_text='Liga o fundo virtual para todo mundo ao entrar. Desligue se os celulares da rede ficarem lentos: o efeito processa vídeo.', verbose_name='Aplicar o fundo automaticamente'),
        ),
        migrations.AddField(
            model_name='configuracaoreunioes',
            name='fundo_sala_url',
            field=models.URLField(blank=True, help_text='Deixe em branco para usar a imagem padrão da rede. Precisa ser uma URL pública — quem baixa é o servidor de vídeo.', verbose_name='Fundo de tela da sala'),
        ),
        migrations.AddField(
            model_name='configuracaoreunioes',
            name='permitir_link_publico',
            field=models.BooleanField(default=True, help_text='Deixa o organizador gerar um link para quem não tem conta no portal. Desligar aqui derruba os links já criados.', verbose_name='Permitir link público de visitante'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='publico_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Link público criado em'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='token_publico',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Link público'),
        ),
        migrations.CreateModel(
            name='VisitanteReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome informado')),
                ('entrou_em', models.DateTimeField(auto_now_add=True, verbose_name='Entrou em')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='reunioes.reuniao')),
            ],
            options={
                'verbose_name': 'Visitante da reunião',
                'verbose_name_plural': 'Visitantes da reunião',
                'ordering': ['entrou_em'],
            },
        ),
    ]
