# Generated by Django 5.2.5 on 2026-09-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0003_configuracaoreunioes_aplicar_fundo_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='tipo',
            field=models.CharField(choices=[('REUNIAO', 'Reunião'), ('ENTREVISTA', 'Entrevista')], db_index=True, default='REUNIAO', max_length=12, verbose_name='Tipo'),
        ),
    ]
