# Generated by Django 5.2.5 on 2026-09-04 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0016_alter_communication_image_and_more'),
        ('users', '0038_pix_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Módulo Drive ativo')),
                ('shared_drive_id', models.CharField(blank=True, default='', help_text='Se a empresa usa um Drive Compartilhado (Team Drive), cole o ID aqui. Opcional.', max_length=100, verbose_name='ID do Drive Compartilhado')),
                ('max_file_mb', models.PositiveIntegerField(default=100, verbose_name='Tamanho máximo por arquivo (MB)')),
                ('allowed_extensions', models.TextField(default='pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,csv,txt,zip', help_text='Separadas por vírgula, sem ponto. Ex.: pdf,docx,xlsx', verbose_name='Extensões permitidas')),
                ('storage_cap_gb', models.PositiveIntegerField(default=0, help_text='0 = sem limite pelo portal (vale o limite do próprio Google).', verbose_name='Capacidade máxima (GB)')),
                ('trash_retention_days', models.PositiveIntegerField(default=30, verbose_name='Dias na lixeira antes da exclusão definitiva')),
                ('notify_new', models.BooleanField(default=True, verbose_name='Avisar novo documento no setor')),
                ('notify_updated', models.BooleanField(default=True, verbose_name='Avisar documento atualizado')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Drive',
                'verbose_name_plural': 'Configuração do Drive',
            },
        ),
        migrations.CreateModel(
            name='SectorDriveMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(help_text='O ID que aparece na URL do Drive depois de /folders/.', max_length=100, verbose_name='ID da pasta no Google Drive')),
                ('folder_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome da pasta (cache)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('managers', models.ManyToManyField(blank=True, help_text='Gerenciam todos os arquivos/pastas que os usuários do setor enxergam.', related_name='drive_setores_geridos', to=settings.AUTH_USER_MODEL, verbose_name='Gestores do setor')),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_mapping', to='users.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Setor no Drive',
                'verbose_name_plural': 'Setores no Drive',
                'ordering': ['sector__name'],
            },
        ),
        migrations.CreateModel(
            name='DrivePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Pasta (vazio = setor inteiro)')),
                ('folder_name', models.CharField(blank=True, default='', max_length=255)),
                ('alvo', models.CharField(choices=[('USER', 'Usuário'), ('GROUP', 'Grupo'), ('SECTOR', 'Setor'), ('HIERARCHY', 'Hierarquia')], max_length=10)),
                ('target_hierarchy', models.CharField(blank=True, choices=[('PADRAO', 'Padrão'), ('ADMINISTRATIVO', 'Administrativo'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Administração'), ('SUPERADMIN', 'Superadmin')], default='', max_length=20)),
                ('nivel', models.CharField(choices=[('VIEW', 'Visualizar'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('EDIT', 'Editar'), ('DELETE', 'Excluir'), ('ADMIN', 'Administrar')], default='VIEW', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_permissoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_permissoes', to='communications.communicationgroup')),
                ('target_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_permissoes_alvo', to='users.sector')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_permissoes', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='drive.sectordrivemapping', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Permissão do Drive',
                'verbose_name_plural': 'Permissões do Drive',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DriveAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('VIEW', 'Visualização'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('EDIT', 'Alteração'), ('DELETE', 'Exclusão'), ('MOVE', 'Movimentação'), ('RENAME', 'Renomeação'), ('RESTORE', 'Restauração'), ('MKDIR', 'Nova pasta'), ('VERSION', 'Nova versão'), ('PERM', 'Permissão alterada'), ('DENY', 'Acesso negado')], db_index=True, max_length=12)),
                ('file_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('folder_id', models.CharField(blank=True, default='', max_length=100)),
                ('detalhe', models.CharField(blank=True, default='', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_logs', to='users.sector')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log do Drive',
                'verbose_name_plural': 'Logs do Drive',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['acao', '-criado_em'], name='drive_drive_acao_5a2ba2_idx'), models.Index(fields=['file_id', '-criado_em'], name='drive_drive_file_id_213722_idx'), models.Index(fields=['user', '-criado_em'], name='drive_drive_user_id_177fc9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriveFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito do Drive',
                'verbose_name_plural': 'Favoritos do Drive',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('user', 'file_id'), name='uniq_drive_favorito')],
            },
        ),
    ]
