# Generated by Django 5.2.5 on 2026-09-05 14:22

import drive.models
import drive.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveconfig',
            name='impersonate_email',
            field=models.EmailField(blank=True, default='', help_text='E-mail de um usuário/admin do Workspace para o Drive enxergar TODOS os arquivos da conta. Exige delegação em todo o domínio autorizada no Admin.', max_length=254, verbose_name='Impersonar (delegação em todo o domínio)'),
        ),
        migrations.AddField(
            model_name='driveconfig',
            name='sa_client_email',
            field=models.CharField(blank=True, default='', help_text='Extraído da chave; é com este e-mail que se compartilham as pastas.', max_length=255, verbose_name='E-mail da conta de serviço'),
        ),
        migrations.AddField(
            model_name='driveconfig',
            name='sa_json',
            field=models.FileField(blank=True, null=True, storage=drive.storage.DriveCredentialStorage(), upload_to=drive.models.upload_credencial, verbose_name='Credencial (JSON da conta de serviço)'),
        ),
    ]
