# Generated by Django 5.2.5 on 2026-09-09 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_driveconfig_impersonate_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driveconfig',
            name='modo',
            field=models.CharField(choices=[('SA', 'Conta de serviço (pastas compartilhadas)'), ('OAUTH', 'Minha conta Google (todos os meus arquivos)')], default='SA', max_length=6, verbose_name='Como o portal acessa o Drive'),
        ),
        migrations.AddField(
            model_name='driveconfig',
            name='oauth_client_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID do cliente OAuth'),
        ),
        migrations.AddField(
            model_name='driveconfig',
            name='oauth_client_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Segredo do cliente OAuth'),
        ),
        migrations.AddField(
            model_name='driveconfig',
            name='oauth_conectado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conectado em'),
        ),
        migrations.AddField(
            model_name='driveconfig',
            name='oauth_conectado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Conectado por'),
        ),
        migrations.AddField(
            model_name='driveconfig',
            name='oauth_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Conta conectada'),
        ),
        migrations.AddField(
            model_name='driveconfig',
            name='oauth_refresh_token',
            field=models.TextField(blank=True, default='', verbose_name='Refresh token'),
        ),
    ]
