# Generated by Django 5.2.5 on 2026-09-10 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_conta_propria_oauth'),
        ('users', '0038_pix_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('file_id', models.CharField(db_index=True, max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('meu_drive', models.BooleanField(default=False)),
                ('modo', models.CharField(choices=[('office', 'No Office (Word, Excel, PowerPoint)'), ('arquivo', 'Cópia no computador')], max_length=10)),
                ('pode_salvar', models.BooleanField(default=False)),
                ('md5_base', models.CharField(blank=True, default='', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('aberto_em', models.DateTimeField(blank=True, null=True)),
                ('permissao_conferida_em', models.DateTimeField(blank=True, null=True)),
                ('lock_token', models.CharField(blank=True, default='', max_length=80)),
                ('lock_expira_em', models.DateTimeField(blank=True, null=True)),
                ('salvamentos', models.PositiveIntegerField(default=0)),
                ('ultimo_salvamento_em', models.DateTimeField(blank=True, null=True)),
                ('conflito_file_id', models.CharField(blank=True, default='', max_length=100)),
                ('ultimo_conflito_nome', models.CharField(blank=True, default='', max_length=255)),
                ('ultimo_conflito_em', models.DateTimeField(blank=True, null=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_edicoes_locais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edição no computador',
                'verbose_name_plural': 'Edições no computador',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['file_id', 'lock_expira_em'], name='drive_edica_file_id_9c00e3_idx')],
            },
        ),
    ]
