# Generated by Django 5.2.5 on 2026-09-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_edicao_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveauditlog',
            name='acao',
            field=models.CharField(choices=[('VIEW', 'Visualização'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('EDIT', 'Alteração'), ('DELETE', 'Exclusão'), ('MOVE', 'Movimentação'), ('RENAME', 'Renomeação'), ('RESTORE', 'Restauração'), ('MKDIR', 'Nova pasta'), ('VERSION', 'Nova versão'), ('PERM', 'Permissão alterada'), ('DENY', 'Acesso negado'), ('USO_LOCAL', 'Uso local')], db_index=True, max_length=12),
        ),
    ]
