# Generated by Django 5.2.5 on 2026-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_acao_uso_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveconfig',
            name='allowed_extensions',
            field=models.TextField(default='pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,webp,heic,heif,gif,csv,txt,zip', help_text='Separadas por vírgula, sem ponto. Ex.: pdf,docx,xlsx. Vazio aceita qualquer uma.', verbose_name='Extensões permitidas'),
        ),
    ]
