"""Pasta liberada: a raiz do Drive que não depende de setor.

Cria a PastaLiberada (pasta qualquer do Drive liberada direto para uma
pessoa, grupo, setor ou hierarquia) e o campo `pasta` do favorito, para
o favorito de dentro dela saber para onde voltar.
"""
# Generated by Django 5.2.5 on 2026-09-25 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0017_communication_obrigatorio'),
        ('drive', '0006_extensoes_com_foto'),
        ('users', '0041_dependentes_do_colaborador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaLiberada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=100, verbose_name='Pasta no Google Drive')),
                ('folder_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome da pasta')),
                ('caminho', models.CharField(blank=True, default='', help_text='Caminho da pasta no Drive, guardado para a tela mostrar de onde ela veio.', max_length=500, verbose_name='Onde fica')),
                ('alvo', models.CharField(choices=[('USER', 'Usuário'), ('GROUP', 'Grupo'), ('SECTOR', 'Setor'), ('HIERARCHY', 'Hierarquia')], default='USER', max_length=10)),
                ('target_hierarchy', models.CharField(blank=True, choices=[('PADRAO', 'Padrão'), ('ADMINISTRATIVO', 'Administrativo'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Administração'), ('SUPERADMIN', 'Superadmin')], default='', max_length=20)),
                ('nivel', models.CharField(choices=[('VIEW', 'Visualizar'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('EDIT', 'Editar'), ('DELETE', 'Excluir'), ('ADMIN', 'Administrar')], default='VIEW', max_length=10, verbose_name='Nível')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_pastas_liberadas_criadas', to=settings.AUTH_USER_MODEL)),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_pastas_liberadas', to='communications.communicationgroup', verbose_name='Grupo')),
                ('target_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_pastas_liberadas', to='users.sector', verbose_name='Setor')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_pastas_liberadas', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Pasta liberada do Drive',
                'verbose_name_plural': 'Pastas liberadas do Drive',
                'ordering': ['folder_name', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='drivefavorite',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoritos', to='drive.pastaliberada', verbose_name='Pasta liberada'),
        ),
        migrations.AddIndex(
            model_name='pastaliberada',
            index=models.Index(fields=['ativo', 'alvo'], name='drive_pasta_ativo_aaa0e3_idx'),
        ),
    ]
