# Generated by Django 5.2.5 on 2025-09-12 18:20

import core.storage
import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=files.models.upload_file_path, verbose_name='Arquivo'),
        ),
    ]
