# Generated by Django 5.2.5 on 2025-09-16 19:14

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_sharedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(upload_to=files.models.upload_file_path, verbose_name='Arquivo'),
        ),
    ]
