# Generated by Django 5.2.5 on 2025-09-17 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_sharedfile_file'),
        ('users', '0007_user_disc_profile_alter_user_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Categoria de Arquivo', 'verbose_name_plural': 'Categorias de Arquivos'},
        ),
        migrations.AddField(
            model_name='filecategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Pasta')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#3B82F6', help_text='Cor em hexadecimal', max_length=7, verbose_name='Cor')),
                ('visibility', models.CharField(choices=[('ALL', 'Todos os usuários'), ('SECTOR', 'Usuários do setor'), ('ADMIN', 'Apenas administradores')], default='ALL', max_length=10, verbose_name='Visibilidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='files.folder', verbose_name='Pasta Pai')),
                ('target_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sector', verbose_name='Setor alvo')),
            ],
            options={
                'verbose_name': 'Pasta',
                'verbose_name_plural': 'Pastas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='filecategory',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='files.folder', verbose_name='Pasta'),
        ),
    ]
