# Generated by Django 5.2.7 on 2025-10-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0013_communicationimage'),
        ('files', '0004_alter_filecategory_options_filecategory_order_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.communicationgroup', verbose_name='Grupo alvo'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='visibility',
            field=models.CharField(choices=[('ALL', 'Todos os usuários'), ('SECTOR', 'Usuários do setor'), ('GROUP', 'Grupo específico'), ('USER', 'Usuário específico')], default='ALL', max_length=10, verbose_name='Visibilidade'),
        ),
    ]
