# Generated by Django 5.2.5 on 2026-10-07 02:24

import core.storage
import django.db.models.deletion
import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_sharedfile_target_group_alter_sharedfile_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategory',
            name='excluido_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='filecategory',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='filecategory',
            name='lote_exclusao',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Lote da exclusão'),
        ),
        migrations.AddField(
            model_name='folder',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='pastas_liberadas', to=settings.AUTH_USER_MODEL, verbose_name='Pessoas com acesso'),
        ),
        migrations.AddField(
            model_name='folder',
            name='excluido_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='folder',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='folder',
            name='lote_exclusao',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Lote da exclusão'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='arquivos_liberados', to=settings.AUTH_USER_MODEL, verbose_name='Pessoas com acesso'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='excluido_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='lote_exclusao',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Lote da exclusão'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=files.models.upload_file_path, verbose_name='Arquivo'),
        ),
        migrations.CreateModel(
            name='MovimentacaoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('ENVIO', 'Envio de arquivo'), ('DOWNLOAD', 'Download / visualização'), ('CRIAR_PASTA', 'Pasta criada'), ('CRIAR_CATEGORIA', 'Categoria criada'), ('MOVER', 'Arquivo movido'), ('EXCLUIR', 'Enviado para a lixeira'), ('RESTAURAR', 'Recuperado da lixeira'), ('LIBERAR', 'Acesso liberado para pessoa'), ('RETIRAR', 'Acesso retirado de pessoa'), ('NEGADO', 'Tentativa sem permissão')], db_index=True, max_length=20, verbose_name='Ação')),
                ('tipo', models.CharField(choices=[('ARQUIVO', 'Arquivo'), ('PASTA', 'Pasta'), ('CATEGORIA', 'Categoria')], max_length=10, verbose_name='Tipo do item')),
                ('item_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID do item')),
                ('item_nome', models.CharField(blank=True, max_length=255, verbose_name='Item')),
                ('detalhe', models.TextField(blank=True, verbose_name='Detalhe')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('quando', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Quando')),
                ('pessoa', models.ForeignKey(blank=True, help_text='Em liberar/retirar acesso: a quem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa afetada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_arquivos', to=settings.AUTH_USER_MODEL, verbose_name='Quem')),
            ],
            options={
                'verbose_name': 'Movimentação de arquivo',
                'verbose_name_plural': 'Movimentações de arquivos',
                'ordering': ['-quando', '-id'],
            },
        ),
    ]
