# Generated by Django 5.2.5 on 2026-08-19 18:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0032_user_tangerino_employee_id_user_tangerino_synced_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoContagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('FORMA_PGTO', 'Somar uma forma de pagamento (DS_COND_PGTO)'), ('COLUNA', 'Somar uma coluna de valor')], default='FORMA_PGTO', max_length=12, verbose_name='Como calcular o Valor SAP')),
                ('forma_pagamento', models.CharField(default='DINHEIRO', help_text='Usada no modo por forma de pagamento. Ex.: DINHEIRO, PIX, DÉBITO, CRÉDITO.', max_length=30, verbose_name='Forma de pagamento')),
                ('colunas_condicao', models.CharField(default='DS_COND_PGTO_01,DS_COND_PGTO_02,DS_COND_PGTO_03', help_text='Separadas por vírgula.', max_length=200, verbose_name='Colunas de condição de pagamento')),
                ('coluna_pedido', models.CharField(default='NU_ORDM_PRDD', help_text='Usada para não contar o mesmo pagamento duas vezes.', max_length=60, verbose_name='Coluna do pedido')),
                ('coluna_valor', models.CharField(default='VALOR_NF', help_text='Somada como Valor SAP no modo por coluna.', max_length=60, verbose_name='Coluna do valor')),
                ('coluna_codigo', models.CharField(default='CD_CRDN', help_text='Casada com o ADABAS do setor. É o casamento mais confiável.', max_length=60, verbose_name='Coluna do código da loja')),
                ('coluna_loja', models.CharField(default='NOME LOJAS', max_length=60, verbose_name='Coluna do nome da loja')),
                ('coluna_data', models.CharField(default='DATA', max_length=60, verbose_name='Coluna da data')),
                ('aba', models.CharField(default='Export', max_length=60, verbose_name='Aba da planilha')),
                ('filtro_coluna', models.CharField(blank=True, help_text='Opcional. Ex.: CENARIO para importar só um cenário.', max_length=60, verbose_name='Filtrar pela coluna')),
                ('filtro_valor', models.CharField(blank=True, help_text='Valor que a coluna acima precisa ter. Vazio = sem filtro.', max_length=120, verbose_name='Filtrar pelo valor')),
                ('notificar_gerente', models.BooleanField(default=True, verbose_name='Avisar o gerente quando ficar em Atenção')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da contagem de caixa',
                'verbose_name_plural': 'Configuração da contagem de caixa',
            },
        ),
        migrations.CreateModel(
            name='ImportacaoContagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(blank=True, max_length=255, verbose_name='Arquivo')),
                ('executada_em', models.DateTimeField(auto_now_add=True)),
                ('linhas_lidas', models.PositiveIntegerField(default=0)),
                ('dias_criados', models.PositiveIntegerField(default=0)),
                ('dias_atualizados', models.PositiveIntegerField(default=0)),
                ('lojas_sem_setor', models.TextField(blank=True, verbose_name='Lojas sem setor no portal')),
                ('sucesso', models.BooleanField(default=True)),
                ('detalhe', models.TextField(blank=True)),
                ('executada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_contagem', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Importação da contagem de caixa',
                'verbose_name_plural': 'Importações da contagem de caixa',
                'ordering': ['-executada_em'],
            },
        ),
        migrations.CreateModel(
            name='ContagemCaixaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('valor_sap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor SAP')),
                ('importado_em', models.DateTimeField(blank=True, null=True, verbose_name='Importado em')),
                ('valor_vivogo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Vivo go EA')),
                ('allied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='allied')),
                ('recarga', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='recarga')),
                ('agoracred', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Agoracred')),
                ('renova', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Renova')),
                ('sangria_erro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='sangria/erro')),
                ('transferencias', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Transferências')),
                ('valor_real', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor real')),
                ('entrada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Entrada')),
                ('deposito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Depósito')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo')),
                ('notificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Gerente avisado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contagens_caixa_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contagens_caixa', to='users.sector', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Contagem de caixa (dia)',
                'verbose_name_plural': 'Contagem de caixa (dias)',
                'ordering': ['loja__name', '-data'],
                'indexes': [models.Index(fields=['data', 'loja'], name='contagem_ca_data_768e27_idx')],
                'constraints': [models.UniqueConstraint(fields=('loja', 'data'), name='contagem_caixa_unica_por_loja_dia')],
            },
        ),
    ]
