# Generated by Django 5.2.5 on 2026-08-22 13:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagem_caixa', '0003_entrada_calculada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contagemcaixadia',
            name='entrada_manual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Entrada (digitada)'),
        ),
    ]
