# Generated by Django 5.2.5 on 2026-09-02 17:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagem_caixa', '0004_alter_contagemcaixadia_entrada_manual'),
        ('users', '0036_userchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoInicialMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo inicial do mês')),
                ('motivo', models.CharField(blank=True, help_text='Aparece na tela. Ex.: "abertura do controle" ou "acerto do fechamento".', max_length=200, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('definido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_iniciais_caixa', to=settings.AUTH_USER_MODEL, verbose_name='Definido por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_iniciais_caixa', to='users.sector', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Saldo inicial do mês',
                'verbose_name_plural': 'Saldos iniciais do mês',
                'ordering': ['loja__name', '-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('loja', 'ano', 'mes'), name='contagem_caixa_saldo_inicial_unico')],
            },
        ),
    ]
