# Generated by Django 5.2.5 on 2026-10-09 11:42

import contagem_caixa.models
import core.storage
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# Ponto de partida das categorias; o gestor ajusta a lista na tela.
CATEGORIAS = ['Alimentação', 'Água e café', 'Limpeza e higiene', 'Material de escritório',
              'Manutenção e reparos', 'Combustível e transporte', 'Correios e fretes',
              'Pagamento a fornecedor', 'Troco / fundo de caixa', 'Outros']


def criar_categorias(apps, schema_editor):
    Categoria = apps.get_model('contagem_caixa', 'CategoriaSangria')
    for ordem, nome in enumerate(CATEGORIAS):
        Categoria.objects.get_or_create(nome=nome, defaults={'ordem': ordem})


class Migration(migrations.Migration):

    dependencies = [
        ('contagem_caixa', '0006_saldo_com_diferenca'),
        ('users', '0044_display_reference_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSangria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='Categoria')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria de sangria',
                'verbose_name_plural': 'Categorias de sangria',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='contagemcaixadia',
            name='sangria_registrada',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sangrias registradas'),
        ),
        migrations.CreateModel(
            name='Sangria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data da sangria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('favorecido', models.CharField(blank=True, help_text='Quem recebeu o dinheiro (fornecedor, pessoa, estabelecimento).', max_length=120, verbose_name='Pago a')),
                ('comprovante', models.FileField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to=contagem_caixa.models.caminho_comprovante_sangria, verbose_name='Comprovante')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('conferida', models.BooleanField(db_index=True, default=False, verbose_name='Conferida')),
                ('conferida_em', models.DateTimeField(blank=True, null=True, verbose_name='Conferida em')),
                ('observacao_conferencia', models.CharField(blank=True, max_length=255, verbose_name='Observação da conferência')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sangrias', to='contagem_caixa.categoriasangria', verbose_name='Categoria')),
                ('conferida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sangrias_conferidas', to=settings.AUTH_USER_MODEL, verbose_name='Conferida por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sangrias', to='users.sector', verbose_name='Loja')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sangrias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
            ],
            options={
                'verbose_name': 'Sangria',
                'verbose_name_plural': 'Sangrias',
                'ordering': ['-data', '-criada_em'],
                'indexes': [models.Index(fields=['loja', 'data'], name='contagem_ca_loja_id_633948_idx')],
            },
        ),
        migrations.RunPython(criar_categorias, migrations.RunPython.noop),
    ]
