# Generated by Django 5.2.5 on 2026-10-09 13:03

import contagem_caixa.models
import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagem_caixa', '0007_sangrias'),
        ('users', '0044_display_reference_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorPisCofins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia')),
                ('situacao', models.CharField(blank=True, max_length=40, verbose_name='Situação cadastral')),
                ('atividade', models.CharField(blank=True, max_length=255, verbose_name='Atividade principal')),
                ('simples', models.BooleanField(blank=True, null=True, verbose_name='Optante pelo Simples')),
                ('municipio', models.CharField(blank=True, max_length=80, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('consultado_em', models.DateTimeField(blank=True, null=True, verbose_name='Consultado na Receita em')),
            ],
            options={
                'verbose_name': 'Fornecedor (PIS/Cofins)',
                'verbose_name_plural': 'Fornecedores (PIS/Cofins)',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPisCofins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NF', 'Nota fiscal'), ('BOLETO', 'Boleto'), ('ALUGUEL', 'Recibo de aluguel'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Tipo')),
                ('competencia', models.DateField(db_index=True, help_text='Sempre o dia 1º do mês de competência.', verbose_name='Competência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('numero', models.CharField(blank=True, max_length=60, verbose_name='Número do documento')),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('arquivo', models.FileField(storage=core.storage.MediaStorage(), upload_to=contagem_caixa.models.caminho_documento_piscofins, verbose_name='Arquivo')),
                ('nome_arquivo', models.CharField(blank=True, max_length=255, verbose_name='Nome original do arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_piscofins', to='users.sector', verbose_name='Loja / unidade')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_piscofins', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='contagem_caixa.fornecedorpiscofins', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Documento de PIS/Cofins',
                'verbose_name_plural': 'Documentos de PIS/Cofins',
                'ordering': ['-competencia', '-criado_em'],
            },
        ),
    ]
