# Generated by Django 5.2.5 on 2026-10-09 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagem_caixa', '0008_piscofins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacaoDFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('ult_nsu', models.BigIntegerField(default=0, verbose_name='Último NSU')),
                ('max_nsu', models.BigIntegerField(default=0, verbose_name='Maior NSU na SEFAZ')),
                ('ultima_consulta', models.DateTimeField(blank=True, null=True, verbose_name='Última consulta')),
                ('proxima_consulta', models.DateTimeField(blank=True, null=True, verbose_name='Próxima consulta permitida')),
                ('ultimo_cstat', models.CharField(blank=True, max_length=10, verbose_name='Último código')),
                ('ultima_mensagem', models.CharField(blank=True, max_length=255, verbose_name='Última mensagem')),
                ('notas_novas', models.PositiveIntegerField(default=0, verbose_name='Notas novas na última consulta')),
            ],
            options={
                'verbose_name': 'Sincronização com a SEFAZ',
                'verbose_name_plural': 'Sincronizações com a SEFAZ',
            },
        ),
        migrations.CreateModel(
            name='NotaRecebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=44, unique=True, verbose_name='Chave de acesso')),
                ('cnpj_destinatario', models.CharField(db_index=True, max_length=14, verbose_name='CNPJ da empresa')),
                ('emitente_cnpj', models.CharField(db_index=True, max_length=14, verbose_name='CNPJ do emitente')),
                ('emitente_nome', models.CharField(blank=True, max_length=200, verbose_name='Emitente')),
                ('emitente_ie', models.CharField(blank=True, max_length=20, verbose_name='IE do emitente')),
                ('modelo', models.CharField(blank=True, max_length=2, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=3, verbose_name='Série')),
                ('numero', models.CharField(blank=True, db_index=True, max_length=9, verbose_name='Número')),
                ('emissao', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Emissão')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor')),
                ('situacao', models.CharField(choices=[('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('DENEGADA', 'Denegada')], default='AUTORIZADA', max_length=12, verbose_name='Situação')),
                ('tipo_operacao', models.CharField(blank=True, max_length=1, verbose_name='Tipo (0 entrada, 1 saída)')),
                ('nsu', models.BigIntegerField(default=0, verbose_name='NSU')),
                ('xml_resumo', models.TextField(blank=True, verbose_name='XML do resumo')),
                ('xml_completo', models.TextField(blank=True, verbose_name='XML completo')),
                ('ignorada', models.BooleanField(default=False, verbose_name='Fora do PIS/Cofins')),
                ('recebida_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_sefaz', to='contagem_caixa.documentopiscofins', verbose_name='Lançado como')),
                ('ignorada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Marcada por')),
            ],
            options={
                'verbose_name': 'Nota recebida (SEFAZ)',
                'verbose_name_plural': 'Notas recebidas (SEFAZ)',
                'ordering': ['-emissao'],
            },
        ),
    ]
