# Generated by Django 5.2.5 on 2026-10-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagem_caixa', '0009_notas_sefaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarecebida',
            name='competencia',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Competência (NFS-e)'),
        ),
        migrations.AddField(
            model_name='notarecebida',
            name='descricao',
            field=models.CharField(blank=True, db_default='', default='', max_length=255, verbose_name='Descrição do serviço'),
        ),
        migrations.AddField(
            model_name='notarecebida',
            name='tipo_documento',
            field=models.CharField(choices=[('NFE', 'NF-e'), ('NFSE', 'NFS-e')], db_default='NFE', db_index=True, default='NFE', max_length=4, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='notarecebida',
            name='valor_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor líquido (NFS-e)'),
        ),
        migrations.AddField(
            model_name='sincronizacaodfe',
            name='notas_novas_nfse',
            field=models.PositiveIntegerField(db_default=0, default=0, verbose_name='NFS-e novas na última consulta'),
        ),
        migrations.AddField(
            model_name='sincronizacaodfe',
            name='proxima_consulta_nfse',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima consulta (NFS-e)'),
        ),
        migrations.AddField(
            model_name='sincronizacaodfe',
            name='ult_nsu_nfse',
            field=models.BigIntegerField(db_default=0, default=0, verbose_name='Último NSU (NFS-e)'),
        ),
        migrations.AddField(
            model_name='sincronizacaodfe',
            name='ultima_consulta_nfse',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última consulta (NFS-e)'),
        ),
        migrations.AddField(
            model_name='sincronizacaodfe',
            name='ultima_mensagem_nfse',
            field=models.CharField(blank=True, db_default='', default='', max_length=255, verbose_name='Última mensagem (NFS-e)'),
        ),
        migrations.AddField(
            model_name='sincronizacaodfe',
            name='ultimo_status_nfse',
            field=models.CharField(blank=True, db_default='', default='', max_length=40, verbose_name='Último status (NFS-e)'),
        ),
        migrations.AlterField(
            model_name='notarecebida',
            name='chave',
            field=models.CharField(max_length=50, unique=True, verbose_name='Chave de acesso'),
        ),
        migrations.AlterField(
            model_name='notarecebida',
            name='numero',
            field=models.CharField(blank=True, db_index=True, max_length=15, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='notarecebida',
            name='serie',
            field=models.CharField(blank=True, max_length=5, verbose_name='Série'),
        ),
    ]
