# Generated by Django 4.2.16 on 2026-02-26 07:49

import contracheque.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('pdf_file', models.FileField(upload_to=contracheque.models.upload_payslip_pdf, verbose_name='Arquivo PDF')),
                ('employee_name', models.CharField(blank=True, max_length=200, verbose_name='Nome no Contracheque')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Cargo')),
                ('admission_date', models.CharField(blank=True, max_length=20, verbose_name='Data de Admissão')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Departamento')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salário Base')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Proventos')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Descontos')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Líquido')),
                ('fgts_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Base FGTS')),
                ('fgts_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Depósito FGTS')),
                ('irrf_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Base IRRF')),
                ('inss_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Base INSS')),
                ('earnings_detail', models.JSONField(blank=True, default=list, verbose_name='Proventos (detalhado)')),
                ('deductions_detail', models.JSONField(blank=True, default=list, verbose_name='Descontos (detalhado)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Contracheque',
                'verbose_name_plural': 'Contracheques',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
