# Generated by Django 5.2.5 on 2026-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='pdf_page_number',
            field=models.PositiveIntegerField(blank=True, help_text='Número da página (0-indexed) do funcionário no PDF original', null=True, verbose_name='Página no PDF original'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='signature_hash',
            field=models.CharField(blank=True, help_text='SHA-256 do conteúdo assinado para garantir integridade', max_length=64, verbose_name='Hash de verificação'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='signature_image',
            field=models.TextField(blank=True, help_text='Imagem da assinatura em base64 (PNG)', verbose_name='Assinatura (base64)'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='signature_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da assinatura'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='signature_user_agent',
            field=models.TextField(blank=True, verbose_name='User-Agent da assinatura'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assinado em'),
        ),
    ]
