# Generated by Django 5.2.5 on 2026-03-06 17:30

import contracheque.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracheque', '0002_payslip_pdf_page_number_payslip_signature_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_year', models.PositiveIntegerField(verbose_name='Ano-Calendário')),
                ('exercise_year', models.PositiveIntegerField(verbose_name='Exercício')),
                ('pdf_file', models.FileField(upload_to=contracheque.models.upload_income_report_pdf, verbose_name='Arquivo PDF')),
                ('employee_name', models.CharField(blank=True, max_length=200, verbose_name='Nome no Informe')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('total_rendimentos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total dos rendimentos')),
                ('contribuicao_previdenciaria', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Contribuição previdenciária oficial')),
                ('contribuicao_previdencia_privada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Contribuição previdência privada/FAPI')),
                ('pensao_alimenticia', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pensão alimentícia')),
                ('irrf', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IRRF')),
                ('parcela_isenta_aposentadoria', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Parcela isenta aposentadoria')),
                ('parcela_isenta_13_aposentadoria', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Parcela isenta 13º aposentadoria')),
                ('diarias_ajuda_custo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Diárias e ajuda de custo')),
                ('pensao_moletia_grave', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pensão por moléstia grave')),
                ('lucros_dividendos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Lucros e dividendos')),
                ('valores_titular_socio', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valores pagos titular/sócio')),
                ('indenizacao_rescisao', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Indenizações rescisão')),
                ('juros_mora', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Juros de mora')),
                ('outros_isentos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Outros isentos')),
                ('decimo_terceiro', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='13º salário')),
                ('irrf_13', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IRRF sobre 13º')),
                ('outros_exclusivos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Outros exclusivos')),
                ('pdf_page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Página no PDF original')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_reports_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_reports', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Informe de Rendimentos',
                'verbose_name_plural': 'Informes de Rendimentos',
                'ordering': ['-base_year'],
                'unique_together': {('user', 'base_year')},
            },
        ),
    ]
