# Generated by Django 5.2.5 on 2026-05-05 00:00

import contracheque.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracheque', '0003_incomereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=contracheque.models.upload_payslip_pdf, verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='incomereport',
            name='pdf_file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=contracheque.models.upload_income_report_pdf, verbose_name='Arquivo PDF'),
        ),
    ]
