# Generated by Django 4.2.16 on 2025-10-13 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_add_uniform_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('this_week', 'Esta Semana'), ('weekdays_month', 'Dias Úteis do Mês'), ('weekends_month', 'Fins de Semana do Mês'), ('daily', 'Todos os Dias'), ('custom', 'Datas Personalizadas')], default='custom', max_length=20, verbose_name='Tipo de Agendamento')),
                ('custom_dates', models.JSONField(blank=True, default=list, help_text='Lista de datas no formato YYYY-MM-DD', verbose_name='Datas Personalizadas')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído por')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído para')),
            ],
            options={
                'verbose_name': 'Atribuição de Checklist',
                'verbose_name_plural': 'Atribuições de Checklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField(verbose_name='Data de Execução')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('overdue', 'Atrasado')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='checklists.checklistassignment', verbose_name='Atribuição')),
            ],
            options={
                'verbose_name': 'Execução de Checklist',
                'verbose_name_plural': 'Execuções de Checklist',
                'ordering': ['-execution_date'],
                'unique_together': {('assignment', 'execution_date')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Checklist')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('sector', models.ForeignKey(help_text='Setor que pode usar este checklist', on_delete=django.db.models.deletion.CASCADE, to='users.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Template de Checklist',
                'verbose_name_plural': 'Templates de Checklist',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatória')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='checklists.checklisttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Tarefa de Checklist',
                'verbose_name_plural': 'Tarefas de Checklist',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='checklistassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklisttemplate', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='ChecklistTaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='checklists.checklistexecution', verbose_name='Execução')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklisttask', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Execução de Tarefa',
                'verbose_name_plural': 'Execuções de Tarefas',
                'ordering': ['task__order'],
                'unique_together': {('execution', 'task')},
            },
        ),
    ]
