# Generated by Django 5.2.7 on 2025-10-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttask',
            name='instruction_image',
            field=models.ImageField(blank=True, help_text='Imagem explicativa de como executar a tarefa', null=True, upload_to='checklists/instructions/images/', verbose_name='Imagem de Instrução'),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='instruction_video',
            field=models.FileField(blank=True, help_text='Vídeo explicativo de como executar a tarefa (MP4, AVI, MOV)', null=True, upload_to='checklists/instructions/videos/', verbose_name='Vídeo de Instrução'),
        ),
    ]
