# Generated by Django 5.2.7 on 2025-10-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklisttask_instruction_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistexecution',
            options={'ordering': ['-execution_date', 'period'], 'verbose_name': 'Execução de Checklist', 'verbose_name_plural': 'Execuções de Checklist'},
        ),
        migrations.AlterUniqueTogether(
            name='checklistexecution',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checklistassignment',
            name='period',
            field=models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('both', 'Manhã e Tarde')], default='both', help_text='Período do dia para execução do checklist', max_length=10, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='checklistexecution',
            name='period',
            field=models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde')], default='morning', help_text='Período do dia (Manhã ou Tarde)', max_length=10, verbose_name='Período'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistexecution',
            unique_together={('assignment', 'execution_date', 'period')},
        ),
    ]
