# Generated by Django 5.2.7 on 2025-10-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_add_period_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistexecution',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado para Aprovação em'),
        ),
        migrations.AddField(
            model_name='checklisttaskexecution',
            name='evidence_image',
            field=models.ImageField(blank=True, help_text='Foto como prova de execução da tarefa', null=True, upload_to='checklists/evidences/images/', verbose_name='Imagem de Evidência'),
        ),
        migrations.AddField(
            model_name='checklisttaskexecution',
            name='evidence_video',
            field=models.FileField(blank=True, help_text='Vídeo como prova de execução da tarefa', null=True, upload_to='checklists/evidences/videos/', verbose_name='Vídeo de Evidência'),
        ),
        migrations.AlterField(
            model_name='checklistexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('overdue', 'Atrasado'), ('awaiting_approval', 'Aguardando Aprovação')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
