# Generated by Django 5.2.7 on 2025-10-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_add_evidence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttask',
            name='instruction_document',
            field=models.FileField(blank=True, help_text='Documento de apoio (PDF, DOC, XLS, PPT, etc.)', null=True, upload_to='checklists/instructions/documents/', verbose_name='Documento de Instrução'),
        ),
    ]
