# Generated by Django 4.2.16 on 2025-11-04 13:36

import checklists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_checklisttask_instruction_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttaskexecution',
            name='evidence_image',
            field=models.ImageField(blank=True, help_text='Foto como prova de execução da tarefa', null=True, upload_to=checklists.models.upload_checklist_evidence_image, verbose_name='Imagem de Evidência'),
        ),
        migrations.AlterField(
            model_name='checklisttaskexecution',
            name='evidence_video',
            field=models.FileField(blank=True, help_text='Vídeo como prova de execução da tarefa', null=True, upload_to=checklists.models.upload_checklist_evidence_video, verbose_name='Vídeo de Evidência'),
        ),
    ]
