# Generated by Django 5.2.7 on 2025-11-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_alter_checklisttaskexecution_evidence_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTaskInstructionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('document', 'Documento')], max_length=10, verbose_name='Tipo de Mídia')),
                ('file', models.FileField(upload_to='checklists/instructions/', verbose_name='Arquivo')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título/Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_media', to='checklists.checklisttask', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Mídia de Instrução',
                'verbose_name_plural': 'Mídias de Instrução',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
