# Generated by Django 5.2.7 on 2025-11-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_checklisttaskinstructionmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTaskEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], max_length=10, verbose_name='Tipo de Evidência')),
                ('file', models.FileField(upload_to='checklists/evidences/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='checklists.checklisttaskexecution', verbose_name='Execução da Tarefa')),
            ],
            options={
                'verbose_name': 'Evidência de Tarefa',
                'verbose_name_plural': 'Evidências de Tarefa',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
