# Generated by Django 4.2.16 on 2025-11-19 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklists', '0008_checklisttaskevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttask',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de pontos que esta tarefa vale', verbose_name='Pontos'),
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='task_type',
            field=models.CharField(choices=[('normal', 'Tarefa Normal'), ('yes_no', 'Pergunta Sim/Não')], default='normal', help_text='Tipo de tarefa: normal (checkbox) ou pergunta sim/não', max_length=10, verbose_name='Tipo de Tarefa'),
        ),
        migrations.AddField(
            model_name='checklisttaskexecution',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Motivo da aprovação/reprovação', verbose_name='Observações da Aprovação'),
        ),
        migrations.AddField(
            model_name='checklisttaskexecution',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Reprovada')], default='pending', max_length=20, verbose_name='Status de Aprovação'),
        ),
        migrations.AddField(
            model_name='checklisttaskexecution',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em'),
        ),
        migrations.AddField(
            model_name='checklisttaskexecution',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='checklisttaskexecution',
            name='yes_no_answer',
            field=models.BooleanField(blank=True, help_text='True = Sim, False = Não, None = Não respondida', null=True, verbose_name='Resposta Sim/Não'),
        ),
    ]
