# Generated by Django 5.2.7 on 2025-11-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_checklisttask_points_checklisttask_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttaskexecution',
            name='dropdown_answer',
            field=models.CharField(blank=True, choices=[('yes', 'Sim'), ('no', 'Não'), ('not_applicable', 'Não se Aplica')], help_text='Resposta para perguntas do tipo menu suspenso', max_length=20, null=True, verbose_name='Resposta Menu Suspenso'),
        ),
        migrations.AlterField(
            model_name='checklisttask',
            name='task_type',
            field=models.CharField(choices=[('normal', 'Tarefa Normal'), ('yes_no', 'Pergunta Sim/Não'), ('dropdown', 'Menu Suspenso (Sim/Não/Não se Aplica)')], default='normal', help_text='Tipo de tarefa: normal (checkbox) ou pergunta sim/não', max_length=10, verbose_name='Tipo de Tarefa'),
        ),
    ]
