# Generated by Django 5.2.7 on 2025-12-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_checklisttaskexecution_dropdown_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttaskevidence',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Original do Arquivo'),
        ),
        migrations.AlterField(
            model_name='checklisttaskevidence',
            name='evidence_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('document', 'Documento')], max_length=10, verbose_name='Tipo de Evidência'),
        ),
    ]
