# Generated by Django 4.2.16 on 2026-02-04 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_hr_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklists', '0011_add_document_support_to_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPendingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('this_week', 'Esta Semana'), ('weekdays_month', 'Dias Úteis do Mês'), ('weekends_month', 'Fins de Semana do Mês'), ('daily', 'Todos os Dias'), ('custom', 'Datas Personalizadas')], default='custom', max_length=20, verbose_name='Tipo de Agendamento')),
                ('period', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('both', 'Manhã e Tarde')], default='both', max_length=10, verbose_name='Período')),
                ('custom_dates', models.JSONField(blank=True, default=list, verbose_name='Datas Personalizadas')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Aprovação/Rejeição')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pending_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado/Rejeitado por')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_checklist_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_checklist_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído para')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklisttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Atribuição Pendente',
                'verbose_name_plural': 'Atribuições Pendentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistAssignmentApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_approvers_added', to=settings.AUTH_USER_MODEL, verbose_name='Adicionado por')),
                ('sector', models.ForeignKey(blank=True, help_text='Se vazio, pode aprovar de todos os setores', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_approvers', to='users.sector', verbose_name='Setor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_approver_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador')),
            ],
            options={
                'verbose_name': 'Aprovador de Atribuição',
                'verbose_name_plural': 'Aprovadores de Atribuição',
                'ordering': ['user__first_name', 'user__last_name'],
                'unique_together': {('user', 'sector')},
            },
        ),
    ]
