# Generated by Django 5.2.5 on 2025-08-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('webhook_url', models.URLField(blank=True, verbose_name='URL do Webhook')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requer Aprovação')),
                ('default_description', models.TextField(blank=True, verbose_name='Descrição Padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['sector__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação do Usuário'), ('FECHADO', 'Fechado'), ('REABERTO', 'Reaberto')], default='ABERTO', max_length=25, verbose_name='Status')),
                ('solution', models.TextField(blank=True, verbose_name='Solução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requer Aprovação')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=25, verbose_name='Status Anterior')),
                ('new_status', models.CharField(max_length=25, verbose_name='Novo Status')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Log do Chamado',
                'verbose_name_plural': 'Logs dos Chamados',
                'ordering': ['-created_at'],
            },
        ),
    ]
