# Generated by Django 5.2.5 on 2025-08-28 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Limite'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=15, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solution_time_hours',
            field=models.IntegerField(default=24, verbose_name='Tempo para Solução (horas)'),
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.URLField(verbose_name='URL do Webhook')),
                ('event', models.CharField(choices=[('TICKET_CREATED', 'Chamado Criado'), ('TICKET_UPDATED', 'Chamado Atualizado'), ('TICKET_RESOLVED', 'Chamado Resolvido'), ('TICKET_CLOSED', 'Chamado Fechado'), ('CATEGORY_CREATED', 'Categoria Criada'), ('USER_CREATED', 'Usuário Criado')], max_length=20, verbose_name='Evento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Headers Customizados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.category', verbose_name='Categoria (filtro)')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sector', verbose_name='Setor (filtro)')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['name'],
            },
        ),
    ]
