# Generated by Django 5.2.5 on 2025-08-28 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_due_date_ticket_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído para'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='comment_type',
            field=models.CharField(choices=[('COMMENT', 'Comentário'), ('FOLLOW_UP', 'Acompanhamento'), ('ASSIGNMENT', 'Atribuição'), ('STATUS_CHANGE', 'Mudança de Status'), ('ASSUMPTION', 'Assumir Chamado')], default='COMMENT', max_length=15, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atribuído em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_assignments', to='tickets.ticket', verbose_name='Chamado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atribuição Adicional',
                'verbose_name_plural': 'Atribuições Adicionais',
                'ordering': ['-assigned_at'],
                'unique_together': {('ticket', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TicketView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Visualizado em')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tickets.ticket', verbose_name='Chamado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Visualização do Chamado',
                'verbose_name_plural': 'Visualizações dos Chamados',
                'ordering': ['-viewed_at'],
                'unique_together': {('ticket', 'user')},
            },
        ),
    ]
