# Generated by Django 5.2.5 on 2025-09-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketcomment_assigned_to_ticketcomment_comment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Denúncia Anônima'),
        ),
    ]
