# Generated by Django 5.2.5 on 2025-09-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_solution_time_hours',
            field=models.IntegerField(default=24, verbose_name='Tempo Padrão para Solução (horas)'),
        ),
    ]
