# Generated by Django 5.2.5 on 2025-09-11 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_add_default_solution_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação do Usuário'), ('FECHADO', 'Fechado'), ('REABERTO', 'Reaberto'), ('REJEITADO', 'Rejeitado')], default='ABERTO', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[('TICKET_CREATED', 'Chamado Criado'), ('TICKET_UPDATED', 'Chamado Atualizado'), ('TICKET_RESOLVED', 'Chamado Resolvido'), ('TICKET_CLOSED', 'Chamado Fechado'), ('CATEGORY_CREATED', 'Categoria Criada'), ('USER_CREATED', 'Usuário Criado'), ('APPROVAL_REQUEST', 'Solicitação de Aprovação'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], max_length=20, verbose_name='Evento'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Decidido em')),
                ('approval_step', models.PositiveIntegerField(verbose_name='Etapa de Aprovação')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aprovador')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_approvals', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Aprovação de Ordem de Compra',
                'verbose_name_plural': 'Aprovações de Ordem de Compra',
                'ordering': ['-created_at'],
                'unique_together': {('ticket', 'approver', 'approval_step')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Máximo de Aprovação')),
                ('approval_order', models.PositiveIntegerField(help_text='1 = Primeiro aprovador, 2 = Segundo aprovador, etc.', verbose_name='Ordem de Aprovação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_approval_config', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aprovador de Ordem de Compra',
                'verbose_name_plural': 'Aprovadores de Ordem de Compra',
                'ordering': ['approval_order'],
                'unique_together': {('approval_order',)},
            },
        ),
    ]
