# Generated by Django 5.2.5 on 2025-09-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_status_alter_webhook_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[('TICKET_CREATED', 'Chamado Criado'), ('TICKET_UPDATED', 'Chamado Atualizado'), ('TICKET_RESOLVED', 'Chamado Resolvido'), ('TICKET_CLOSED', 'Chamado Fechado'), ('CATEGORY_CREATED', 'Categoria Criada'), ('USER_CREATED', 'Usuário Criado'), ('APPROVAL_REQUEST', 'Solicitação de Aprovação'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('COMMUNICATION_CREATED', 'Comunicado Criado'), ('COMMUNICATION_UPDATED', 'Comunicado Atualizado')], max_length=25, verbose_name='Evento'),
        ),
    ]
