# Generated by Django 5.2.5 on 2025-09-16 18:54

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_add_communication_webhook_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.utils.upload_ticket_attachment, verbose_name='Arquivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome Original do Arquivo')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('content_type', models.CharField(blank=True, max_length=255, verbose_name='Tipo de Conteúdo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Chamado')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo do Chamado',
                'verbose_name_plural': 'Anexos dos Chamados',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
