# Generated by Django 4.2.16 on 2025-11-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='store_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loja/Local'),
        ),
    ]
