# Generated by Django 5.2.7 on 2025-11-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment_type',
            field=models.CharField(choices=[('COMMENT', 'Comentário'), ('FOLLOW_UP', 'Acompanhamento'), ('ASSIGNMENT', 'Atribuição'), ('STATUS_CHANGE', 'Mudança de Status'), ('ASSUMPTION', 'Assumir Chamado'), ('PRIORITY_CHANGE', 'Mudança de Prioridade')], default='COMMENT', max_length=15, verbose_name='Tipo'),
        ),
    ]
