# Generated by Django 5.2.5 on 2026-08-19 17:56

import core.storage
import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticketcomment_comment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='detalhe_encerramento',
            field=models.TextField(blank=True, help_text='Explicação do porquê o chamado foi encerrado sem ser resolvido.', verbose_name='Detalhe do encerramento'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='encerrado_sem_solucao_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Encerrado sem solução em'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='encerrado_sem_solucao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_encerrados_sem_solucao', to=settings.AUTH_USER_MODEL, verbose_name='Encerrado sem solução por'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='motivo_encerramento',
            field=models.CharField(blank=True, choices=[('CUSTO', 'Custo inviável / orçamento reprovado'), ('SEM_NECESSIDADE', 'Sem necessidade no momento'), ('ADIADO', 'Adiado para outro período'), ('DUPLICADO', 'Chamado duplicado'), ('FORA_ESCOPO', 'Fora do escopo da equipe'), ('SEM_RETORNO', 'Sem retorno do solicitante'), ('RESOLVIDO_FORA', 'Resolvido por fora do chamado'), ('OUTRO', 'Outro motivo')], max_length=20, verbose_name='Motivo do encerramento sem solução'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação do Usuário'), ('FECHADO', 'Fechado'), ('ENCERRADO_SEM_SOLUCAO', 'Encerrado sem solução'), ('REABERTO', 'Reaberto'), ('REJEITADO', 'Rejeitado')], default='ABERTO', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=core.utils.upload_ticket_attachment, verbose_name='Arquivo'),
        ),
    ]
