# Generated by Django 5.2.5 on 2026-10-01 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticketcomment_excluido_em_ticketcomment_excluido_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True, verbose_name='Etiqueta')),
                ('cor', models.CharField(default='#6366F1', help_text='Em hexadecimal (#RRGGBB). A etiqueta aparece com esta cor na lista.', max_length=7, verbose_name='Cor')),
                ('descricao', models.CharField(blank=True, max_length=160, verbose_name='Para que serve')),
                ('ativa', models.BooleanField(default=True, verbose_name='Disponível para uso')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
            ],
            options={
                'verbose_name': 'Etiqueta de chamado',
                'verbose_name_plural': 'Etiquetas de chamado',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tickets.tickettag', verbose_name='Etiquetas'),
        ),
    ]
