# Generated by Django 4.2.16 on 2026-05-25 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaD1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_da_venda', models.CharField(max_length=60, verbose_name='Número da venda')),
                ('produto', models.CharField(blank=True, max_length=200, verbose_name='Produto / plano')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF do cliente')),
                ('numero_acesso', models.CharField(blank=True, max_length=60, verbose_name='Número de acesso')),
                ('data_da_venda', models.DateField(blank=True, null=True, verbose_name='Data da venda')),
                ('pilar', models.CharField(blank=True, max_length=40, verbose_name='Pilar')),
                ('vendedor', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Vendedor')),
                ('pdv', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Loja (PDV)')),
                ('servicos', models.CharField(blank=True, max_length=200, verbose_name='Serviços')),
                ('status', models.CharField(choices=[('pendente', 'Pendente análise'), ('conformidade', 'Em conformidade'), ('divergente', 'Divergente')], db_index=True, default='pendente', max_length=20)),
                ('tipo_divergencia', models.CharField(blank=True, choices=[('venda_inexistente', 'Venda inexistente (Excluir venda)'), ('valores_incorretos', 'Valores incorretos (Corrigir receita)'), ('plano_incorreto', 'Plano incorreto (Corrigir plano)'), ('linha_incorreta', 'Linha incorreta (Alterar n. de acesso)'), ('divergencia_cadastral', 'Divergência cadastral (Alterar cadastro)'), ('movimento_inelegivel', 'Movimento inelegível (Excluir venda)')], max_length=30)),
                ('penalidade', models.CharField(choices=[('nenhuma', 'Nenhuma'), ('leve', 'Leve'), ('media', 'Média'), ('grave', 'Grave')], default='nenhuma', max_length=10)),
                ('acao_realizada_no_go', models.BooleanField(default=False, verbose_name='Alteração feita no Vivo GO')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação da Ilha')),
                ('marcado_em', models.DateTimeField(blank=True, null=True)),
                ('acordo_status', models.CharField(choices=[('pendente', 'Aguardando gerente'), ('de_acordo', 'De acordo'), ('contestado', 'Contestado'), ('expirado', 'Expirado (48h)')], db_index=True, default='pendente', max_length=15)),
                ('acordo_respondido_em', models.DateTimeField(blank=True, null=True)),
                ('acordo_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('acordo_respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_d1_respondidas', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='validad1.vendad1')),
                ('marcado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_d1_marcadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda D-1',
                'verbose_name_plural': 'Vendas D-1',
                'ordering': ['-data_da_venda', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendaD1Contestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo da contestação')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('procedente', 'Procedente (ajustar no GO)'), ('improcedente', 'Improcedente')], default='aberta', max_length=15)),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta da Ilha')),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aberto_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestacoes_d1_abertas', to=settings.AUTH_USER_MODEL)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestacoes', to='validad1.vendad1')),
            ],
            options={
                'ordering': ['-aberto_em'],
            },
        ),
        migrations.CreateModel(
            name='VendaD1ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='validad1.vendad1contestacao')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='vendad1',
            index=models.Index(fields=['status'], name='validad1_ve_status_2d7b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendad1',
            index=models.Index(fields=['acordo_status'], name='validad1_ve_acordo__a2c6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='vendad1',
            index=models.Index(fields=['data_da_venda'], name='validad1_ve_data_da_2bee29_idx'),
        ),
    ]
