# Generated by Django 5.2.5 on 2026-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validad1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendad1contestacao',
            name='last_opener_view_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendad1',
            name='acordo_status',
            field=models.CharField(choices=[('pendente', 'Aguardando'), ('de_acordo', 'De acordo'), ('contestado', 'Contestado'), ('expirado', 'Expirado (48h)')], db_index=True, default='pendente', max_length=15),
        ),
    ]
