# Generated by Django 5.2.5 on 2026-05-26 16:20

import django.db.models.deletion
import validad1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validad1', '0002_vendad1contestacao_last_opener_view_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendad1chatmessage',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='VendaD1ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=validad1.models._vd1_attachment_upload_to)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='validad1.vendad1chatmessage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
