# Generated by Django 4.2.16 on 2026-05-29 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('validad1', '0004_vendad1_penalidade_detalhe'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendad1',
            name='numero_protocolo',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número do protocolo'),
        ),
        migrations.CreateModel(
            name='VendaD1SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created', models.PositiveIntegerField(default=0)),
                ('total_in_source', models.PositiveIntegerField(default=0)),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_d1_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sincronização D-1',
                'verbose_name_plural': 'Sincronizações D-1',
                'ordering': ['-synced_at'],
            },
        ),
    ]
