# Generated by Django 5.1.6 on 2025-09-30 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_add_uniform_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('icon', models.CharField(default='fas fa-bell', max_length=50, verbose_name='Ícone Font Awesome')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Notificação',
                'verbose_name_plural': 'Categorias de Notificações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'Sistema'), ('TICKET', 'Chamado'), ('COMMUNICATION', 'Comunicado'), ('TASK', 'Tarefa'), ('CUSTOM', 'Personalizada')], default='CUSTOM', max_length=20, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('icon', models.CharField(default='fas fa-bell', max_length=50, verbose_name='Ícone')),
                ('action_url', models.URLField(blank=True, verbose_name='URL da Ação')),
                ('action_text', models.CharField(blank=True, max_length=50, verbose_name='Texto da Ação')),
                ('send_to_all', models.BooleanField(default=False, verbose_name='Enviar para Todos')),
                ('schedule_for', models.DateTimeField(blank=True, null=True, verbose_name='Agendar para')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Agendada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Enviado')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationcategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('target_sectors', models.ManyToManyField(blank=True, to='users.sector', verbose_name='Setores Alvo')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Alvo')),
            ],
            options={
                'verbose_name': 'Notificação Push',
                'verbose_name_plural': 'Notificações Push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Token do Dispositivo')),
                ('device_type', models.CharField(choices=[('WEB', 'Web Browser'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='WEB', max_length=10, verbose_name='Tipo do Dispositivo')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Informações do Dispositivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token do Dispositivo',
                'verbose_name_plural': 'Tokens dos Dispositivos',
                'ordering': ['-last_used'],
                'unique_together': {('user', 'token')},
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('is_clicked', models.BooleanField(default=False, verbose_name='Clicada')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Clicada em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='notifications.pushnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação do Usuário',
                'verbose_name_plural': 'Notificações dos Usuários',
                'ordering': ['-created_at'],
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
