# Generated by Django 4.2.16 on 2025-12-18 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='Notificações In-App')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Notificações Push/Browser')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Notificações por Email')),
                ('ticket_created', models.BooleanField(default=True, verbose_name='Novos Chamados')),
                ('ticket_assigned', models.BooleanField(default=True, verbose_name='Atribuição de Chamados')),
                ('ticket_status_changed', models.BooleanField(default=True, verbose_name='Mudança de Status')),
                ('ticket_comment', models.BooleanField(default=True, verbose_name='Novos Comentários')),
                ('communication_new', models.BooleanField(default=True, verbose_name='Novos Comunicados')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='Horário Silencioso')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Início do Silêncio')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fim do Silêncio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificações',
            },
        ),
    ]
