# Generated by Django 4.2.16 on 2025-12-29 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_add_notification_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruepushSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.CharField(max_length=255, unique=True, verbose_name='ID do Assinante Truepush')),
                ('device_type', models.CharField(default='web', max_length=50, verbose_name='Tipo de Dispositivo')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navegador')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truepush_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinante Truepush',
                'verbose_name_plural': 'Assinantes Truepush',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TruepushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('url', models.URLField(blank=True, verbose_name='URL de Destino')),
                ('segment_id', models.CharField(blank=True, max_length=255, verbose_name='ID do Segmento')),
                ('sent_to_all', models.BooleanField(default=True, verbose_name='Enviado para Todos')),
                ('success', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Quantidade Enviada')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Resposta da API')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truepush_notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Log de Notificação Truepush',
                'verbose_name_plural': 'Logs de Notificações Truepush',
                'ordering': ['-created_at'],
            },
        ),
    ]
