# Generated by Django 4.2.16 on 2025-12-29 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_truepush_integration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truepushnotificationlog',
            options={'verbose_name': 'Log Truepush (Legado)', 'verbose_name_plural': 'Logs Truepush (Legado)'},
        ),
        migrations.AlterModelOptions(
            name='truepushsubscriber',
            options={'verbose_name': 'Assinante Truepush (Legado)', 'verbose_name_plural': 'Assinantes Truepush (Legado)'},
        ),
        migrations.AlterField(
            model_name='truepushnotificationlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='truepushnotificationlog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='truepushnotificationlog',
            name='response_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='truepushnotificationlog',
            name='segment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='truepushnotificationlog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truepush_notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='truepushnotificationlog',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='truepushnotificationlog',
            name='sent_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='truepushnotificationlog',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='truepushnotificationlog',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='truepushnotificationlog',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='truepushsubscriber',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='truepushsubscriber',
            name='device_type',
            field=models.CharField(default='web', max_length=50),
        ),
        migrations.AlterField(
            model_name='truepushsubscriber',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='truepushsubscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='truepushsubscriber',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='OneSignalPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255, unique=True, verbose_name='Player ID OneSignal')),
                ('device_type', models.CharField(default='web', max_length=50, verbose_name='Tipo de Dispositivo')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navegador')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onesignal_players', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Player OneSignal',
                'verbose_name_plural': 'Players OneSignal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneSignalNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL de Destino')),
                ('segment', models.CharField(blank=True, max_length=255, verbose_name='Segmento')),
                ('sent_to_all', models.BooleanField(default=True, verbose_name='Enviado para Todos')),
                ('success', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Quantidade Enviada')),
                ('notification_id', models.CharField(blank=True, max_length=255, verbose_name='ID da Notificação OneSignal')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Resposta da API')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onesignal_notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Log de Notificação OneSignal',
                'verbose_name_plural': 'Logs de Notificações OneSignal',
                'ordering': ['-created_at'],
            },
        ),
    ]
