# Generated by Django 5.2.5 on 2026-01-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_onesignal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='onesignalplayer',
            name='email',
            field=models.EmailField(blank=True, help_text='Email registrado no OneSignal para notificações', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='onesignalplayer',
            name='external_user_id',
            field=models.CharField(blank=True, help_text='ID do usuário no sistema (usado via OneSignal.login())', max_length=100, verbose_name='External User ID'),
        ),
        migrations.AddField(
            model_name='onesignalplayer',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone registrado no OneSignal (formato E.164)', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='onesignalplayer',
            name='player_id',
            field=models.CharField(help_text='ID único do dispositivo no OneSignal', max_length=255, unique=True, verbose_name='Player ID OneSignal'),
        ),
    ]
