# Generated by Django 5.2.5 on 2026-09-15 17:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Inativo, o modelo sai da lista de aplicar, mas continua guardado.', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Modelo de rotina',
                'verbose_name_plural': 'Modelos de rotina',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RotinaGerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True, help_text='Desativada, a rotina some do menu da pessoa e os avisos param.', verbose_name='Ativa')),
                ('pode_criar', models.BooleanField(default=False, help_text='Deixa a pessoa acrescentar (e apagar) atividades dela na semana.', verbose_name='Pode criar atividades próprias')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizada por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('modelo_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotinas', to='rotina.modelorotina', verbose_name='Modelo aplicado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rotina_gerencial', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Rotina gerencial',
                'verbose_name_plural': 'Rotinas gerenciais',
            },
        ),
        migrations.CreateModel(
            name='AtividadeRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')], verbose_name='Dia da semana')),
                ('inicio', models.TimeField(verbose_name='Início')),
                ('fim', models.TimeField(verbose_name='Fim')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Pode ter links: eles ficam clicáveis na rotina.', verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('RESULTADO', 'Tem influência sobre o resultado a curto e médio prazo'), ('EQUIPE', 'Tem influência no dia a dia da equipe'), ('COMPLEMENTAR', 'Atividade complementar')], default='COMPLEMENTAR', max_length=20, verbose_name='Categoria')),
                ('bloqueada', models.BooleanField(default=False, help_text='Travada, a pessoa não consegue mover a atividade nem mudar a duração.', verbose_name='Horário travado')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('criada_pela_pessoa', models.BooleanField(default=False, help_text='Só estas a pessoa pode renomear ou apagar — e só se a rotina permitir criar.', verbose_name='Criada pela própria pessoa')),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='rotina.rotinagerencial', verbose_name='Rotina')),
            ],
            options={
                'verbose_name': 'Atividade da rotina',
                'verbose_name_plural': 'Atividades da rotina',
                'ordering': ['dia_semana', 'inicio', 'fim', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvisoRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Dia')),
                ('titulo', models.CharField(blank=True, max_length=150, verbose_name='Título avisado')),
                ('inicio', models.TimeField(blank=True, null=True, verbose_name='Início avisado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Avisado em')),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='rotina.atividaderotina', verbose_name='Atividade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_rotina', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Aviso de atividade',
                'verbose_name_plural': 'Avisos de atividade',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('atividade', 'data'), name='rotina_aviso_um_por_atividade_e_dia')],
            },
        ),
        migrations.CreateModel(
            name='AtividadeModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')], verbose_name='Dia da semana')),
                ('inicio', models.TimeField(verbose_name='Início')),
                ('fim', models.TimeField(verbose_name='Fim')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Pode ter links: eles ficam clicáveis na rotina.', verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('RESULTADO', 'Tem influência sobre o resultado a curto e médio prazo'), ('EQUIPE', 'Tem influência no dia a dia da equipe'), ('COMPLEMENTAR', 'Atividade complementar')], default='COMPLEMENTAR', max_length=20, verbose_name='Categoria')),
                ('bloqueada', models.BooleanField(default=False, help_text='Travada, a pessoa não consegue mover a atividade nem mudar a duração.', verbose_name='Horário travado')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='rotina.modelorotina', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Atividade do modelo',
                'verbose_name_plural': 'Atividades do modelo',
                'ordering': ['dia_semana', 'inicio', 'fim', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='rotina_atividademodelo_fim_depois_do_inicio'), models.CheckConstraint(condition=models.Q(('dia_semana__lte', 5)), name='rotina_atividademodelo_segunda_a_sabado'), models.CheckConstraint(condition=models.Q(('fim__lte', datetime.time(23, 0)), ('inicio__gte', datetime.time(5, 0))), name='rotina_atividademodelo_entre_5h_e_23h')],
            },
        ),
        migrations.AddConstraint(
            model_name='atividaderotina',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='rotina_atividaderotina_fim_depois_do_inicio'),
        ),
        migrations.AddConstraint(
            model_name='atividaderotina',
            constraint=models.CheckConstraint(condition=models.Q(('dia_semana__lte', 5)), name='rotina_atividaderotina_segunda_a_sabado'),
        ),
        migrations.AddConstraint(
            model_name='atividaderotina',
            constraint=models.CheckConstraint(condition=models.Q(('fim__lte', datetime.time(23, 0)), ('inicio__gte', datetime.time(5, 0))), name='rotina_atividaderotina_entre_5h_e_23h'),
        ),
    ]
