# Generated by Django 5.2.5 on 2026-09-16 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0002_modelo_padrao_loja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='avisorotina',
            name='rotina_aviso_um_por_atividade_e_dia',
        ),
        migrations.AddField(
            model_name='avisorotina',
            name='tipo',
            field=models.CharField(choices=[('LEMBRETE', 'Lembrete (minutos antes)'), ('INICIO', 'Início da atividade')], default='INICIO', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddConstraint(
            model_name='avisorotina',
            constraint=models.UniqueConstraint(fields=('atividade', 'data', 'tipo'), name='rotina_aviso_um_por_atividade_dia_e_tipo'),
        ),
    ]
