# Generated by Django 5.2.5 on 2026-09-16 21:46
#
# Domingo e WhatsApp na rotina gerencial.
# - `com_domingo` (modelo e rotina) nasce desligado: nenhuma semana existente muda.
# - A trava do banco passa de "segunda a sábado" (dia <= 5) para "segunda a domingo" (dia <= 6).
# - `avisar_whatsapp` nasce LIGADO nas rotinas que já existem: depois do migrate, quem tem
#   rotina ativa e telefone no cadastro passa a receber o lembrete no WhatsApp.
# - AvisoWhatsApp: o registro (um por atividade e dia) que impede mandar duas vezes.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0003_aviso_lembrete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Dia')),
                ('tipo', models.CharField(choices=[('LEMBRETE', 'Lembrete (minutos antes)'), ('INICIO', 'Início da atividade')], default='LEMBRETE', max_length=10, verbose_name='Momento')),
                ('titulo', models.CharField(blank=True, max_length=150, verbose_name='Título avisado')),
                ('inicio', models.TimeField(blank=True, null=True, verbose_name='Início avisado')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('detalhe', models.CharField(blank=True, max_length=255, verbose_name='Retorno do envio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
            ],
            options={
                'verbose_name': 'Aviso por WhatsApp',
                'verbose_name_plural': 'Avisos por WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='atividademodelo',
            name='rotina_atividademodelo_segunda_a_sabado',
        ),
        migrations.RemoveConstraint(
            model_name='atividaderotina',
            name='rotina_atividaderotina_segunda_a_sabado',
        ),
        migrations.AddField(
            model_name='modelorotina',
            name='com_domingo',
            field=models.BooleanField(default=False, help_text='Ligado, a semana do modelo vai de segunda a domingo. Quem recebe o modelo recebe o domingo junto.', verbose_name='Semana com domingo'),
        ),
        migrations.AddField(
            model_name='rotinagerencial',
            name='avisar_whatsapp',
            field=models.BooleanField(default=True, help_text='Manda o lembrete de cada atividade para o WhatsApp do cadastro da pessoa (campo Telefone), minutos antes de começar.', verbose_name='Avisar por WhatsApp'),
        ),
        migrations.AddField(
            model_name='rotinagerencial',
            name='com_domingo',
            field=models.BooleanField(default=False, help_text='Ligado, a semana da pessoa vai de segunda a domingo, com os avisos do domingo.', verbose_name='Semana com domingo'),
        ),
        migrations.AlterField(
            model_name='atividademodelo',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='atividaderotina',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana'),
        ),
        migrations.AddConstraint(
            model_name='atividademodelo',
            constraint=models.CheckConstraint(condition=models.Q(('dia_semana__lte', 6)), name='rotina_atividademodelo_segunda_a_domingo'),
        ),
        migrations.AddConstraint(
            model_name='atividaderotina',
            constraint=models.CheckConstraint(condition=models.Q(('dia_semana__lte', 6)), name='rotina_atividaderotina_segunda_a_domingo'),
        ),
        migrations.AddField(
            model_name='avisowhatsapp',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_whatsapp', to='rotina.atividaderotina', verbose_name='Atividade'),
        ),
        migrations.AddField(
            model_name='avisowhatsapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_whatsapp_rotina', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa'),
        ),
        migrations.AddConstraint(
            model_name='avisowhatsapp',
            constraint=models.UniqueConstraint(fields=('atividade', 'data'), name='rotina_whatsapp_um_por_atividade_e_dia'),
        ),
    ]
