# Generated by Django 5.2.5 on 2026-09-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0004_domingo_e_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisowhatsapp',
            name='tentado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última tentativa'),
        ),
        migrations.AddField(
            model_name='avisowhatsapp',
            name='tentativas',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Tentativas'),
        ),
    ]
