# Generated by Django 5.2.5 on 2026-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0005_tentativas_do_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisowhatsapp',
            name='tentativas',
            field=models.PositiveSmallIntegerField(db_default=1, default=1, verbose_name='Tentativas'),
        ),
    ]
