# Generated by Django 5.2.5 on 2026-09-22 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0006_default_no_banco_das_tentativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividademodelo',
            name='minutos_whatsapp',
            field=models.PositiveSmallIntegerField(db_default=5, default=5, help_text='Quanto tempo antes do início sai o lembrete no WhatsApp. 0 = na hora em que começa.', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Lembrete no WhatsApp (minutos antes)'),
        ),
        migrations.AddField(
            model_name='atividaderotina',
            name='minutos_whatsapp',
            field=models.PositiveSmallIntegerField(db_default=5, default=5, help_text='Quanto tempo antes do início sai o lembrete no WhatsApp. 0 = na hora em que começa.', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Lembrete no WhatsApp (minutos antes)'),
        ),
        migrations.AddConstraint(
            model_name='atividademodelo',
            constraint=models.CheckConstraint(condition=models.Q(('minutos_whatsapp__lte', 120)), name='rotina_atividademodelo_whatsapp_ate_2h_antes'),
        ),
        migrations.AddConstraint(
            model_name='atividaderotina',
            constraint=models.CheckConstraint(condition=models.Q(('minutos_whatsapp__lte', 120)), name='rotina_atividaderotina_whatsapp_ate_2h_antes'),
        ),
    ]
