# Generated by Django 5.2.5 on 2026-09-25 17:33

import core.storage
import django.db.models.deletion
import rotina.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0007_minutos_do_whatsapp_por_atividade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividademodelo',
            name='exige_comprovante',
            field=models.BooleanField(db_default=False, default=False, help_text='Para dar a atividade por concluída, a pessoa precisa enviar um comprovante (foto, print ou PDF).', verbose_name='Necessita comprovante'),
        ),
        migrations.AddField(
            model_name='atividaderotina',
            name='exige_comprovante',
            field=models.BooleanField(db_default=False, default=False, help_text='Para dar a atividade por concluída, a pessoa precisa enviar um comprovante (foto, print ou PDF).', verbose_name='Necessita comprovante'),
        ),
        migrations.CreateModel(
            name='ConclusaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Dia')),
                ('comprovante', models.FileField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to=rotina.models.upload_comprovante, verbose_name='Comprovante')),
                ('comprovante_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do arquivo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Concluída em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='rotina.atividaderotina', verbose_name='Atividade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotina_conclusoes', to=settings.AUTH_USER_MODEL, verbose_name='Concluída por')),
            ],
            options={
                'verbose_name': 'Conclusão de atividade',
                'verbose_name_plural': 'Conclusões de atividades',
                'ordering': ['-data', '-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('atividade', 'data'), name='rotina_conclusao_uma_por_atividade_e_dia')],
            },
        ),
    ]
